'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Check, Clock3, History, Mic, Sparkles, Target } from 'lucide-react'
import { onboardingKo } from '@/lib/onboarding-i18n'
import { formatDurationWords } from '@/lib/self-introduction-data'
import { getQuestionProgress, interviewQuestionById, interviewQuestions, type EvaluationScore, type InterviewAnswerAnalysis, type InterviewAttempt, type InterviewCategory, type InterviewDifficulty, type InterviewQuestion, type QuestionProgress } from '@/lib/interview-practice-data'
import { DiagnosisFrame } from '@/components/self-introduction/self-introduction-components'
import { getPracticeQuestionsForAirline } from '@/lib/airline-knowledge-repository'
import { interviewPracticeQueueRepository, practiceQueueReasonLabel, recommendedQueueReason, resolveInterviewQuestion, type InterviewPracticeQueueItem, type PracticeQueueReason } from '@/lib/interview-practice-queue'

const card='rounded-2xl border border-border bg-card p-4'
const primary='h-12 rounded-xl bg-navy px-4 text-sm font-bold text-ivory focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold'
const categoryOrder:InterviewCategory[]=['introduction_and_motivation','behavioral_experience','customer_situation','safety_and_role_judgment']
const categoryLabel=(id:InterviewCategory)=>(onboardingKo.interviewPractice.categories as Record<string,{title:string;description:string}>)[id]

export function InterviewAudioAnalysis({attempt}:{attempt:InterviewAttempt}){const m=attempt.audioMetrics;if(!m)return null;const volume=m.volume.averageDbfs===null?'측정 불가':`${m.volume.averageDbfs.toFixed(1)} dBFS`;return <section className={`${card} mt-7`} aria-label="말하기 분석"><h2 className="text-base font-bold text-navy">말하기 분석</h2><p className="mt-1 text-xs text-muted-foreground">마이크 입력 기준 음량(dBFS) · 참고용</p><div className="mt-3 grid grid-cols-2 gap-2 text-sm text-midnight"><p>평균 음량 <strong>{volume}</strong></p><p>음량 안정성 <strong>{m.volume.stability===null?'측정 불가':`${Math.round(m.volume.stability)}%`}</strong></p><p>긴 쉼 <strong>{m.pauses.longCount}회</strong></p><p>가장 긴 쉼 <strong>{(m.pauses.longestMs/1000).toFixed(1)}초</strong></p>{m.speech.wordsPerMinute!==null&&<p>추정 말하기 속도 <strong>{m.speech.wordsPerMinute} WPM</strong></p>}</div>{m.quality.clippingDetected&&<p className="mt-3 rounded-xl bg-gold/15 p-3 text-xs text-midnight">마이크 입력이 일부 크게 잡혔어요. 다음에는 녹음 거리를 조금 조절해 보세요.</p>}{m.quality.tooQuietDetected&&!m.quality.insufficientAudio&&<p className="mt-3 rounded-xl bg-secondary p-3 text-xs text-midnight">입력 음량이 낮게 잡혔어요. 마이크 연결과 거리를 확인해 보세요.</p>}{m.quality.insufficientAudio&&<p className="mt-3 text-xs text-muted-foreground">분석할 녹음 신호가 충분하지 않아 일부 항목은 참고용으로만 표시합니다.</p>}</section>}

export function InterviewCategoryCard({category,completed,recentScore,onStart}:{category:InterviewCategory;completed:number;recentScore?:number;onStart:()=>void}){const meta=categoryLabel(category);return <article className={card}><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-secondary text-navy"><Mic className="h-5 w-5"/></span><div className="min-w-0 flex-1"><h3 className="font-bold text-navy">{meta.title}</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{meta.description}</p></div></div><div className="mt-4 flex items-center justify-between border-t border-border pt-3"><span className="text-xs text-muted-foreground">완료 {completed}/6 · {recentScore?`최근 ${recentScore}점`:'첫 연습 전'}</span><button className="text-sm font-bold text-navy focus-visible:ring-2 focus-visible:ring-gold" onClick={onStart}>시작 <ArrowRight className="inline h-4 w-4"/></button></div></article>}

export function RecommendedQuestionCard({question,onStart}:{question:InterviewQuestion;onStart:()=>void}){return <section className="rounded-3xl bg-navy p-5 text-ivory"><div className="flex items-center gap-2 text-gold"><Sparkles className="h-4 w-4"/><span className="eyebrow">TODAY’S QUESTION</span></div><p className="mt-4 text-base font-bold leading-relaxed">{question.prompt}</p><button className="mt-5 h-11 w-full rounded-xl bg-coral text-sm font-bold text-white" onClick={onStart}>추천 질문 시작</button></section>}

export function InterviewQuestionActions({question,airlineId,sourceAttemptId,reason='manual'}:{question:InterviewQuestion;airlineId?:string;sourceAttemptId?:string;reason?:PracticeQueueReason}){const [revision,setRevision]=useState(0);useEffect(()=>{const refresh=()=>setRevision(value=>value+1);window.addEventListener(interviewPracticeQueueRepository.eventName,refresh);return()=>window.removeEventListener(interviewPracticeQueueRepository.eventName,refresh)},[]);const favorite=interviewPracticeQueueRepository.isFavorite(question.id);const queued=interviewPracticeQueueRepository.listOpen().some(item=>item.questionId===question.id);void revision;return <div className="mt-3 grid grid-cols-2 gap-2"><button type="button" aria-pressed={favorite} onClick={()=>interviewPracticeQueueRepository.toggleFavorite({question,airlineId,source:sourceAttemptId?'result':'question'})} className="h-10 rounded-xl border border-border bg-card text-xs font-bold text-navy">{favorite?'★ 즐겨찾기':'☆ 즐겨찾기'}</button><button type="button" disabled={queued} onClick={()=>interviewPracticeQueueRepository.addQueue({question,airlineId,sourceAttemptId,reason})} className="h-10 rounded-xl border border-border bg-card text-xs font-bold text-navy disabled:opacity-50">{queued?'재연습에 담김':'재연습에 추가'}</button></div>}

export function InterviewPracticeQueuePanel({onStartQuestion,onStartQueued}:{onStartQuestion:(question:InterviewQuestion)=>void;onStartQueued:(question:InterviewQuestion,item:InterviewPracticeQueueItem)=>void}){const [revision,setRevision]=useState(0);useEffect(()=>{const refresh=()=>setRevision(value=>value+1);window.addEventListener(interviewPracticeQueueRepository.eventName,refresh);return()=>window.removeEventListener(interviewPracticeQueueRepository.eventName,refresh)},[]);const queue=interviewPracticeQueueRepository.listOpen().slice(0,5),favorites=interviewPracticeQueueRepository.listFavorites().slice(-5).reverse().map(item=>({item,question:resolveInterviewQuestion(item.questionId,item.airlineId)})).filter(row=>row.question);void revision;return <section className="px-5 pt-4"><div className="rounded-3xl border border-border bg-card p-5"><h2 className="font-bold text-navy">재연습 큐</h2><div className="mt-3 space-y-2">{queue.length?queue.map(item=>{const question=resolveInterviewQuestion(item.questionId,item.airlineId);return question?<button key={item.id} onClick={()=>onStartQueued(question,item)} className="w-full rounded-xl bg-secondary/60 p-3 text-left"><span className="text-[11px] font-bold text-gold">{practiceQueueReasonLabel[item.reason]}</span><p className="mt-1 text-sm font-semibold text-navy">{question.prompt}</p></button>:null}):<p className="text-sm text-muted-foreground">재연습할 질문이 아직 없어요.</p>}</div><h2 className="mt-5 font-bold text-navy">즐겨찾기 질문</h2><div className="mt-3 space-y-2">{favorites.length?favorites.map(({item,question})=><button key={item.questionId} onClick={()=>question&&onStartQuestion(question)} className="w-full rounded-xl border border-border p-3 text-left text-sm font-semibold text-navy">{question?.prompt}</button>):<p className="text-sm text-muted-foreground">별표를 눌러 질문을 모아보세요.</p>}</div></div></section>}

export function InterviewPracticeHome({attempts,onSelectCategory,onStartQuestion,onOpenExperience}:{attempts:InterviewAttempt[];onSelectCategory:(category:InterviewCategory)=>void;onStartQuestion:(question:InterviewQuestion)=>void;onOpenExperience?:()=>void}){
  const weekCount=attempts.filter(a=>Date.now()-new Date(a.createdAt).getTime()<7*86400000).length;const completed=new Set(attempts.map(a=>a.questionId)).size;const avgDelta=attempts.filter(a=>a.previousAttemptId).reduce((sum,a)=>{const p=attempts.find(x=>x.id===a.previousAttemptId);return sum+(p?a.analysis.overallScore-p.analysis.overallScore:0)},0)/Math.max(1,attempts.filter(a=>a.previousAttemptId).length);const recent=attempts.slice(0,3);const recommended=interviewQuestions.find(q=>!attempts.some(a=>a.questionId===q.id))??interviewQuestions[0];const actualWeakness=attempts.flatMap(a=>a.analysis.evaluationScores).find(item=>item.status==='needs_improvement')?.key;const weaknessLabel=actualWeakness?scoreLabels[actualWeakness]??'최근 답변 보완':'기록 확인 중'
  return <DiagnosisFrame title={onboardingKo.interviewPractice.title} subtitle={onboardingKo.interviewPractice.supporting}><section className="grid grid-cols-2 gap-2">{[['이번 주 연습',`${weekCount}회`],['완료한 질문',`${completed}개`],['평균 개선도',`${avgDelta>0?'+':''}${Math.round(avgDelta)}점`],['우선 보완',weaknessLabel]].map(([l,v])=><div key={l} className={card}><p className="text-[11px] text-muted-foreground">{l}</p><strong className="mt-1 block text-base text-navy">{v}</strong></div>)}</section>{onOpenExperience&&<section className={`${card} mt-5`}><h2 className="font-bold text-navy">활용할 경험을 먼저 정리해 보세요.</h2><p className="mt-2 text-xs text-muted-foreground">저장한 경험은 여러 면접 질문에서 다시 활용할 수 있어요.</p><button className="mt-3 text-sm font-bold text-navy" onClick={onOpenExperience}>경험 저장소 열기 <ArrowRight className="inline h-4 w-4"/></button></section>}<div className="mt-7 space-y-3"><h2 className="text-base font-bold text-navy">면접 유형</h2>{categoryOrder.map(c=>{const ca=attempts.filter(a=>a.category===c);return <InterviewCategoryCard key={c} category={c} completed={new Set(ca.map(a=>a.questionId)).size} recentScore={ca[0]?.analysis.overallScore} onStart={()=>onSelectCategory(c)}/>})}</div><div className="mt-7"><RecommendedQuestionCard question={recommended} onStart={()=>onStartQuestion(recommended)}/></div><div className="mt-7"><InterviewAttemptHistory attempts={recent} onRetry={(q)=>onStartQuestion(q)}/></div></DiagnosisFrame>}

export function InterviewQuestionCard({question,progress,onStart}:{question:InterviewQuestion;progress:QuestionProgress;onStart:()=>void}){return <article className={card}><div className="flex items-center justify-between"><span className="rounded-full bg-secondary px-2.5 py-1 text-[11px] font-bold text-midnight">{onboardingKo.interviewPractice.difficulties[question.difficulty]}</span><span className="text-[11px] text-muted-foreground">{progress.completed?`최근 ${progress.latestScore}점`:'미연습'}</span></div><h3 className="mt-3 text-sm font-bold leading-relaxed text-navy">{question.prompt}</h3><button onClick={onStart} className="mt-4 h-10 w-full rounded-xl border border-navy text-sm font-bold text-navy focus-visible:ring-2 focus-visible:ring-gold">{progress.completed?'다시 연습':'답변 시작'}</button></article>}

export function InterviewQuestionList({category,onBack,onStart}:{category:InterviewCategory;onBack:()=>void;onStart:(q:InterviewQuestion)=>void}){const [filter,setFilter]=useState<'all'|InterviewDifficulty|'unpracticed'|'retry'>('all');const [sort,setSort]=useState<'recommended'|'unpracticed'|'recent'|'lowest'>('recommended');const list=useMemo(()=>{let rows=interviewQuestions.filter(q=>q.category===category).map(q=>({q,p:getQuestionProgress(q.id)}));if(['beginner','intermediate','advanced'].includes(filter))rows=rows.filter(x=>x.q.difficulty===filter);if(filter==='unpracticed')rows=rows.filter(x=>!x.p.completed);if(filter==='retry')rows=rows.filter(x=>x.p.completed);if(sort==='unpracticed')rows.sort((a,b)=>Number(a.p.completed)-Number(b.p.completed));if(sort==='recent')rows.sort((a,b)=>(b.p.lastPracticedAt??'').localeCompare(a.p.lastPracticedAt??''));if(sort==='lowest')rows.sort((a,b)=>(a.p.latestScore||999)-(b.p.latestScore||999));return rows},[category,filter,sort]);const meta=categoryLabel(category);return <DiagnosisFrame title={meta.title} subtitle={meta.description} onBack={onBack}><div className="flex gap-2 overflow-x-auto pb-2" aria-label="질문 필터">{(['all','beginner','intermediate','advanced','unpracticed','retry'] as const).map(id=><button key={id} onClick={()=>setFilter(id)} aria-pressed={filter===id} className={`shrink-0 rounded-full px-3 py-2 text-xs font-bold ${filter===id?'bg-navy text-ivory':'bg-card text-muted-foreground'}`}>{onboardingKo.interviewPractice.filters[id]}</button>)}</div><label className="mt-3 block text-xs text-muted-foreground">정렬<select value={sort} onChange={e=>setSort(e.target.value as typeof sort)} className="ml-2 rounded-lg border border-border bg-card px-2 py-2 text-navy">{(['recommended','unpracticed','recent','lowest'] as const).map(id=><option key={id} value={id}>{onboardingKo.interviewPractice.sorts[id]}</option>)}</select></label><div className="mt-5 space-y-3">{list.map(({q,p})=><InterviewQuestionCard key={q.id} question={q} progress={p} onStart={()=>onStart(q)}/>)}{!list.length&&<p className="py-10 text-center text-sm text-muted-foreground">조건에 맞는 질문이 없어요.</p>}</div></DiagnosisFrame>}

export function AirlineInterviewQuestionList({category,targetAirlineId,onBack,onStart}:{category:InterviewCategory;targetAirlineId?:string;onBack:()=>void;onStart:(q:InterviewQuestion)=>void}){const list=getPracticeQuestionsForAirline({airlineId:targetAirlineId,category});return <DiagnosisFrame title={categoryLabel(category).title} subtitle={categoryLabel(category).description} onBack={onBack}><div className="mt-5 space-y-3">{list.map(q=><div key={q.id}>{q.airlineTags?.length&&<p className="mb-1 text-xs font-bold text-gold">Emirates 지원 준비 질문</p>}<InterviewQuestionCard question={q} progress={getQuestionProgress(q.id)} onStart={()=>onStart(q)}/></div>)}</div></DiagnosisFrame>}

export function InterviewQuestionIntro({question,previous,experienceSection,onStart,onBack}:{question:InterviewQuestion;previous?:InterviewAttempt;experienceSection?:React.ReactNode;onStart:()=>void;onBack:()=>void}){const meta=categoryLabel(question.category);return <DiagnosisFrame title="답변 준비" subtitle={meta.title} onBack={onBack} footer={<button className={`${primary} w-full`} onClick={onStart}>녹음 준비하기</button>}><section className="interview-question-panel rounded-3xl bg-navy p-6 text-ivory"><span className="eyebrow text-gold">INTERVIEW QUESTION</span><p className="mt-4 text-xl font-bold leading-relaxed">{question.prompt}</p></section><p className="interview-guidance-panel mt-5 rounded-2xl bg-secondary/60 p-4 text-sm leading-relaxed text-midnight">{question.evaluationRubric.guidance}</p>{experienceSection}<div className={`${card} mt-4 flex items-center justify-between`}><span className="text-sm text-muted-foreground">권장 답변 범위</span><strong className="text-sm text-navy">{question.suggestedAnswerRange?.minSeconds}~{question.suggestedAnswerRange?.maxSeconds}초 · 참고용</strong></div>{previous&&<div className={`${card} mt-4`}><p className="text-xs font-bold text-gold">재도전 목표</p><p className="mt-2 text-sm text-navy">이전 {previous.analysis.overallScore}점 · {previous.analysis.improvements[0]??'핵심 기준'} 보완</p></div>}<p className="mt-5 text-xs leading-relaxed text-muted-foreground">시간 제한과 자동 종료 없이 자유롭게 답한 뒤 실제 시간과 내용을 함께 분석합니다.</p></DiagnosisFrame>}

const scoreLabels:Record<string,string>={question_fit:'질문 적합성',core_message:'핵심 메시지',structure:'답변 구조',specificity:'구체성',role_connection:'직무 연결',motivation_authenticity:'지원 이유의 진정성',airline_reason:'항공사 선택 이유',situation_clarity:'상황의 명확성',action_specificity:'본인 행동',result_learning:'결과와 배운 점',star_structure:'STAR 구조',empathy:'공감 표현',situation_assessment:'상황 파악',policy_compliance:'규정 준수',resolution_process:'해결 절차',service_recovery:'서비스 회복',safety_priority:'안전 우선',immediate_action:'즉시 조치',reporting:'보고 체계',procedure:'절차 준수',follow_up:'후속 조치'}
export function EvaluationScoreCard({score}:{score:EvaluationScore}){const label=onboardingKo.interviewPractice.statuses[score.status];return <article className={card}><div className="flex items-center justify-between"><h3 className="text-sm font-bold text-navy">{scoreLabels[score.key]??score.key}</h3><span className="rounded-full bg-secondary px-2.5 py-1 text-[11px] font-bold text-midnight">{label} · {score.score}점</span></div><p className="mt-3 text-sm leading-relaxed text-midnight">{score.feedback}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">개선 팁 · {score.tip}</p></article>}
export function CategoryRubricSection({analysis}:{analysis:InterviewAnswerAnalysis}){return <section><h2 className="text-base font-bold text-navy">상세 평가</h2><div className="mt-3 space-y-2">{analysis.evaluationScores.map(score=><EvaluationScoreCard key={score.key} score={score}/>)}</div></section>}
export function NextQuestionRecommendations({ids,onStart}:{ids:string[];onStart:(q:InterviewQuestion)=>void}){return <section><h2 className="text-base font-bold text-navy">다음으로 이런 질문을 연습해 보세요</h2><div className="mt-3 space-y-2">{ids.map(id=>interviewQuestionById.get(id)).filter((q):q is InterviewQuestion=>!!q).map(q=><button key={q.id} onClick={()=>onStart(q)} className="flex w-full items-center justify-between rounded-2xl border border-border bg-card p-4 text-left text-sm font-semibold leading-relaxed text-navy focus-visible:ring-2 focus-visible:ring-gold">{q.prompt}<ArrowRight className="ml-3 h-4 w-4 shrink-0"/></button>)}</div></section>}
export function InterviewAttemptHistory({attempts,onRetry}:{attempts:InterviewAttempt[];onRetry:(q:InterviewQuestion)=>void}){return <section><div className="flex items-center gap-2"><History className="h-4 w-4 text-gold"/><h2 className="text-base font-bold text-navy">연습 기록</h2></div><div className="mt-3 space-y-2">{attempts.length?attempts.map(a=>{const q=interviewQuestionById.get(a.questionId);const previous=a.previousAttemptId?attempts.find(x=>x.id===a.previousAttemptId):undefined;return <article key={a.id} className={card}><p className="text-sm font-bold leading-relaxed text-navy">{q?.shortTitle??a.questionId}</p><p className="mt-1 text-xs text-muted-foreground">{categoryLabel(a.category).title} · {formatDurationWords(a.durationSeconds)} · {a.analysis.overallScore}점 {previous&&`· ${a.analysis.overallScore-previous.analysis.overallScore>=0?'+':''}${a.analysis.overallScore-previous.analysis.overallScore}`}</p>{q&&<button onClick={()=>onRetry(q)} className="mt-3 text-xs font-bold text-navy">다시 연습</button>}</article>}):<p className="rounded-2xl border border-dashed border-border p-6 text-center text-sm text-muted-foreground">{onboardingKo.interviewPractice.empty}</p>}</div></section>}
export function QuestionProgressSummary({progress}:{progress:QuestionProgress}){const mastery=progress.bestScore>=88?'우수':progress.bestScore>=78?'안정적':progress.attemptCount>=2?'연습 중':'시작';return <section className="grid grid-cols-2 gap-2">{[['전체 시도',`${progress.attemptCount}회`],['최고 점수',`${progress.bestScore}점`],['최근 점수',`${progress.latestScore}점`],['숙련 상태',mastery]].map(([l,v])=><div key={l} className={card}><p className="text-[11px] text-muted-foreground">{l}</p><strong className="mt-1 block text-navy">{v}</strong></div>)}</section>}

export function InterviewAnswerResult({attempt,allAttempts,onHome,onRetry,onNext,sessionMode=false}:{attempt:InterviewAttempt;allAttempts:InterviewAttempt[];onHome:()=>void;onRetry:()=>void;onNext:(q:InterviewQuestion)=>void;sessionMode?:boolean}){const q=resolveInterviewQuestion(attempt.questionId,attempt.targetAirlineId)!;const a=attempt.analysis;const range=q.suggestedAnswerRange;const relation=attempt.durationSeconds<(range?.minSeconds??0)?'권장 범위보다 짧지만 내용 충실도를 함께 확인했어요.':attempt.durationSeconds>(range?.maxSeconds??999)?'권장 범위보다 길지만 구조와 반복 여부를 함께 확인했어요.':'권장 범위 안에서 답변했습니다.';return <DiagnosisFrame title="면접 답변 분석 결과" onBack={onHome} footer={<button className={`${primary} w-full`} onClick={onHome}>면접 훈련실로 돌아가기</button>}><section className="rounded-3xl bg-navy p-5 text-ivory"><span className="text-xs text-gold">{categoryLabel(q.category).title}</span><h2 className="mt-2 text-base font-bold leading-relaxed">{q.prompt}</h2><div className="mt-5 grid grid-cols-2 gap-3 border-t border-white/10 pt-4"><div><p className="text-xs text-ivory/60">실제 답변 시간</p><strong>{formatDurationWords(attempt.durationSeconds)}</strong></div><div><p className="text-xs text-ivory/60">종합 점수</p><strong className="text-xl">{a.overallScore}점</strong></div></div><p className="mt-4 text-sm leading-relaxed">{a.summary}</p></section><p className="mt-4 rounded-2xl bg-secondary/60 p-4 text-sm leading-relaxed text-midnight">{relation}<br/>{a.timingAnalysis.feedback}</p><div className="mt-7"><CategoryRubricSection analysis={a}/></div><section className="mt-7"><h2 className="text-base font-bold text-navy">잘한 점 · 정리할 점 · 강화할 점</h2><div className="mt-3 space-y-2">{[['잘한 점',a.strengths[0]??'질문의 방향을 유지한 점'],['줄이거나 정리할 점',a.timingAnalysis.assessment==='slightly_long'?'반복되는 배경 설명':'불필요한 연결 표현'],['추가하거나 강화할 점',a.improvements[0]??'결론의 직무 연결']].map(([l,v])=><div key={l} className={card}><span className="text-xs font-bold text-gold">{l}</span><p className="mt-2 text-sm text-midnight">{scoreLabels[v]??v}</p></div>)}</div></section><div className="mt-7"><QuestionProgressSummary progress={getQuestionProgress(q.id)}/></div><button className="mt-5 h-12 w-full rounded-xl bg-coral text-sm font-bold text-white" onClick={onRetry}>{retryLabels[a.recommendedRetryMode]}</button>{!sessionMode&&<div className="mt-7"><NextQuestionRecommendations ids={a.nextQuestionIds} onStart={onNext}/></div>}<div className="mt-7"><InterviewAttemptHistory attempts={allAttempts.filter(x=>x.questionId===q.id)} onRetry={()=>onRetry()}/></div></DiagnosisFrame>}

export const retryLabels:Record<InterviewAnswerAnalysis['recommendedRetryMode'],string>={add_specific_experience:'경험을 구체화해 다시 답하기',clarify_structure:'답변 구조를 정리해 다시 답하기',shorten_answer:'핵심 중심으로 압축해 다시 답하기',strengthen_role_connection:'직무 연결을 강화해 다시 답하기',improve_safety_reasoning:'안전 판단을 보완해 다시 답하기',improve_customer_empathy:'공감 표현을 보완해 다시 답하기',repeat_current_structure:'현재 구조로 다시 연습하기'}
