"use client";

import { useMemo, useState, type ReactNode } from "react";
import { ArrowLeft, Building2, Check, ExternalLink, Plane, Search, Star } from "lucide-react";
import { listApplicationAnswers, listAnswersByAirline, type ApplicationAnswer } from "@/lib/application-answer-repository";
import { experienceRepository, type CareerExperience } from "@/lib/experience-repository";
import { loadInterviewAttempts, type InterviewAttempt } from "@/lib/interview-practice-data";
import { questionProvenance, questionProvenanceLabels } from "@/lib/airline-question-provenance";
import {
  buildEvidenceQuestionPool,
  calculateCommunityPatterns,
  canPracticeCommunityQuestion,
  interviewStageLabels,
  moderationStatusLabels,
  type QuestionInterviewStage,
} from "@/lib/airline-question-community-evidence";
import {
  airlineTargetingRepository,
  buildAirlineWorkspaceProfiles,
  buildPreparationStatus,
  calculateQuestionPatterns,
  compareAirlines,
  filterAirlines,
  filterQuestions,
  freshnessFor,
  getSourceBackedWorkspaceQuestions,
  isAirlineEligibleForAi,
  mergeAirlineFleet,
  mergeAirlineRoutes,
  normalizeTargetPreferences,
  type AirlineCarrierType,
  type AirlineCountryGroup,
  type AirlineOperationScope,
  type AirlineTargetPreferences,
  type AirlineWorkspaceProfile,
  type WorkspaceQuestion,
} from "@/lib/airline-targeting-workspace";

type Tab = "overview" | "application" | "questions" | "routes" | "fleet" | "experience" | "practice";
const tabs: [Tab, string][] = [["overview", "Overview"], ["application", "Application"], ["questions", "Questions"], ["routes", "Routes"], ["fleet", "Fleet"], ["experience", "My Experience"], ["practice", "Practice"]];
const countryFilters: [AirlineCountryGroup, string][] = [["ALL", "전체"], ["KOREA", "대한민국"], ["JAPAN", "일본"], ["CHINA", "중국권"], ["SOUTHEAST_ASIA", "동남아시아"], ["MIDDLE_EAST", "중동"], ["EUROPE", "유럽"], ["NORTH_AMERICA", "북미"], ["OTHER", "기타"]];
const carrierLabels: Record<AirlineCarrierType, string> = { FULL_SERVICE: "대형 항공사", LOW_COST: "저비용 항공사", HYBRID: "하이브리드", REGIONAL: "지역 항공사", OTHER: "기타" };
const scopeLabels: Record<AirlineOperationScope, string> = { DOMESTIC: "국내선 운항", INTERNATIONAL: "국제선 운항", BOTH: "국내·국제 모두" };
const patternLabels: Record<string, string> = { MOTIVATION: "지원동기", COMPANY_FIT: "회사 적합성", SERVICE: "서비스", SAFETY: "안전", TEAMWORK: "팀워크", CONFLICT: "갈등", CUSTOMER_COMPLAINT: "고객 불만", GLOBAL_MINDSET: "글로벌 역량", STRENGTH_WEAKNESS: "강점·약점", SELF_INTRODUCTION: "자기소개", EXPERIENCE: "경험", SITUATIONAL: "상황대처", OTHER: "기타" };
const recruitmentRecordLabel = (item: { recruitmentType?: string; recruitmentPeriod?: string; recordStatus?: string }) => [item.recruitmentType, item.recruitmentPeriod, item.recordStatus].filter(Boolean).join(" · ");
type QuestionSourceFilter = "ALL" | "OFFICIAL" | "USER_REPORTED" | "VERIFIED_SECONDARY" | "UNVERIFIED_COMMUNITY";

const panel = "rounded-3xl border border-border bg-card p-5";
const empty = (message: string) => <div className="rounded-2xl border border-dashed border-border p-7 text-center text-sm text-muted-foreground">{message}</div>;

function AirlineList({ profiles, preferences, onSelect, onPreferencesChange }: { profiles: AirlineWorkspaceProfile[]; preferences: AirlineTargetPreferences; onSelect: (profile: AirlineWorkspaceProfile) => void; onPreferencesChange: (preferences: AirlineTargetPreferences, selected: AirlineWorkspaceProfile, mode: "primary" | "interest") => void }) {
  const [search, setSearch] = useState("");
  const [countryGroup, setCountryGroup] = useState<AirlineCountryGroup>("ALL");
  const [countryCode, setCountryCode] = useState("");
  const [scope, setScope] = useState<AirlineOperationScope | "ALL">("ALL");
  const [carrier, setCarrier] = useState<AirlineCarrierType | "ALL">("ALL");
  const visible = useMemo(() => filterAirlines(profiles, { search, countryGroup, countryCode, operationScope: scope, carrierType: carrier }), [profiles, search, countryGroup, countryCode, scope, carrier]);
  return <>
    <div className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground"/><input value={search} onChange={(event) => setSearch(event.target.value)} aria-label="항공사 검색" placeholder="항공사명, 국가, IATA 검색" className="h-11 w-full rounded-xl border border-border bg-card pl-10 pr-3 text-sm"/></div>
    <div className="mt-3 flex gap-2 overflow-x-auto pb-1" aria-label="국가·지역 필터">{countryFilters.map(([value, label]) => <button key={value} onClick={() => setCountryGroup(value)} aria-pressed={countryGroup === value} className={`min-h-10 shrink-0 rounded-full px-4 text-xs font-bold ${countryGroup === value ? "bg-navy text-ivory" : "border border-border bg-card text-muted-foreground"}`}>{label}</button>)}</div>
    <select aria-label="국가 상세 필터" value={countryCode} onChange={(event) => setCountryCode(event.target.value)} className="mt-2 h-10 w-full rounded-xl border border-border bg-card px-3 text-xs sm:max-w-xs"><option value="">전체 국가</option>{[...new Map(profiles.map((profile) => [profile.countryCode, profile.countryNameKo])).entries()].sort((a, b) => a[1].localeCompare(b[1], "ko")).map(([code, name]) => <option key={code} value={code}>{name}</option>)}</select>
    <div className="mt-2 flex gap-2 overflow-x-auto pb-1" aria-label="운항 범위 필터">{([["ALL", "전체 운항"], ["DOMESTIC", "국내선"], ["INTERNATIONAL", "국제선"], ["BOTH", "국내·국제"]] as const).map(([value, label]) => <button key={value} onClick={() => setScope(value)} aria-pressed={scope === value} className={`min-h-10 shrink-0 rounded-full px-4 text-xs font-bold ${scope === value ? "bg-gold text-navy" : "border border-border bg-card text-muted-foreground"}`}>{label}</button>)}</div>
    <div className="mt-2 flex gap-2 overflow-x-auto pb-1" aria-label="항공사 유형 필터">{([["ALL", "전체 유형"], ["LOW_COST", "저비용 항공사"], ["FULL_SERVICE", "대형 항공사"], ["HYBRID", "하이브리드"], ["REGIONAL", "지역 항공사"]] as const).map(([value, label]) => <button key={value} onClick={() => setCarrier(value)} aria-pressed={carrier === value} className={`min-h-10 shrink-0 rounded-full px-4 text-xs font-bold ${carrier === value ? "bg-navy text-ivory" : "border border-border bg-card text-muted-foreground"}`}>{label}</button>)}</div>
    <p className="mt-4 text-xs text-muted-foreground">검색 결과 {visible.length}개 · 운항 범위는 확인된 노선 자료가 있을 때만 표시됩니다.</p>
    <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visible.map((profile) => {
      const primary = preferences.primary?.id === profile.id;
      const interested = preferences.interests.some((item) => item.id === profile.id);
      return <article key={profile.id} className={panel}>
        <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-gold">{profile.iataCode ?? "IATA 미확인"} · {profile.countryNameKo}</p><h2 className="mt-1 text-lg font-bold text-navy">{profile.nameKo}</h2><p className="text-xs text-muted-foreground">{profile.nameEn}</p></div>{primary ? <span className="rounded-full bg-gold/15 px-2 py-1 text-[11px] font-bold text-gold">1순위</span> : null}</div>
        <div className="mt-3 flex flex-wrap gap-2 text-[11px]"><span className="rounded-full bg-secondary px-2 py-1">{carrierLabels[profile.carrierType]}</span><span className="rounded-full bg-secondary px-2 py-1">{profile.operationScope ? scopeLabels[profile.operationScope] : "운항 범위 미확인"}</span></div>
        <div className="mt-4 grid grid-cols-2 gap-2"><button onClick={() => onPreferencesChange(preferences, profile, "primary")} className="min-h-11 rounded-xl bg-navy px-2 text-xs font-bold text-ivory">{primary ? <><Check className="mr-1 inline h-3 w-3"/>1순위 설정됨</> : "타겟 항공사로 설정"}</button><button onClick={() => onPreferencesChange(preferences, profile, "interest")} disabled={primary} className="min-h-11 rounded-xl border border-border px-2 text-xs font-bold text-navy disabled:opacity-40"><Star className="mr-1 inline h-3 w-3" fill={interested ? "currentColor" : "none"}/>{interested ? "관심 해제" : "관심 추가"}</button></div>
        <button onClick={() => onSelect(profile)} className="mt-2 min-h-11 w-full rounded-xl border border-navy text-sm font-bold text-navy">워크스페이스 열기</button>
      </article>;
    })}</div>
    {!visible.length ? empty("조건에 맞는 항공사가 없습니다. 운항 범위가 미확인인 항공사는 국내선/국제선 필터에서 제외됩니다.") : null}
  </>;
}

function QuestionComposer({ airlineId, kind: fixedKind, onSaved }: { airlineId: string; kind?: WorkspaceQuestion["kind"]; onSaved: () => void }) {
  const [kind, setKind] = useState<WorkspaceQuestion["kind"]>(fixedKind ?? "INTERVIEW"); const [text, setText] = useState(""); const [year, setYear] = useState(""); const [period, setPeriod] = useState(""); const [locale, setLocale] = useState<"ko" | "en" | "ja">("ko"); const [stage, setStage] = useState<QuestionInterviewStage>("OTHER"); const [attested, setAttested] = useState(false); const [notice, setNotice] = useState("");
  const save = () => {
    if (!text.trim() || !attested) return;
    const result = airlineTargetingRepository.addUserQuestion({ airlineId, kind, questionText: text, locale, year: year ? Number(year) : undefined, recruitmentPeriod: period, interviewStage: kind === "INTERVIEW" ? stage : "DOCUMENT", selfAttested: attested });
    if (result.ok) {
      setText(""); setYear(""); setPeriod(""); setAttested(false); setNotice("내 기기에 검토 대기 제보로 저장했습니다. 공개 공유·공식 승격·연습 연결은 수락 전까지 되지 않습니다."); onSaved();
    } else {
      const labels: Record<string, string> = { EMPTY: "질문을 입력해 주세요.", TOO_LONG: "질문은 500자 이내로 입력해 주세요.", URL_SPAM: "질문 본문에는 URL을 넣을 수 없습니다.", PII_DETECTED: "연락처 등 개인정보를 제거해 주세요.", DUPLICATE: "이미 저장된 같은 질문이 있습니다.", ATTESTATION_REQUIRED: "직접 경험 확인이 필요합니다." };
      setNotice("code" in result ? labels[result.code] ?? "이 기기에 저장하지 못했습니다." : "이 기기에 저장하지 못했습니다.");
    }
  };
  return <div className="rounded-2xl bg-secondary/60 p-4"><strong className="text-sm text-navy">{fixedKind === "APPLICATION" ? "지원서 질문 제보" : "면접 질문 제보"}</strong><p className="mt-1 text-xs text-muted-foreground">직접 겪은 질문만 이 기기에 저장합니다. 제보는 공식 질문으로 자동 승격되거나 공개되지 않습니다.</p>{!fixedKind ? <div className="mt-3 flex gap-2">{(["INTERVIEW", "APPLICATION"] as const).map((value) => <button type="button" key={value} onClick={() => setKind(value)} className={`min-h-10 rounded-full px-4 text-xs font-bold ${kind === value ? "bg-navy text-ivory" : "bg-card text-navy"}`}>{value === "INTERVIEW" ? "면접" : "지원서"}</button>)}</div> : null}<textarea value={text} maxLength={500} onChange={(event) => setText(event.target.value)} rows={3} placeholder="질문을 입력하세요 (개인정보·URL 제외)" className="mt-3 w-full rounded-xl border border-border bg-card p-3 text-sm"/><div className="mt-2 grid gap-2 sm:grid-cols-2"><input value={year} onChange={(event) => setYear(event.target.value.replace(/\D/g, "").slice(0, 4))} inputMode="numeric" placeholder="연도(선택)" className="h-11 rounded-xl border border-border bg-card px-3 text-sm"/><input value={period} onChange={(event) => setPeriod(event.target.value.slice(0, 80))} placeholder="시기·회차(선택)" className="h-11 rounded-xl border border-border bg-card px-3 text-sm"/><select aria-label="질문 언어" value={locale} onChange={(event) => setLocale(event.target.value as typeof locale)} className="h-11 rounded-xl border border-border bg-card px-3 text-sm"><option value="ko">한국어</option><option value="en">English</option><option value="ja">日本語</option></select>{kind === "INTERVIEW" ? <select aria-label="면접 단계" value={stage} onChange={(event) => setStage(event.target.value as QuestionInterviewStage)} className="h-11 rounded-xl border border-border bg-card px-3 text-sm">{Object.entries(interviewStageLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select> : <div className="flex h-11 items-center rounded-xl border border-border bg-card px-3 text-sm text-muted-foreground">서류 단계</div>}</div><label className="mt-3 flex min-h-11 items-center gap-2 text-xs text-navy"><input type="checkbox" checked={attested} onChange={(event) => setAttested(event.target.checked)} className="h-4 w-4"/>제가 실제 지원·면접 과정에서 경험한 질문입니다.</label><button onClick={save} disabled={!text.trim() || !attested} className="mt-2 min-h-11 w-full rounded-xl bg-navy px-5 text-sm font-bold text-ivory disabled:opacity-40">내 기기에 제보 저장</button>{notice ? <p role="status" className="mt-2 text-xs text-muted-foreground">{notice}</p> : null}</div>;
}

function CabinCrewOfficialInfo({ profile }: { profile: AirlineWorkspaceProfile }) {
  const requirements = profile.cabinCrewRequirements ?? [];
  const process = profile.recruitmentProcess ?? [];
  const guidance = profile.recruitmentGuidance ?? [];
  if (!requirements.length && !process.length && !guidance.length) return null;
  return <section className={`${panel} mt-4`}><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-bold text-navy">Cabin Crew 공식 채용 정보</h2><p className="mt-1 text-xs text-muted-foreground">공식 페이지에서 직접 확인된 내용만 표시합니다. 없는 조건은 충족 면제가 아니라 확인되지 않은 정보입니다.</p></div>{profile.cabinCrewCareersUrl ? <a href={profile.cabinCrewCareersUrl} target="_blank" rel="noreferrer" className="text-sm font-bold text-navy">Cabin Crew 지원 페이지 <ExternalLink className="inline h-3 w-3"/></a> : null}</div><div className="mt-4 grid gap-4 lg:grid-cols-2"><div><h3 className="text-sm font-bold text-navy">지원요건 · {requirements.length}개</h3><div className="mt-2 space-y-2">{requirements.length ? requirements.map((item) => <article key={item.id} className="rounded-xl bg-secondary/60 p-3"><p className="text-sm text-midnight">{item.text}</p><p className="mt-1 text-[11px] text-muted-foreground">{item.requirementType} · {recruitmentRecordLabel(item) || freshnessFor(item.verifiedAt)}</p></article>) : empty("공식 페이지에서 직접 확인된 지원요건 정보가 아직 없습니다.")}</div></div><div><h3 className="text-sm font-bold text-navy">채용 절차</h3>{process.length ? <ol className="mt-2 space-y-2">{process.map((item) => <li key={item.id} className="rounded-xl bg-secondary/60 p-3"><strong className="text-sm text-navy">{item.order}. {item.title}</strong><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{item.description}</p>{recruitmentRecordLabel(item) ? <p className="mt-1 text-[11px] text-muted-foreground">{recruitmentRecordLabel(item)}</p> : null}</li>)}</ol> : <div className="mt-2">{empty("공식 페이지에서 확인된 상세 채용 절차가 없습니다.")}</div>}<h3 className="mt-4 text-sm font-bold text-navy">공식 안내</h3><div className="mt-2 space-y-2">{guidance.map((item) => <div key={item.id} className="rounded-xl bg-secondary/60 p-3"><p className="text-xs leading-relaxed text-muted-foreground">{item.text}</p>{recruitmentRecordLabel(item) ? <p className="mt-1 text-[11px] text-muted-foreground">{recruitmentRecordLabel(item)}</p> : null}</div>)}</div></div></div></section>;
}

function WorkspaceDetail({ profile, answers, attempts, experiences, onBack, onOpenApplication, onOpenExperience, onStartPractice }: { profile: AirlineWorkspaceProfile; answers: ApplicationAnswer[]; attempts: InterviewAttempt[]; experiences: CareerExperience[]; onBack: () => void; onOpenApplication: (airlineId: string) => void; onOpenExperience: () => void; onStartPractice: (airlineId: string, mode: "interview" | "mock" | "self_intro", question?: WorkspaceQuestion) => void }) {
  const [tab, setTab] = useState<Tab>("overview"); const [revision, setRevision] = useState(0); const [questionKind, setQuestionKind] = useState<WorkspaceQuestion["kind"] | "ALL">("ALL"); const [questionYear, setQuestionYear] = useState<string>(""); const [questionCategory, setQuestionCategory] = useState<string>("ALL"); const [questionPosition, setQuestionPosition] = useState<string>(""); const [questionSource, setQuestionSource] = useState<QuestionSourceFilter>("ALL"); const [questionSearch, setQuestionSearch] = useState(""); const [routeScope, setRouteScope] = useState<"ALL" | "DOMESTIC" | "INTERNATIONAL">("ALL"); const [routeOrigin, setRouteOrigin] = useState(""); const [routeDestination, setRouteDestination] = useState("");
  const liveStore = useMemo(() => airlineTargetingRepository.load(), [revision]);
  const sourceBackedQuestions = useMemo(() => getSourceBackedWorkspaceQuestions(profile.id), [profile.id]);
  const airlineQuestions = [...sourceBackedQuestions, ...liveStore.questions.filter((item) => item.airlineId === profile.id)].filter((item, index, all) => all.findIndex((candidate) => candidate.id === item.id) === index);
  const evidencePool = buildEvidenceQuestionPool(airlineQuestions);
  const sourceFilteredQuestions = evidencePool.map((item) => item.question).filter((question) => {
    const provenance = questionProvenance(question);
    if (questionSource === "OFFICIAL") return provenance === "OFFICIAL_CURRENT" || provenance === "OFFICIAL_ARCHIVE";
    return questionSource === "ALL" || provenance === questionSource;
  });
  const visibleQuestions = filterQuestions(sourceFilteredQuestions, { kind: questionKind, year: questionYear ? Number(questionYear) : undefined, category: questionCategory as Parameters<typeof filterQuestions>[1]["category"], position: questionPosition || undefined, search: questionSearch });
  const patterns = calculateQuestionPatterns(airlineQuestions);
  const userPatterns = calculateCommunityPatterns(airlineQuestions, "USER_REPORTED");
  const secondaryPatterns = calculateCommunityPatterns(airlineQuestions, "VERIFIED_SECONDARY");
  const status = buildPreparationStatus({ airlineId: profile.id, questions: airlineQuestions, answers, attempts, experiences });
  const airlineRoutes = mergeAirlineRoutes(liveStore.routes).filter((item) => item.airlineId === profile.id);
  const visibleRoutes = airlineRoutes.filter((route) => (routeScope === "ALL" || route.routeScope === routeScope) && (!routeOrigin || route.originCountry === routeOrigin) && (!routeDestination || route.destinationCountry === routeDestination));
  const airlineFleet = mergeAirlineFleet(liveStore.fleet).filter((item) => item.airlineId === profile.id);
  return <main className="mx-auto w-full max-w-7xl px-5 pb-10 pt-5 md:px-8">
    <button onClick={onBack} className="flex min-h-11 items-center gap-2 text-sm font-bold text-navy"><ArrowLeft className="h-4 w-4"/>항공사 목록</button>
    <header className="mt-3 rounded-3xl bg-navy p-6 text-ivory"><span className="text-xs font-bold text-gold">AIRLINE TARGET</span><h1 className="mt-2 text-2xl font-bold">{profile.nameKo}</h1><p className="mt-1 text-sm text-ivory/70">{profile.nameEn} · {profile.countryNameKo} · {carrierLabels[profile.carrierType]}</p><div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-white/10 px-3 py-1">{profile.verified && profile.published ? "검증·게시 프로필" : "정보 검토 중"}</span><span className="rounded-full bg-white/10 px-3 py-1">AI 문맥 {isAirlineEligibleForAi(profile) ? "사용 가능" : "비활성"}</span></div></header>
    <div className="mt-4 flex gap-2 overflow-x-auto pb-2" role="tablist">{tabs.map(([id, label]) => <button key={id} role="tab" aria-selected={tab === id} onClick={() => setTab(id)} className={`min-h-11 shrink-0 rounded-full px-4 text-xs font-bold ${tab === id ? "bg-gold text-navy" : "border border-border bg-card text-muted-foreground"}`}>{label}</button>)}</div>
    <section className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className={panel}><span className="text-xs text-muted-foreground">지원서 질문</span><strong className="mt-1 block text-xl text-navy">{status.answeredApplicationCount}/{status.applicationQuestionCount}</strong><span className="text-[11px] text-muted-foreground">저장 답변 / 저장 질문</span></div><div className={panel}><span className="text-xs text-muted-foreground">면접 연습</span><strong className="mt-1 block text-xl text-navy">{status.practicedInterviewCount}회</strong></div><div className={panel}><span className="text-xs text-muted-foreground">면접 질문</span><strong className="mt-1 block text-xl text-navy">{status.interviewQuestionCount}개</strong></div><div className={panel}><span className="text-xs text-muted-foreground">연결 경험</span><strong className="mt-1 block text-xl text-navy">{status.linkedExperienceCount}개</strong></div><div className={panel}><span className="text-xs text-muted-foreground">확인 출처</span><strong className="mt-1 block text-xl text-navy">{profile.sources.length}개</strong></div></section>
    {tab === "overview" || tab === "application" ? <CabinCrewOfficialInfo profile={profile}/> : null}
    {tab === "overview" ? <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className={panel}><h2 className="font-bold text-navy">회사 정보</h2><dl className="mt-4 grid grid-cols-[120px_1fr] gap-y-3 text-sm"><dt className="text-muted-foreground">국가</dt><dd>{profile.countryNameKo}</dd><dt className="text-muted-foreground">운항 성격</dt><dd>{profile.operationScope ? scopeLabels[profile.operationScope] : "확인된 노선 자료 없음"}</dd><dt className="text-muted-foreground">본사</dt><dd>{profile.headquarters ?? "검증 정보 없음"}</dd><dt className="text-muted-foreground">주요 허브</dt><dd>{profile.hubs.length ? profile.hubs.join(" · ") : "검증 정보 없음"}</dd></dl>{profile.summary ? <p className="mt-4 text-sm leading-relaxed text-muted-foreground">{profile.summary}</p> : null}<div className="mt-4 flex flex-wrap gap-2">{profile.website ? <a href={profile.website} target="_blank" rel="noreferrer" className="text-sm font-bold text-navy">공식 홈페이지 <ExternalLink className="inline h-3 w-3"/></a> : null}{profile.careersUrl ? <a href={profile.careersUrl} target="_blank" rel="noreferrer" className="text-sm font-bold text-navy">채용 페이지 <ExternalLink className="inline h-3 w-3"/></a> : null}</div></section><section className={panel}><h2 className="font-bold text-navy">출처와 최신성</h2>{profile.sources.length ? <div className="mt-3 space-y-3">{profile.sources.map((source) => <article key={`${source.type}:${source.sourceUrl}`} className="rounded-xl bg-secondary/60 p-3"><strong className="text-sm text-navy">{source.sourceTitle}</strong><p className="mt-1 text-xs text-muted-foreground">{source.status} · {freshnessFor(source.verifiedAt)} · {new Date(source.verifiedAt).toLocaleDateString("ko-KR")}</p><a href={source.sourceUrl} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs font-bold text-navy">출처 보기 →</a></article>)}</div> : <div className="mt-3">{empty("게시·검증된 회사 정보 출처가 없습니다.")}</div>}</section></div> : null}
    {tab === "application" ? <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className={panel}><div className="flex items-center justify-between"><h2 className="font-bold text-navy">지원서 질문</h2><button onClick={() => onOpenApplication(profile.id)} className="text-sm font-bold text-navy">Application Coach →</button></div><div className="mt-4 space-y-3">{airlineQuestions.filter((item) => item.kind === "APPLICATION").map((question) => <QuestionCard key={question.id} question={question} onPractice={() => onOpenApplication(profile.id)} onMock={() => onStartPractice(profile.id, "mock", question)} onSelfIntroduction={() => onStartPractice(profile.id, "self_intro", question)}/>)}</div>{!airlineQuestions.some((item) => item.kind === "APPLICATION") ? empty("확인된 공식 지원서 질문이 없습니다.") : null}<div className="mt-4"><QuestionComposer airlineId={profile.id} kind="APPLICATION" onSaved={() => setRevision((value) => value + 1)}/></div></section><section className={panel}><h2 className="font-bold text-navy">내 답변</h2>{answers.length ? <div className="mt-3 space-y-3">{answers.map((answer) => <article key={answer.id} className="rounded-xl bg-secondary/60 p-3"><strong className="text-sm text-navy">{answer.title}</strong><p className="mt-1 text-xs text-muted-foreground">{answer.status} · 버전 {answer.versionIds.length}개 · 경험 {answer.selectedExperienceIds.length}개</p><p className="mt-1 text-[11px] text-muted-foreground">최근 수정 {new Date(answer.updatedAt).toLocaleDateString("ko-KR")}</p></article>)}</div> : empty("이 항공사에 저장된 답변이 없습니다.")}<button onClick={() => onOpenApplication(profile.id)} className="mt-4 min-h-11 w-full rounded-xl bg-navy text-sm font-bold text-ivory">답변 작성·수정</button></section></div> : null}
    {tab === "questions" ? <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_340px]">
      <section className={panel}>
        <div className="flex gap-2">{(["ALL", "APPLICATION", "INTERVIEW"] as const).map((kind) => <button key={kind} onClick={() => setQuestionKind(kind)} className={`min-h-10 rounded-full px-4 text-xs font-bold ${questionKind === kind ? "bg-navy text-ivory" : "bg-secondary text-navy"}`}>{kind === "ALL" ? "전체" : kind === "APPLICATION" ? "지원서" : "면접"}</button>)}</div>
        <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">
          <input aria-label="질문 검색" value={questionSearch} onChange={(event) => setQuestionSearch(event.target.value)} placeholder="질문 검색" className="h-10 rounded-xl border border-border bg-card px-3 text-xs"/>
          <select aria-label="연도 필터" value={questionYear} onChange={(event) => setQuestionYear(event.target.value)} className="h-10 rounded-xl border border-border bg-card px-3 text-xs"><option value="">전체 연도</option>{[...new Set(airlineQuestions.map((item) => item.year).filter(Boolean))].sort().reverse().map((year) => <option key={year} value={year}>{year}</option>)}</select>
          <select aria-label="질문 분류 필터" value={questionCategory} onChange={(event) => setQuestionCategory(event.target.value)} className="h-10 rounded-xl border border-border bg-card px-3 text-xs"><option value="ALL">전체 분류</option>{Object.entries(patternLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>
          <select aria-label="직무 필터" value={questionPosition} onChange={(event) => setQuestionPosition(event.target.value)} className="h-10 rounded-xl border border-border bg-card px-3 text-xs"><option value="">전체 직무</option>{[...new Set(airlineQuestions.map((item) => item.position))].sort().map((position) => <option key={position} value={position}>{position}</option>)}</select>
          <select aria-label="출처 필터" value={questionSource} onChange={(event) => setQuestionSource(event.target.value as QuestionSourceFilter)} className="h-10 rounded-xl border border-border bg-card px-3 text-xs"><option value="ALL">전체 출처</option><option value="OFFICIAL">공식 질문</option><option value="USER_REPORTED">사용자 제보</option><option value="VERIFIED_SECONDARY">검증된 2차 출처</option><option value="UNVERIFIED_COMMUNITY">미검증 커뮤니티</option></select>
        </div>
        <p className="mt-3 text-xs text-muted-foreground">공식 현재·과거 자료와 사용자 제보를 분리합니다. 사용자 입력과 2차 자료는 공식 질문 패턴에 포함하지 않습니다.</p>
        <div className="mt-4 space-y-3">{visibleQuestions.map((question) => <QuestionCard key={question.id} question={question} supportCount={evidencePool.find((item) => item.question.id === question.id)?.supportCount ?? 0} onPractice={() => question.kind === "APPLICATION" ? onOpenApplication(profile.id) : onStartPractice(profile.id, "interview", question)} onMock={() => onStartPractice(profile.id, "mock", question)} onSelfIntroduction={() => onStartPractice(profile.id, "self_intro", question)}/>)}</div>
        {!visibleQuestions.length ? empty(questionSource === "OFFICIAL" || questionSource === "ALL" ? sourceBackedQuestions.length ? "조건에 맞는 저장 질문이 없습니다." : airlineQuestions.some((item) => questionProvenance(item) === "USER_REPORTED") ? "확인된 공식 질문은 없지만 내 기기에 저장된 사용자 제보가 있습니다." : "확인된 공식 질문이 없습니다. 사용자 제보는 별도로 저장할 수 있습니다." : "선택한 출처 유형에 저장된 질문이 없습니다.") : null}
        <div className="mt-4"><QuestionComposer airlineId={profile.id} onSaved={() => setRevision((value) => value + 1)}/></div>
      </section>
      <aside className="space-y-4"><PatternPanel title="공식 질문 패턴" description="공식 현재·과거 자료만 집계합니다." patterns={patterns}/><PatternPanel title="사용자 제보 패턴" description="수락된 제보만 집계하며 서로 다른 제보자 수를 함께 봅니다." patterns={userPatterns}/><PatternPanel title="검증 2차 출처 패턴" description="출처 메타데이터가 검증된 자료만 공식 패턴과 분리해 집계합니다." patterns={secondaryPatterns}/></aside>
    </div> : null}
    {tab === "routes" ? <section className={`${panel} mt-4`}><h2 className="font-bold text-navy">확인된 노선</h2><p className="mt-2 text-xs text-muted-foreground">노선은 변동 정보이며 검증일과 출처가 있는 자료만 표시합니다.</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><select aria-label="노선 범위 필터" value={routeScope} onChange={(event) => setRouteScope(event.target.value as typeof routeScope)} className="h-10 rounded-xl border border-border bg-card px-3 text-xs"><option value="ALL">전체 노선</option><option value="DOMESTIC">국내선</option><option value="INTERNATIONAL">국제선</option></select><select aria-label="출발 국가 필터" value={routeOrigin} onChange={(event) => setRouteOrigin(event.target.value)} className="h-10 rounded-xl border border-border bg-card px-3 text-xs"><option value="">전체 출발국가</option>{[...new Set(airlineRoutes.map((route) => route.originCountry))].sort().map((country) => <option key={country} value={country}>{country}</option>)}</select><select aria-label="도착 국가 필터" value={routeDestination} onChange={(event) => setRouteDestination(event.target.value)} className="h-10 rounded-xl border border-border bg-card px-3 text-xs"><option value="">전체 도착국가</option>{[...new Set(airlineRoutes.map((route) => route.destinationCountry))].sort().map((country) => <option key={country} value={country}>{country}</option>)}</select></div>{visibleRoutes.length ? <div className="mt-4 space-y-2">{visibleRoutes.map((route) => <article key={route.id} className="rounded-xl bg-secondary/60 p-3 text-sm"><strong>{route.originAirport} → {route.destinationAirport}</strong><p className="mt-1 text-xs text-muted-foreground">{route.routeScope === "DOMESTIC" ? "국내선" : "국제선"} · {freshnessFor(route.lastVerifiedAt)} · {new Date(route.lastVerifiedAt).toLocaleDateString("ko-KR")}</p><a href={route.source.sourceUrl} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs font-bold text-navy">출처 보기 →</a></article>)}</div> : <div className="mt-4">{empty(airlineRoutes.length ? "조건에 맞는 확인 노선이 없습니다." : "확인된 노선 정보가 없습니다.")}</div>}</section> : null}
    {tab === "fleet" ? <section className={`${panel} mt-4`}><h2 className="font-bold text-navy">확인된 기단</h2><p className="mt-2 text-xs text-muted-foreground">공식 최신 출처가 없는 수량은 추정하지 않습니다.</p>{airlineFleet.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{airlineFleet.map((entry) => <article key={entry.id} className="rounded-xl bg-secondary/60 p-3"><strong className="text-sm text-navy">{entry.manufacturer} {entry.aircraftModel}</strong><p className="mt-1 text-xs text-muted-foreground">{entry.bodyType ?? "형태 미확인"} · 수량 {entry.quantity ?? "미확인"} · {freshnessFor(entry.lastVerifiedAt)}</p><a href={entry.source.sourceUrl} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs font-bold text-navy">출처 보기 →</a></article>)}</div> : <div className="mt-4">{empty("확인된 기단 정보가 없습니다.")}</div>}</section> : null}
    {tab === "experience" ? <section className={`${panel} mt-4`}><div className="flex items-center justify-between"><h2 className="font-bold text-navy">연결된 내 경험</h2><button onClick={onOpenExperience} className="text-sm font-bold text-navy">경험 저장소 →</button></div>{experiences.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{experiences.map((experience) => <article key={experience.id} className="rounded-xl bg-secondary/60 p-3"><strong className="text-sm text-navy">{experience.title}</strong><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{experience.shortSummary || experience.situation}</p></article>)}</div> : <div className="mt-4">{empty("저장된 경험이 없습니다. 경험 저장소에서 직접 작성해 주세요.")}</div>}</section> : null}
    {tab === "practice" ? <section className={`${panel} mt-4`}><h2 className="font-bold text-navy">이 항공사 준비 액션</h2><p className="mt-2 text-sm text-muted-foreground">연습 결과만 준비 활동으로 집계됩니다. 화면 진입만으로 완료 처리하지 않습니다.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Action icon={<Building2/>} label="지원서 답변" onClick={() => onOpenApplication(profile.id)}/><Action icon={<Plane/>} label="단일 면접" onClick={() => onStartPractice(profile.id, "interview")}/><Action icon={<Star/>} label="자기소개" onClick={() => onStartPractice(profile.id, "self_intro")}/><Action icon={<Plane/>} label="모의면접" onClick={() => onStartPractice(profile.id, "mock")}/></div></section> : null}
  </main>;
}

function PatternPanel({ title, description, patterns }: { title: string; description: string; patterns: { category: string; count: number; confidence: string; uniqueReporterCount?: number; yearsObserved?: number[]; repeatedTheme?: boolean }[] }) {
  return <section className={panel}><h2 className="font-bold text-navy">{title}</h2><p className="mt-2 text-xs text-muted-foreground">{description}</p>{patterns.length ? <div className="mt-4 space-y-2">{patterns.map((pattern) => <div key={pattern.category} className="rounded-xl bg-secondary/60 p-3"><div className="flex justify-between text-sm"><strong className="text-navy">{patternLabels[pattern.category] ?? pattern.category}</strong><span>{pattern.count}</span></div><p className="mt-1 text-[11px] text-muted-foreground">{pattern.confidence}{typeof pattern.uniqueReporterCount === "number" ? ` · 제보자 ${pattern.uniqueReporterCount}명` : ""}{pattern.yearsObserved?.length ? ` · ${pattern.yearsObserved.join("·")}` : ""}{pattern.repeatedTheme ? " · 여러 시기 반복" : ""}</p></div>)}</div> : <div className="mt-3">{empty("집계할 근거가 없습니다.")}</div>}</section>;
}

function QuestionCard({ question, supportCount = 0, onPractice, onMock, onSelfIntroduction }: { question: WorkspaceQuestion; supportCount?: number; onPractice: () => void; onMock: () => void; onSelfIntroduction: () => void }) {
  const provenance = questionProvenance(question);
  const practiceAllowed = canPracticeCommunityQuestion(question);
  return <article className="rounded-xl border border-border p-3">
    <div className="flex flex-wrap items-center gap-2 text-[11px]"><span className="rounded-full bg-secondary px-2 py-1">{question.kind === "APPLICATION" ? "지원서" : "면접"}</span><span className="rounded-full bg-secondary px-2 py-1">{questionProvenanceLabels[provenance]}</span>{question.moderationStatus ? <span className="rounded-full bg-gold/15 px-2 py-1 text-navy">{moderationStatusLabels[question.moderationStatus]}</span> : null}{question.year ? <span>{question.year}</span> : null}{question.archived ? <span>과거 자료</span> : null}</div>
    <p className="mt-2 text-sm font-semibold leading-relaxed text-navy">{question.questionText}</p>
    <p className="mt-2 text-xs text-muted-foreground">{patternLabels[question.category]} · {question.position} · {(question.locale ?? "ko").toUpperCase()} · {question.verified ? "검증됨" : "미검증"}</p>
    {question.recruitmentPeriod ? <p className="mt-1 text-[11px] text-muted-foreground">채용 시기: {question.recruitmentPeriod}</p> : null}
    {question.interviewStage ? <p className="mt-1 text-[11px] text-muted-foreground">단계: {interviewStageLabels[question.interviewStage]}</p> : null}
    {question.reporterOwned && question.moderationStatus === "PENDING" ? <p className="mt-1 text-[11px] text-muted-foreground">이 기기에만 저장 · 공개 공유 안 됨</p> : null}
    {supportCount ? <p className="mt-1 text-[11px] text-muted-foreground">같은 질문을 뒷받침하는 별도 기록 {supportCount}건</p> : null}
    {question.sourceUrl ? <a href={question.sourceUrl} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs font-bold text-navy">근거 출처 보기 <ExternalLink className="inline h-3 w-3"/></a> : null}
    {practiceAllowed ? <div className="mt-3 grid gap-2 sm:grid-cols-3"><button onClick={onPractice} className="min-h-11 rounded-xl border border-navy text-sm font-bold text-navy">{question.kind === "APPLICATION" ? "답변 작성" : "단일 면접"}</button><button onClick={onMock} className="min-h-11 rounded-xl border border-border text-sm font-bold text-navy">모의면접</button><button onClick={onSelfIntroduction} className="min-h-11 rounded-xl border border-border text-sm font-bold text-navy">자기소개</button></div> : <p className="mt-3 rounded-xl bg-secondary/60 p-3 text-xs text-muted-foreground">검토 수락 전에는 연습에 사용되지 않습니다.</p>}
  </article>;
}
function Action({ icon, label, onClick }: { icon: ReactNode; label: string; onClick: () => void }) { return <button onClick={onClick} className="flex min-h-24 flex-col items-center justify-center gap-2 rounded-2xl border border-border text-sm font-bold text-navy">{icon}{label}</button>; }

export function AirlineTargetingWorkspace({ preferences, onPreferencesChange, onExit, onOpenApplication, onOpenExperience, onStartPractice }: { preferences: AirlineTargetPreferences; onPreferencesChange: (preferences: AirlineTargetPreferences) => void; onExit: () => void; onOpenApplication: (airlineId: string) => void; onOpenExperience: () => void; onStartPractice: (airlineId: string, mode: "interview" | "mock" | "self_intro", question?: WorkspaceQuestion) => void }) {
  const [selected, setSelected] = useState<AirlineWorkspaceProfile | null>(null); const [revision, setRevision] = useState(0); const [compareIds, setCompareIds] = useState<string[]>([]);
  const store = useMemo(() => airlineTargetingRepository.load(), [revision]);
  const mergedRoutes = useMemo(() => mergeAirlineRoutes(store.routes), [store.routes]);
  const mergedFleet = useMemo(() => mergeAirlineFleet(store.fleet), [store.fleet]);
  const profiles = useMemo(() => buildAirlineWorkspaceProfiles(mergedRoutes), [mergedRoutes]);
  const answers = selected ? listAnswersByAirline(selected.id) : [];
  const attempts = loadInterviewAttempts(); const experiences = experienceRepository.load().experiences;
  if (selected) return <WorkspaceDetail profile={selected} answers={answers} attempts={attempts} experiences={experiences} onBack={() => { setSelected(null); setRevision((value) => value + 1); }} onOpenApplication={onOpenApplication} onOpenExperience={onOpenExperience} onStartPractice={onStartPractice}/>;
  const comparison = compareAirlines(profiles, compareIds, { questions: store.questions, answers: listApplicationAnswers(), attempts, experiences });
  return <main className="mx-auto w-full max-w-7xl px-5 pb-10 pt-5 md:px-8"><button onClick={onExit} className="flex min-h-11 items-center gap-2 text-sm font-bold text-navy"><ArrowLeft className="h-4 w-4"/>홈</button><header className="mt-3"><span className="eyebrow text-gold">AIRLINE TARGETING</span><h1 className="mt-2 text-2xl font-bold text-navy">타겟 항공사 워크스페이스</h1><p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">검증된 회사 정보와 내가 저장한 질문·답변·경험·연습 기록을 항공사별로 연결합니다. 출처가 없는 노선·기단·기출은 만들지 않습니다.</p></header><section className="mt-5"><AirlineList profiles={profiles} preferences={preferences} onSelect={setSelected} onPreferencesChange={(current, profile, mode) => onPreferencesChange(normalizeTargetPreferences(current.primary, current.interests, { id: profile.id, name: profile.nameEn }, mode))}/></section><section className={`${panel} mt-6`}><h2 className="font-bold text-navy">간단 비교 · 최대 3개</h2><p className="mt-1 text-xs text-muted-foreground">우열이나 합격 가능성을 계산하지 않습니다. 공식 자료에 없는 조건은 “없음”이 아니라 확인되지 않은 정보입니다.</p><div className="mt-3 flex flex-wrap gap-2">{profiles.slice(0, 24).map((profile) => <button key={profile.id} disabled={!compareIds.includes(profile.id) && compareIds.length >= 3} onClick={() => setCompareIds((ids) => ids.includes(profile.id) ? ids.filter((id) => id !== profile.id) : [...ids, profile.id].slice(0, 3))} className={`min-h-10 rounded-full px-3 text-xs font-bold ${compareIds.includes(profile.id) ? "bg-navy text-ivory" : "border border-border text-navy disabled:opacity-30"}`}>{profile.nameKo}</button>)}</div>{comparison.length ? <div className="mt-4 grid gap-3 md:grid-cols-3">{comparison.map(({ profile, preparation }) => { const families = [...new Set(mergedFleet.filter((item) => item.airlineId === profile.id).map((item) => item.aircraftFamily))]; return <article key={profile.id} className="rounded-2xl bg-secondary/60 p-4"><strong className="text-sm text-navy">{profile.nameKo}</strong><p className="mt-2 text-xs text-muted-foreground">{profile.countryNameKo} · {carrierLabels[profile.carrierType]}</p><p className="mt-1 text-xs text-muted-foreground">운항: {profile.operationScope ? scopeLabels[profile.operationScope] : "미확인"}</p><p className="mt-1 text-xs text-muted-foreground">허브: {profile.hubs.join(" · ") || "검증 정보 없음"}</p><p className="mt-1 text-xs text-muted-foreground">기단: {families.join(" · ") || "공식 자료에서 확인되지 않음"}</p><p className="mt-1 text-xs text-muted-foreground">공식 지원요건: {profile.cabinCrewRequirements?.length ?? 0}개</p><p className="mt-2 text-xs text-midnight">저장 질문 {preparation.applicationQuestionCount + preparation.interviewQuestionCount} · 실제 연습 {preparation.practicedInterviewCount}</p></article> })}</div> : null}</section></main>;
}
