export type InterviewAudioMetrics={version:1;durationMs:number;voicedDurationMs:number;silenceDurationMs:number;volume:{averageDbfs:number|null;peakDbfs:number|null;minDbfs:number|null;dynamicRangeDb:number|null;stability:number|null;clipping:boolean};pauses:{count:number;longCount:number;longestMs:number;averageMs:number};speech:{voicedRatio:number;wordsPerMinute:number|null};quality:{microphoneSignalDetected:boolean;clippingDetected:boolean;tooQuietDetected:boolean;insufficientAudio:boolean}}

export const audioAnalysisConfig={silenceDbfs:-45,minPauseMs:350,longPauseMs:1500,clippingAmplitude:0.98,minDurationMs:1000,minSignalAmplitude:0.002,tooQuietDbfs:-42} as const
export type AudioFrame={atMs:number;rms:number;peak:number}
const finite=(value:number)=>Number.isFinite(value)&&value>=0?value:0
export function amplitudeToDbfs(value:number){const safe=finite(value);return safe===0?null:20*Math.log10(Math.min(1,safe))}
export function calculateRms(samples:ArrayLike<number>){if(!samples.length)return 0;let sum=0;for(let i=0;i<samples.length;i++){const value=Number(samples[i]);if(Number.isFinite(value))sum+=value*value}return Math.sqrt(sum/samples.length)}
export function calculatePeak(samples:ArrayLike<number>){let peak=0;for(let i=0;i<samples.length;i++)peak=Math.max(peak,Math.abs(Number(samples[i])||0));return peak}
export function estimateWordsPerMinute(transcript:string|undefined,durationMs:number){if(!transcript?.trim()||durationMs<=0)return null;const words=transcript.trim().split(/\s+/).filter(Boolean).length;return words?Math.round(words/(durationMs/60000)):null}
export function groupPauses(frames:AudioFrame[],config=audioAnalysisConfig){const ordered=frames.filter(f=>Number.isFinite(f.atMs)).sort((a,b)=>a.atMs-b.atMs);const pauses:number[]=[];let started:number|null=null;for(const frame of ordered){const silent=(amplitudeToDbfs(frame.rms)??-Infinity)<config.silenceDbfs;if(silent&&started===null)started=frame.atMs;if(!silent&&started!==null){const duration=Math.max(0,frame.atMs-started);if(duration>=config.minPauseMs)pauses.push(duration);started=null}}return pauses}
export function analyzeInterviewAudio(frames:AudioFrame[],durationMs:number,transcript?:string):InterviewAudioMetrics{const safeDuration=Math.max(0,Number.isFinite(durationMs)?durationMs:0);const usable=frames.filter(f=>Number.isFinite(f.atMs)&&Number.isFinite(f.rms)&&Number.isFinite(f.peak));const dbs=usable.map(f=>amplitudeToDbfs(f.rms)).filter((v):v is number=>v!==null);const voiced=usable.filter(f=>(amplitudeToDbfs(f.rms)??-Infinity)>=audioAnalysisConfig.silenceDbfs);const pauses=groupPauses(usable);const average=dbs.length?dbs.reduce((a,b)=>a+b,0)/dbs.length:null;const peak=usable.length?amplitudeToDbfs(Math.max(...usable.map(f=>f.peak))):null;const min=dbs.length?Math.min(...dbs):null;const variance=dbs.length&&average!==null?dbs.reduce((sum,value)=>sum+(value-average)**2,0)/dbs.length:0;const voiceMs=usable.length>1?Math.round(safeDuration*(voiced.length/usable.length)):0;const silenceMs=Math.max(0,safeDuration-voiceMs);const clipping=usable.some(f=>f.peak>=audioAnalysisConfig.clippingAmplitude);const signal=usable.some(f=>f.peak>=audioAnalysisConfig.minSignalAmplitude);const insufficient=safeDuration<audioAnalysisConfig.minDurationMs||usable.length<2||voiceMs===0;return{version:1,durationMs:safeDuration,voicedDurationMs:voiceMs,silenceDurationMs:silenceMs,volume:{averageDbfs:average,peakDbfs:peak,minDbfs:min,dynamicRangeDb:peak!==null&&min!==null?peak-min:null,stability:dbs.length?Math.max(0,Math.min(100,100-Math.sqrt(variance)*5)):null,clipping},pauses:{count:pauses.length,longCount:pauses.filter(p=>p>=audioAnalysisConfig.longPauseMs).length,longestMs:pauses.length?Math.max(...pauses):0,averageMs:pauses.length?Math.round(pauses.reduce((a,b)=>a+b,0)/pauses.length):0},speech:{voicedRatio:safeDuration?Math.round(voiceMs/safeDuration*100):0,wordsPerMinute:estimateWordsPerMinute(transcript,safeDuration)},quality:{microphoneSignalDetected:signal,clippingDetected:clipping,tooQuietDetected:!signal||(average!==null&&average<audioAnalysisConfig.tooQuietDbfs),insufficientAudio:insufficient}}}

export function compareInterviewAudioMetrics(previous:InterviewAudioMetrics|undefined,current:InterviewAudioMetrics|undefined){if(!previous||!current)return null;return{longPauseDelta:current.pauses.longCount-previous.pauses.longCount,voicedRatioDelta:current.speech.voicedRatio-previous.speech.voicedRatio,volumeStabilityDelta:(current.volume.stability??0)-(previous.volume.stability??0),wpmDelta:current.speech.wordsPerMinute!==null&&previous.speech.wordsPerMinute!==null?current.speech.wordsPerMinute-previous.speech.wordsPerMinute:null}}

export function createInterviewAudioMonitor(stream:MediaStream){let context:AudioContext|undefined;let analyser:AnalyserNode|undefined;let timer:number|undefined;const frames:AudioFrame[]=[];const startedAt=performance.now();try{context=new AudioContext();const source=context.createMediaStreamSource(stream);analyser=context.createAnalyser();analyser.fftSize=2048;source.connect(analyser);const samples=new Float32Array(analyser.fftSize);const sample=()=>{if(!analyser)return;analyser.getFloatTimeDomainData(samples);frames.push({atMs:performance.now()-startedAt,rms:calculateRms(samples),peak:calculatePeak(samples)})};sample();timer=window.setInterval(sample,100)}catch{/* Recording remains available when Web Audio is unavailable. */}return{finish(transcript?:string){if(timer!==undefined)window.clearInterval(timer);try{analyser?.disconnect();void context?.close()}catch{/* Non-critical cleanup. */}return analyzeInterviewAudio(frames,performance.now()-startedAt,transcript)}}}
