import assert from 'node:assert/strict'
import test from 'node:test'
import { amplitudeToDbfs, analyzeInterviewAudio, calculateRms, estimateWordsPerMinute, groupPauses } from './audio-analysis'
import { buildInterviewSpeechMetrics, compareInterviewSpeechMetrics, detectFillers } from './speech-analysis'
import { pronunciationProviderRegistry } from '@/lib/ai/pronunciation-provider'
import { analyzeInterviewContent, detectInterviewStructure } from '@/lib/interview-content-analysis'
import type { InterviewAttempt, InterviewQuestion } from '@/lib/interview-practice-data'
import { analyzeInterviewSession, followUpForAttempt, selectSessionQuestions } from '@/lib/mock-interview-session'
import { decideAiInterviewerFollowUp, followUpTemplateRegistry, phraseFollowUp } from '@/lib/ai-interviewer'

test('audio math handles RMS, dBFS, silence, clipping, and invalid input',()=>{assert.equal(calculateRms([1,-1]),1);assert.equal(amplitudeToDbfs(1),0);assert.equal(amplitudeToDbfs(0),null);const metrics=analyzeInterviewAudio([{atMs:0,rms:0.2,peak:1},{atMs:100,rms:0,peak:0},{atMs:500,rms:0,peak:0},{atMs:1800,rms:0.2,peak:0.2}],2000,'one two');assert.equal(metrics.quality.clippingDetected,true);assert.equal(metrics.pauses.count,1);assert.equal(metrics.pauses.longCount,1);assert.equal(metrics.speech.wordsPerMinute,60);assert.equal(metrics.speech.voicedRatio,50);assert.equal(analyzeInterviewAudio([],0).quality.insufficientAudio,true)})
test('pause grouping and WPM safely exclude absent transcripts',()=>{assert.deepEqual(groupPauses([{atMs:0,rms:0.1,peak:.1},{atMs:100,rms:0,peak:0},{atMs:460,rms:0,peak:0},{atMs:500,rms:0.1,peak:.1}]),[400]);assert.equal(estimateWordsPerMinute('',60000),null);assert.equal(estimateWordsPerMinute('한 문장',0),null)})
test('speech analysis distinguishes fillers, transcript fallback, confidence and comparisons',()=>{assert.equal(detectFillers('um actually like this','en').totalCount,3);assert.equal(detectFillers('음 약간 이렇게','ko').totalCount,2);const audio=analyzeInterviewAudio([{atMs:0,rms:.2,peak:.2},{atMs:1000,rms:.2,peak:.2}],1000,'');const current=buildInterviewSpeechMetrics({transcript:'um I can explain this clearly',transcription:{transcript:'um I can explain this clearly',detectedLanguage:'en',confidence:.65,segments:[{text:'um I can',startSeconds:0,endSeconds:1,confidence:.5}],transcriptionMode:'actual_audio',isActualTranscription:true},audioMetrics:audio,providerId:'server'});assert.equal(current.clarity.lowConfidenceSegmentCount,1);assert.equal(current.pronunciation.status,'proxy_only');assert.equal(buildInterviewSpeechMetrics({audioMetrics:audio}).transcriptAvailable,false);assert.equal(compareInterviewSpeechMetrics({...current,fillers:{...current.fillers,totalCount:3}},current)?.fillerCount.after,current.fillers.totalCount)})
test('trailing silence is finalized only after the pause threshold',()=>{assert.deepEqual(groupPauses([{atMs:0,rms:.1,peak:.1},{atMs:100,rms:0,peak:0},{atMs:500,rms:0,peak:0}]),[400]);assert.deepEqual(groupPauses([{atMs:0,rms:.1,peak:.1},{atMs:100,rms:0,peak:0},{atMs:300,rms:0,peak:0}]),[])})
test('phase three provider and content foundations have safe no-provider fallbacks',async()=>{const provider=pronunciationProviderRegistry.active();assert.equal(provider.capabilities.wordAlignment,false);assert.equal((await provider.analyze({transcript:'hello',language:'en'})).status,'not_configured');const question:InterviewQuestion={id:'q',category:'behavioral_experience',targetCapabilities:['interview_communication'],prompt:'Tell me',shortTitle:'q',difficulty:'beginner',evaluationRubric:{keys:[],guidance:''},localeKey:'q'};assert.equal(detectInterviewStructure(question,'When I handled a situation, my role was clear and I solved it.').detected,'star');assert.equal(analyzeInterviewContent(question,'').structure.detected,'unstructured')})
test('mock session selection, follow-up and aggregation stay deterministic',()=>{assert.equal(selectSessionQuestions({mode:'general',count:5}).length,5);const attempt={id:'a',contentAnalysis:{structure:{missingParts:['Result']},answerQuality:{genericClaims:[]},competencies:[]},speechMetrics:{fillers:{totalCount:2}},audioMetrics:{pauses:{longCount:1}}} as unknown as InterviewAttempt;assert.ok(followUpForAttempt(attempt));const report=analyzeInterviewSession({id:'s',mode:'general',questionIds:[],attemptIds:['a'],currentQuestionIndex:0,status:'completed',startedAt:''},[attempt]);assert.equal(report.speechSummary,'필러 2회 · 긴 쉼 1회')})
test('AI interviewer chooses verified templates and prevents duplicate or unlimited follow-ups',async()=>{const question:InterviewQuestion={id:'q',category:'behavioral_experience',targetCapabilities:['interview_communication'],prompt:'Tell me about a time',shortTitle:'q',difficulty:'beginner',evaluationRubric:{keys:[],guidance:''},localeKey:'q'};const attempt={id:'base',questionId:'q',category:'behavioral_experience',transcript:'I worked hard.',durationSeconds:30,createdAt:'',attemptNumber:1,completed:true,analysis:{} as never,contentAnalysis:{version:1,structure:{missingParts:['Action','Result'],parts:[],detected:'unstructured'},answerQuality:{genericClaims:['I worked hard.'],evidenceStatements:[]},competencies:[],answerSummary:{oneLineSummary:'',keyPoints:[]},relevance:{status:'direct',missingPoints:[]},strongPoints:[],improvementPoints:[],sentenceCoaching:[],improvedAnswerPlan:{targetDurationSeconds:30,opening:'',keyPointOrder:[],closing:''},followUpPractice:[],suggestions:[]}} as InterviewAttempt;const session={id:'s',mode:'ai_interviewer' as const,questionIds:['q','q2','q3','q4','q5'],attemptIds:[],currentQuestionIndex:0,status:'in_progress' as const,startedAt:''};const first=decideAiInterviewerFollowUp({question,attempt,session,priorFollowUps:[]});assert.equal(first.shouldAsk,true);assert.equal(first.reason,'missing_action');assert.equal(first.templateId,'star-action');const duplicate=decideAiInterviewerFollowUp({question,attempt,session,priorFollowUps:[{...attempt,id:'f',isFollowUp:true,followUpTemplateId:'star-action',followUpReason:'missing_action'}]});assert.notEqual(duplicate.templateId,'star-action');const capped=decideAiInterviewerFollowUp({question,attempt,session,priorFollowUps:Array.from({length:3},(_,i)=>({...attempt,id:`f${i}`,isFollowUp:true}))});assert.equal(capped.shouldAsk,false);assert.equal(await phraseFollowUp(followUpTemplateRegistry[0],{language:'ko',paraphrase:async()=>{throw new Error('offline')}}),followUpTemplateRegistry[0].textKo)})
