import type { TranscriptionResult } from '@/lib/ai/types'
import type { InterviewAudioMetrics } from './audio-analysis'

export type SpeechProviderCapabilities={wordTimestamps:boolean;segmentTimestamps:boolean;confidence:boolean;language:boolean}
export const speechProviderCapabilities:Record<'mock'|'browser_speech'|'server',SpeechProviderCapabilities>={mock:{wordTimestamps:false,segmentTimestamps:false,confidence:false,language:false},browser_speech:{wordTimestamps:false,segmentTimestamps:false,confidence:false,language:true},server:{wordTimestamps:false,segmentTimestamps:true,confidence:true,language:true}}
export type InterviewSpeechMetrics={version:1;transcriptAvailable:boolean;language:string|null;speechRate:{speechUnitCount:number;estimatedWpm:number|null;voicedWpm:number|null;label:string|null};fillers:{totalCount:number;ratePerMinute:number|null;items:Array<{text:string;count:number;category:'high_confidence'|'contextual'}>};clarity:{overallScore:number|null;lowConfidenceSegmentCount:number;unclearSegments:Array<{text:string;startMs?:number;endMs?:number;confidence?:number}>};pronunciation:{status:'not_available'|'proxy_only'|'provider_supported';proxyScore:number|null;caution:'STT 기반 추정치이며 실제 음소 단위 발음 정확도가 아님'}}
const highEnglish=['um','uh','erm','hmm'],contextualEnglish=['like','you know','actually','basically'],highKorean=['음','어','저','뭐랄까'],contextualKorean=['약간','그러니까']
const normalize=(text:string)=>text.toLowerCase().replace(/[.,!?;:()[\]{}]/g,' ')
export function detectFillers(transcript:string,language?:string|null){const source=normalize(transcript);const english=/^en/i.test(language??'')||/[a-z]/i.test(source);const sets:Array<[string[],'high_confidence'|'contextual']>=english?[[highEnglish,'high_confidence'],[contextualEnglish,'contextual']]:[[highKorean,'high_confidence'],[contextualKorean,'contextual']];const items:InterviewSpeechMetrics['fillers']['items']=[];for(const [terms,category] of sets)for(const term of terms){const escaped=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const matches=source.match(new RegExp(`(^|\\s)${escaped}(?=\\s|$)`,'g'))??[];if(matches.length)items.push({text:term,count:matches.length,category})}return{items,totalCount:items.reduce((sum,item)=>sum+item.count,0)}}
const countUnits=(text:string)=>text.trim().split(/\s+/).filter(Boolean).length
const rateLabel=(wpm:number|null,language:string|null)=>{if(wpm===null)return null;const korean=/^ko/i.test(language??'');const low=korean?90:100,high=korean?180:180;return wpm<low?'느린 편':wpm>high?'빠른 편':'안정적'}
export function buildInterviewSpeechMetrics(input:{transcript?:string;transcription?:TranscriptionResult;audioMetrics?:InterviewAudioMetrics;providerId?:'mock'|'browser_speech'|'server'}):InterviewSpeechMetrics{const transcript=input.transcription?.transcript??input.transcript??'';const language=input.transcription?.detectedLanguage??null;const duration=input.audioMetrics?.durationMs??0;const units=countUnits(transcript);const estimated=transcript.trim()&&duration>0?Math.round(units/(duration/60000)):null;const voiced=input.audioMetrics?.voicedDurationMs??0;const voicedWpm=transcript.trim()&&voiced>0?Math.round(units/(voiced/60000)):null;const fillers=detectFillers(transcript,language);const rate=duration?Math.round(fillers.totalCount/(duration/60000)*10)/10:null;const segments=input.transcription?.segments??[];const low=segments.filter(s=>typeof s.confidence==='number'&&s.confidence<0.7).map(s=>({text:s.text,startMs:Math.round(s.startSeconds*1000),endMs:Math.round(s.endSeconds*1000),confidence:s.confidence}));const hasConfidence=typeof input.transcription?.confidence==='number'||segments.some(s=>typeof s.confidence==='number');let clarity:number|null=null;if(transcript.trim()&&input.audioMetrics){clarity=100;clarity-=Math.min(25,fillers.totalCount*3);clarity-=Math.min(20,input.audioMetrics.pauses.longCount*4);clarity-=input.audioMetrics.quality.clippingDetected?12:0;clarity-=input.audioMetrics.quality.tooQuietDetected?12:0;clarity-=estimated!==null&&(estimated<80||estimated>210)?10:0;clarity-=Math.min(25,low.length*8);clarity=Math.max(0,clarity)}const confidence=input.transcription?.confidence;return{version:1,transcriptAvailable:Boolean(transcript.trim()),language,speechRate:{speechUnitCount:units,estimatedWpm:estimated,voicedWpm,label:rateLabel(estimated,language)},fillers:{...fillers,ratePerMinute:rate},clarity:{overallScore:clarity,lowConfidenceSegmentCount:low.length,unclearSegments:low},pronunciation:{status:hasConfidence?'proxy_only':'not_available',proxyScore:hasConfidence&&typeof confidence==='number'?Math.round(confidence*100):null,caution:'STT 기반 추정치이며 실제 음소 단위 발음 정확도가 아님'}}}
export function compareInterviewSpeechMetrics(previous:InterviewSpeechMetrics|undefined,current:InterviewSpeechMetrics|undefined){if(!previous||!current)return null;return{fillerCount:{before:previous.fillers.totalCount,after:current.fillers.totalCount},fillerRate:{before:previous.fillers.ratePerMinute,after:current.fillers.ratePerMinute},speechRate:{before:previous.speechRate.estimatedWpm,after:current.speechRate.estimatedWpm},clarity:{before:previous.clarity.overallScore,after:current.clarity.overallScore}}}
