'use client'
import {useEffect,useRef,useState} from 'react'
import type {User} from '@supabase/supabase-js'
import {Cloud,Download,LogIn,RefreshCw,Upload} from 'lucide-react'
import {authService} from '@/lib/supabase/auth-service'
import {getSupabaseRuntimeConfig} from '@/lib/supabase/config'
import {syncStatusLabels,type SyncStatus} from '@/lib/supabase/connection-status'
import {downloadLocalData,summarizeLocalData} from '@/lib/supabase/local-data-exporter'
import {previewLocalDataImport,applyLocalDataImport} from '@/lib/supabase/local-data-importer'
import {syncService} from '@/lib/supabase/sync-service'
import {ExperienceSyncPanel} from './experience-sync-panel'
import {SupabaseDiagnostic} from './supabase-diagnostic'
import {flushExperienceQueue} from '@/lib/supabase/experience-sync-repository'
import {connectAllLocalTrainingRecords,flushTrainingQueue,localTrainingMergeSummary,trainingSyncMeta} from '@/lib/supabase/training-attempt-repositories'
import {connectAllLocalLearning,flushLearningQueue,learningMergeDecision,learningSyncMeta,loadLocalLearningProfile} from '@/lib/supabase/learning-sync-repository'
import {flushApplicationQueue} from '@/lib/supabase/application-sync-repository'
import {syncQueueRepository} from '@/lib/supabase/sync-queue-repository'
import {runTrainingSyncDiagnostics,type SyncDiagnostic} from '@/lib/supabase/sync-diagnostics'
import {getProfileCompletionStatus,type UserProfile} from '@/lib/supabase/profile-completion-service'
import ko from '@/lib/locales/ko.json'
import {ProfileAvatarManager} from '@/components/profile/profile-avatar-manager'

export function AccountSummary({onLogin}:{onLogin:()=>void}){
 const[user,setUser]=useState<User|null>(null),[status,setStatus]=useState<SyncStatus>('local_only'),[notice,setNotice]=useState(''),input=useRef<HTMLInputElement>(null),configured=getSupabaseRuntimeConfig().configured,summary=summarizeLocalData()
 useEffect(()=>{void authService.currentUser().then(u=>{setUser(u);setStatus(u?'synced':'local_only')});return authService.onAuthStateChange(u=>{setUser(u);setStatus(u?'synced':'local_only')})},[])
 async function sync(){if(!user)return;setStatus('syncing');const [result,experiences]=await Promise.all([syncService.flush(user.id),flushExperienceQueue(user),flushTrainingQueue(user),flushLearningQueue(user),flushApplicationQueue(user)]);setStatus(result.offline?'offline':result.failed||experiences.failed?'error':'synced')}
 async function importFile(file?:File){if(!file)return;try{const parsed=JSON.parse(await file.text()),preview=previewLocalDataImport(parsed);if(!preview.valid){setNotice(preview.error);return}if(confirm(`${preview.keys.length}개 데이터 묶음을 이 기기 기록과 병합할까요?`)){applyLocalDataImport(preview.payload);setNotice('기록을 병합했습니다. 화면을 새로 고치면 반영됩니다.')}}catch{setNotice('파일을 읽지 못했어요.')}}
 return <div className="space-y-4"><section className="rounded-3xl border border-border bg-card p-6"><div className="flex items-start justify-between"><div><span className="eyebrow text-muted-foreground">ACCOUNT & SYNC</span><h2 className="mt-2 text-xl font-bold text-navy">{user?'계정에 연결됨':'로컬 저장 모드'}</h2><p className="mt-2 text-sm text-muted-foreground">{user?.email??'이 기기에만 저장 중'}</p></div><Cloud className="h-6 w-6 text-gold"/></div><div className="mt-5 rounded-2xl bg-secondary/70 p-4 text-sm text-navy">{syncStatusLabels[status]}</div>{user?<div className="mt-4 grid grid-cols-2 gap-3"><button onClick={()=>void sync()} className="h-11 rounded-xl bg-navy text-sm font-bold text-ivory"><RefreshCw className="mr-2 inline h-4 w-4"/>지금 동기화</button><button onClick={async()=>{await authService.signOut();setUser(null);setStatus('local_only')}} className="h-11 rounded-xl border border-border text-sm font-bold text-navy">로그아웃</button></div>:<><p className="mt-4 text-sm leading-6 text-muted-foreground">로그인하면 다른 기기에서도 기록을 이어서 사용할 수 있어요.</p><button onClick={onLogin} className="mt-4 h-12 w-full rounded-2xl bg-navy font-bold text-ivory"><LogIn className="mr-2 inline h-4 w-4"/>로그인 또는 회원가입</button>{!configured&&<p className="mt-3 text-xs text-muted-foreground">Supabase 미설정 · 로컬 기능은 정상 사용 가능</p>}</>}</section>{user&&<ProfileAccountCard/>}{user&&<TrainingSyncPanel/>}{user&&<LearningSyncPanel user={user}/>} {user&&<ExperienceSyncPanel user={user}/>}<SupabaseDiagnostic/><section className="rounded-3xl border border-border bg-card p-6"><h2 className="text-lg font-bold text-navy">데이터 관리</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">경험 {summary.experiences}개 · 면접 {summary.interviews}개 · 자기소개 {summary.selfIntroductions}개 · 지원 답변 {summary.applicationAnswers}개</p><div className="mt-5 space-y-3"><button onClick={downloadLocalData} className="h-11 w-full rounded-xl border border-border text-sm font-bold text-navy"><Download className="mr-2 inline h-4 w-4"/>로컬 데이터 내보내기</button><input ref={input} type="file" accept="application/json" hidden onChange={e=>void importFile(e.target.files?.[0])}/><button onClick={()=>input.current?.click()} className="h-11 w-full rounded-xl border border-border text-sm font-bold text-navy"><Upload className="mr-2 inline h-4 w-4"/>로컬 데이터 가져오기</button></div>{notice&&<p className="mt-3 text-xs text-muted-foreground">{notice}</p>}</section><section className="rounded-3xl border border-coral/20 bg-card p-6"><h2 className="font-bold text-navy">계정 데이터 삭제</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">클라우드 계정 삭제는 서버 권한 설정 후 사용할 수 있어요. 로컬 기록은 자동으로 삭제되지 않습니다.</p></section></div>
}

function TrainingSyncPanel(){
 const[summary,setSummary]=useState<{interviews:unknown[];selfIntroductions:unknown[];audio:number}>({interviews:[],selfIntroductions:[],audio:0}),[notice,setNotice]=useState(''),[diagnostics,setDiagnostics]=useState<SyncDiagnostic[]>(),[diagnosing,setDiagnosing]=useState(false)
 const refresh=()=>void localTrainingMergeSummary().then(setSummary)
 useEffect(()=>{refresh();window.addEventListener('cabin:training-sync-changed',refresh);return()=>window.removeEventListener('cabin:training-sync-changed',refresh)},[])
 const records=[...summary.interviews,...summary.selfIntroductions] as {id:string}[],states=records.map(x=>trainingSyncMeta.get(x.id)),pending=states.filter(x=>x.status==='pending'||x.audioStatus==='pending'||x.audioStatus==='uploading_audio').length,failed=states.filter(x=>x.status==='failed'||x.audioStatus==='failed').length,synced=states.filter(x=>x.status==='synced').length,diagnosticsEnabled=process.env.NEXT_PUBLIC_ENABLE_SYNC_DIAGNOSTICS==='true'
 async function diagnose(){setDiagnosing(true);try{setDiagnostics((await runTrainingSyncDiagnostics()).items)}finally{setDiagnosing(false)}}
 return <section className="rounded-3xl border border-border bg-card p-6"><span className="eyebrow text-muted-foreground">TRAINING SYNC</span><h2 className="mt-2 text-lg font-bold text-navy">연습 기록 동기화</h2><p className="mt-2 text-sm text-muted-foreground">면접 {summary.interviews.length}개 · 자기소개 {summary.selfIntroductions.length}개 · 녹음 {summary.audio}개</p><p className="mt-2 text-xs text-muted-foreground">계정 저장 완료 {synced} · 대기 {pending} · 실패 {failed} · 충돌 0</p><div className="mt-4 grid grid-cols-2 gap-3"><button onClick={()=>void connectAllLocalTrainingRecords().then(result=>{setNotice(`${result.queued}개 기록을 계정에 연결했습니다.`);refresh()})} className="h-11 rounded-xl bg-navy text-sm font-bold text-ivory">모두 계정에 연결</button><button onClick={()=>void authService.currentUser().then(user=>user&&flushTrainingQueue(user))} className="h-11 rounded-xl border border-border text-sm font-bold text-navy">지금 동기화</button></div><div className="mt-2 grid grid-cols-2 gap-3"><button onClick={()=>setNotice('서버 기록 비교는 현재 로컬 기록을 변경하지 않습니다.')} className="h-10 text-xs text-muted-foreground">서버 기록과 비교</button><button onClick={()=>setNotice('이 기기에서만 유지합니다.')} className="h-10 text-xs text-muted-foreground">이 기기에서만 유지</button></div>{diagnosticsEnabled&&<div className="mt-4 border-t border-border pt-4"><button type="button" onClick={()=>void diagnose()} disabled={diagnosing} className="h-10 w-full rounded-xl border border-border text-sm font-bold text-navy disabled:opacity-50">{diagnosing?'진단 중…':'동기화 진단 실행'}</button>{diagnostics&&<ul className="mt-3 space-y-2 text-xs" aria-live="polite">{diagnostics.map(item=><li key={item.label} className="flex justify-between gap-3"><span className="text-muted-foreground">{item.label}</span><span className={item.level==='FAIL'?'text-coral':item.level==='WARNING'?'text-gold':'text-navy'}>{item.level}{item.detail?` ${item.detail}`:''}</span></li>)}</ul>}</div>}{notice&&<p className="mt-3 text-xs text-muted-foreground">{notice}</p>}</section>
}

function LearningSyncPanel({user}:{user:User}){
 const[refreshKey,setRefreshKey]=useState(0),[notice,setNotice]=useState('')
 const local=loadLocalLearningProfile(),queue=syncQueueRepository.list().filter(item=>item.userId===user.id&&['learning_profile','weekly_learning_plan','learning_activity'].includes(item.entityType)),pending=queue.filter(item=>item.status==='pending'||item.status==='syncing').length,failed=queue.filter(item=>item.status==='failed').length,synced=[local.onboarding?learningSyncMeta.get('profile').status==='synced':false,...local.analytics.confirmedWeeklyPlans.map(plan=>learningSyncMeta.get(plan.weekStart).status==='synced'),...local.analytics.routineCompletions.map(item=>learningSyncMeta.get(item.id).status==='synced')].filter(Boolean).length,hasLocal=!!local.onboarding||local.analytics.confirmedWeeklyPlans.length>0||local.analytics.routineCompletions.length>0,decision=learningMergeDecision.get(user.id)
 useEffect(()=>{const refresh=()=>setRefreshKey(value=>value+1);window.addEventListener('cabin:learning-sync-changed',refresh);window.addEventListener('cabin:learning-local-changed',refresh);return()=>{window.removeEventListener('cabin:learning-sync-changed',refresh);window.removeEventListener('cabin:learning-local-changed',refresh)}},[])
 void refreshKey
 return <section className="rounded-3xl border border-border bg-card p-6"><span className="eyebrow text-muted-foreground">LEARNING SYNC</span><h2 className="mt-2 text-lg font-bold text-navy">학습 기록 동기화</h2><p className="mt-2 text-sm text-muted-foreground">학습 프로필 {local.onboarding?1:0}개 · 주간 계획 {local.analytics.confirmedWeeklyPlans.length}개 · 학습 활동 {local.analytics.routineCompletions.length}개</p><p className="mt-2 text-xs text-muted-foreground">저장 완료 {synced} · 대기 {pending} · 실패 {failed}</p>{hasLocal&&!decision?<div className="mt-4 space-y-2"><p className="text-sm text-navy">이 기기에 저장된 학습 기록을 계정에 연결할까요?</p><div className="grid grid-cols-2 gap-3"><button onClick={()=>void connectAllLocalLearning(user).then(()=>{setNotice('학습 기록을 계정 동기화 대기열에 추가했습니다.');setRefreshKey(value=>value+1)})} className="h-11 rounded-xl bg-navy text-sm font-bold text-ivory">모두 계정에 연결</button><button onClick={()=>{learningMergeDecision.set(user.id,'review_server');setNotice('서버 기록 비교를 선택했습니다. 로컬 기록은 변경하지 않습니다.');setRefreshKey(value=>value+1)}} className="h-11 rounded-xl border border-border text-sm font-bold text-navy">서버 기록과 비교</button></div><div className="grid grid-cols-2 gap-3"><button onClick={()=>{learningMergeDecision.set(user.id,'keep_local');setNotice('이 기기에서만 유지합니다.');setRefreshKey(value=>value+1)}} className="h-10 text-xs text-muted-foreground">이 기기에서만 유지</button><button onClick={()=>{learningMergeDecision.set(user.id,'later');setNotice('나중에 다시 선택할 수 있습니다.');setRefreshKey(value=>value+1)}} className="h-10 text-xs text-muted-foreground">나중에</button></div></div>:<button onClick={()=>void flushLearningQueue(user).then(()=>setRefreshKey(value=>value+1))} className="mt-4 h-11 w-full rounded-xl border border-border text-sm font-bold text-navy">지금 동기화</button>}{notice&&<p className="mt-3 text-xs text-muted-foreground">{notice}</p>}</section>
}

function ProfileAccountCard(){
 const[profile,setProfile]=useState<UserProfile>()
 useEffect(()=>{void getProfileCompletionStatus().then(result=>setProfile(result.profile))},[])
 if(!profile)return null
 const t=ko.profileSetup
 return <section className="rounded-3xl border border-border bg-card p-6"><div className="flex items-center justify-between"><div><span className="eyebrow text-muted-foreground">PRIVATE PROFILE</span><h2 className="mt-2 text-lg font-bold text-navy">{profile.fullName}</h2></div><button onClick={()=>window.location.assign('/profile/setup?edit=1&returnTo=/')} className="text-sm font-bold text-navy">{t.edit}</button></div><div className="mt-5"><ProfileAvatarManager name={profile.fullName} showDescription={false}/></div><dl className="mt-5 space-y-3 text-sm">{[[t.email,profile.email],[t.phone,profile.phone],[t.birthDate,profile.birthDate],[`${t.kakaoId} · ${t.optional}`,profile.kakaoId||'-']].map(([label,value])=><div key={label} className="flex justify-between gap-4"><dt className="text-muted-foreground">{label}</dt><dd className="text-right font-semibold text-navy">{value}</dd></div>)}</dl><p className="mt-3 text-xs leading-5 text-muted-foreground">{t.ageExclusion}</p><div className="mt-4 rounded-2xl bg-secondary/60 p-4 text-xs leading-5 text-navy"><p>{t.requiredConsent}: {profile.requiredTermsVersion} · {profile.privacyConsentVersion}</p><p className="mt-1">{t.optionalConsent}: {[profile.marketingConsent&&t.marketing,profile.smsNotificationConsent&&t.sms,profile.kakaoContactConsent&&t.kakaoContact].filter(Boolean).join(' · ')||'-'}</p></div></section>
}
