'use client'
import {useEffect,useState} from 'react'
import {authService} from '@/lib/supabase/auth-service'
import {applicationMergeDecision,connectAllLocalApplications,flushApplicationQueue,localApplicationSyncSummary} from '@/lib/supabase/application-sync-repository'
import {syncQueueRepository} from '@/lib/supabase/sync-queue-repository'
import {persistencePolicyCopy} from '@/lib/persistence-provenance'

export function ApplicationSyncPanel(){
 const[user,setUser]=useState<Awaited<ReturnType<typeof authService.currentUser>>>(null),[refresh,setRefresh]=useState(0),[notice,setNotice]=useState('')
 useEffect(()=>{void authService.currentUser().then(setUser);const update=()=>setRefresh(value=>value+1);window.addEventListener('cabin:application-local-changed',update);window.addEventListener('cabin:application-sync-changed',update);return()=>{window.removeEventListener('cabin:application-local-changed',update);window.removeEventListener('cabin:application-sync-changed',update)}},[])
 void refresh
 if(!user)return null
 const summary=localApplicationSyncSummary(),queue=syncQueueRepository.list().filter(item=>item.userId===user.id&&['airline_application','application_draft','application_answer','application_activity'].includes(item.entityType)),pending=queue.filter(item=>item.status==='pending'||item.status==='syncing').length,failed=queue.filter(item=>item.status==='failed').length,hasLocal=summary.applications>0||summary.drafts>0||summary.answers>0,decision=applicationMergeDecision.get(user.id)
 return <section className="rounded-3xl border border-border bg-card p-6"><span className="eyebrow text-muted-foreground">APPLICATION SYNC</span><h2 className="mt-2 text-lg font-bold text-navy">지원 기록 동기화</h2><p className="mt-2 text-sm text-muted-foreground">지원 항공사 {summary.applications}개 · 지원서 초안 {summary.drafts}개 · 문항 답변 {summary.answers}개</p><p className="mt-2 text-xs text-muted-foreground">동기화 대기 {pending} · 실패 {failed}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">지원 기록은 이 기기 데이터를 우선 사용합니다. {persistencePolicyCopy.ko.incompleteRestore}</p>{hasLocal&&!decision?<div className="mt-4 space-y-2"><p className="text-sm text-navy">이 기기의 지원 기록을 계정 동기화 대기열에 추가할까요?</p><div className="grid grid-cols-2 gap-3"><button onClick={()=>void connectAllLocalApplications(user).then(()=>{setNotice('지원 기록을 계정 동기화 대기열에 추가했습니다. 전체 복원 또는 백업 완료를 의미하지 않습니다.');setRefresh(value=>value+1)})} className="h-11 rounded-xl bg-navy text-sm font-bold text-ivory">동기화 대기열에 추가</button><button onClick={()=>{applicationMergeDecision.set(user.id,'review_server');setNotice('지원 항공사 기록만 서버와 병합될 수 있습니다. 초안·답변의 전체 복원은 지원하지 않습니다.');setRefresh(value=>value+1)}} className="h-11 rounded-xl border border-border text-sm font-bold text-navy">지원 범위 확인</button></div><div className="grid grid-cols-2 gap-3"><button onClick={()=>{applicationMergeDecision.set(user.id,'keep_local');setNotice('이 기기에서만 유지합니다.');setRefresh(value=>value+1)}} className="h-10 text-xs text-muted-foreground">이 기기에서만 유지</button><button onClick={()=>{applicationMergeDecision.set(user.id,'later');setNotice('나중에 다시 선택할 수 있습니다.');setRefresh(value=>value+1)}} className="h-10 text-xs text-muted-foreground">나중에</button></div></div>:<button onClick={()=>void flushApplicationQueue(user).then(()=>setRefresh(value=>value+1))} className="mt-4 h-11 w-full rounded-xl border border-border text-sm font-bold text-navy">지금 동기화</button>}{notice&&<p className="mt-3 text-xs text-muted-foreground">{notice}</p>}</section>
}
