import type { AirlineFAQ, AirlineKnowledgeProfile } from "./airline-knowledge-repository";
import type { AirlineResearchRecord } from "./airline-research-repository";
import type { AirlineCoachingInsight, AirlineInterviewQuestion } from "./airline-knowledge-transformer";

const corporate = "https://corporate.airfrance.com/en/cabin-crew-member";
const careers = "https://recrutement.airfrance.com/";
const papeete = "https://recrutement.airfrance.com/job/pnc-ppt-cca";
const airFrance = "https://www.airfrance.com/";
const jfkThirdParty = "https://justpostedjobs.com/jobs/cabin-crew-air-france-jfk/";
const instagram = "https://www.instagram.com/p/C3_airfrance_pnc/";
const collectedAt = "2026-07-30T00:00:00.000Z";
const fact = (category: AirlineResearchRecord["extractedFacts"][number]["category"], key: string, value: string, sourceUrl: string, sourceGrade: "A" | "C" | "D" | "E") => ({ category, key, value, sourceUrl, sourceGrade, verified: false });

export const airFranceResearchRecords: AirlineResearchRecord[] = [
  { id: "air-france-profile-official-20260730", airlineId: "air_france", sourceTitle: "Air France official cabin crew role", sourceUrl: corporate, sourceType: "Official", collectedBy: "manual", collectedAt, sourceDate: "2026-07-30", sourceGrade: "A", confidence: "high", status: "collected", rawSummary: "Official Air France cabin-crew role candidates.", rawText: "Air France; professional cabin-crew role; flight safety; customer service; customer relationships; teamwork; work under pressure.", extractedFacts: [fact("profile", "official_name", "Air France", corporate, "A"), fact("profile", "country", "France", airFrance, "A"), fact("safety", "safety_first", "Flight Safety is a continual objective and cabin crew ensure passenger safety by respecting rules.", corporate, "A"), fact("service", "customer_service", "Cabin crew provide customer service aligned with Air France quality and excellence objectives.", corporate, "A"), fact("service", "professional_role", "Cabin crew are trained professionals who work under pressure and personalise customer relationships.", corporate, "A"), fact("profile", "headquarters", "Requires confirmation from this supplied source set.", corporate, "E"), fact("profile", "hub", "Requires confirmation from this supplied source set.", corporate, "E"), fact("profile", "founded", "Requires confirmation from this supplied source set.", corporate, "E"), fact("profile", "group_relationship", "Detailed Air France-KLM relationship requires confirmation from this supplied source set.", corporate, "E"), fact("brand", "art_de_vivre", "Art de vivre, elegance, gastronomy and premium-clientele wording require official source confirmation in this pack.", corporate, "E")] },
  { id: "air-france-recruitment-official-20260730", airlineId: "air_france", sourceTitle: "Air France official recruitment portal and Papeete posting", sourceUrl: careers, sourceType: "Official", collectedBy: "manual", collectedAt, sourceDate: "2026-07-30", sourceGrade: "A", confidence: "high", status: "collected", rawSummary: "Official application and base-scoped Papeete recruitment candidates.", rawText: "Official online application; document screening; interview or video interview; English assessment; medical fitness; background check; training. Papeete posting candidates only: Baccalaureat, European CCA, English B2 and designated English test, TOEIC not accepted, Polynesian resident, visa categories, recent PNC experience, medical aptitude and criminal-record document. These are not global Air France conditions.", extractedFacts: [fact("recruitment", "online_application", "Official online application portal.", careers, "A"), fact("recruitment", "document_screening", "Document screening candidate.", careers, "A"), fact("interview", "interview_or_video", "Interview or video interview candidate.", careers, "A"), fact("language", "english_assessment", "English assessment candidate.", corporate, "A"), fact("medical", "medical_fitness", "Medical fitness candidate.", corporate, "A"), fact("recruitment", "background_check", "Background-check candidate.", careers, "A"), fact("training", "training", "Training candidate.", corporate, "A"), fact("recruitment", "papeete_baccalaureat", "Papeete-only candidate: Baccalaureat.", papeete, "A"), fact("recruitment", "papeete_european_cca", "Papeete-only candidate: European CCA.", papeete, "A"), fact("language", "papeete_english_b2", "Papeete-only candidate: English B2 and designated English test; TOEIC not accepted.", papeete, "A"), fact("work_authorization", "papeete_residency_visa", "Papeete-only candidate: Polynesian residence and visa categories.", papeete, "A"), fact("medical", "papeete_medical", "Papeete-only candidate: medical aptitude and criminal-record document.", papeete, "A"), fact("recruitment", "france_mainland_conditions", "Mainland age, education, French, English, CCA, work authorization, physical and base conditions require confirmation.", careers, "E")] },
  { id: "air-france-jfk-third-party-20260730", airlineId: "air_france", sourceTitle: "Third-party JFK cabin crew listing", sourceUrl: jfkThirdParty, sourceType: "Third Party", collectedBy: "manual", collectedAt, sourceDate: "2026-07-30", sourceGrade: "D", confidence: "low", status: "collected", rawSummary: "Third-party JFK candidates only; not official and never global.", rawText: "JFK candidates: minimum 21, US work right, English fluency, French preferred, no visible tattoos, background check and Paris training. This is a third-party source and is not official Air France information.", extractedFacts: [fact("recruitment", "jfk_age", "JFK-only third-party candidate: minimum 21.", jfkThirdParty, "D"), fact("work_authorization", "jfk_work_right", "JFK-only third-party candidate: US work right.", jfkThirdParty, "D"), fact("language", "jfk_language", "JFK-only third-party candidate: English fluent and French preferred.", jfkThirdParty, "D"), fact("recruitment", "jfk_tattoo", "JFK-only third-party candidate: no visible tattoos.", jfkThirdParty, "D"), fact("recruitment", "jfk_background_training", "JFK-only third-party candidate: background check and Paris training.", jfkThirdParty, "D")] },
  { id: "air-france-social-third-party-20260730", airlineId: "air_france", sourceTitle: "Social and academy-style source candidate", sourceUrl: instagram, sourceType: "Third Party", collectedBy: "manual", collectedAt, sourceDate: "2026-07-30", sourceGrade: "D", confidence: "low", status: "collected", rawSummary: "Social source retained as unverified third-party material only.", rawText: "Social or academy summaries are not official Air France sources and cannot create published facts.", extractedFacts: [fact("application", "social_summary", "Social and academy material requires independent official confirmation.", instagram, "D")] },
  { id: "air-france-preparation-20260730", airlineId: "air_france", sourceTitle: "Air France supplied coaching candidates", sourceUrl: corporate, sourceType: "Interview Preparation and Application Coaching", collectedBy: "manual", collectedAt, sourceDate: "2026-07-30", sourceGrade: "C", confidence: "medium", status: "collected", rawSummary: "Coaching directions only; not actual interview questions.", rawText: "Safety first, procedure compliance, tailored customer response, multicultural teamwork, language ability, composure and professionalism. Explain French service as service quality, not appearance. Do not generalize Papeete/JFK conditions or mix KLM/Transavia conditions.", extractedFacts: [fact("interview", "question_patterns", "Support questions for motivation, safety, service, teamwork and language preparation.", corporate, "C"), fact("application", "coaching_directions", "Connect safety, procedures, tailored service, multicultural teamwork and language ability to selected experience.", corporate, "C"), fact("application", "avoid_patterns", "Avoid travel/image-only motivations, inferred French/CCA/EU rules, base generalization and KLM/Transavia condition mixing.", corporate, "C")] },
];

export const airFranceKnowledgeProfileCandidate: Partial<AirlineKnowledgeProfile> = { id: "profile-air-france", airlineId: "air_france", reviewStatus: "reviewed", publishStatus: "unpublished", overview: { officialName: "Air France", displayName: "Air France", countryCode: "FR", region: "europe", businessModel: "full_service", website: careers, brandIdentity: { value: "Brand-detail candidates require review before use.", status: "needs_review", sourceIds: ["air-france-profile-official-20260730"] }, servicePhilosophy: "Customer service and professional cabin-crew role are review candidates.", customerFocus: { value: "Personalised customer relationship is a review candidate.", status: "needs_review", sourceIds: ["air-france-profile-official-20260730"] }, safetyCulture: { value: "Safety and procedure compliance are review candidates.", status: "needs_review", sourceIds: ["air-france-profile-official-20260730"] } } as AirlineKnowledgeProfile["overview"], recruitmentProfile: { recruitmentLanguages: [], applicationLanguages: [], commonRecruitmentStages: ["application", "document_screening", "online_assessment", "video_interview", "individual_interview", "medical_check", "background_check", "other"], officialCareerPageUrl: careers, currentStatus: "unknown", checkedAt: "2026-07-30", eligibilityRequirements: { value: ["Eligibility is base- and posting-specific; do not generalize Papeete or JFK candidates."], status: "needs_review", sourceIds: ["air-france-recruitment-official-20260730"] }, languageRequirements: { value: ["French and English conditions require confirmation for the applicable Air France posting."], status: "needs_review", sourceIds: ["air-france-recruitment-official-20260730"] }, selectionSteps: { status: "needs_review", sourceIds: ["air-france-recruitment-official-20260730"] }, physicalRequirements: { status: "needs_review", sourceIds: ["air-france-recruitment-official-20260730"] }, status: "draft" } };

const faq = (id: string, question: string, answer: string, grade: "A" | "E" = "A"): AirlineFAQ => ({ id, airlineId: "air_france", category: "eligibility", question: `지원 준비 참고 FAQ: ${question}`, answer, sourceGrade: grade, sourceReference: careers, status: "draft", publishStatus: "unpublished", createdAt: collectedAt, updatedAt: collectedAt });
export const airFranceFaqDrafts = [faq("af-faq-apply", "Where do I apply?", "Use the official Air France recruitment portal and the applicable current posting."), faq("af-faq-french", "Is French required?", "확인 필요: do not infer a universal French-language requirement from the supplied Pack.", "E"), faq("af-faq-english", "Is English required?", "확인 필요: English assessment is a candidate, while base-specific language conditions must be checked in the applicable posting.", "E"), faq("af-faq-work-right", "Is EU or French work authorization required?", "확인 필요: do not generalize work-authorization conditions from a specific base or third-party listing.", "E"), faq("af-faq-cca", "Is CCA required?", "확인 필요: European CCA appears only as a Papeete-specific candidate in this Pack."), faq("af-faq-process", "What are the recruitment stages?", "Official application, screening, interview/video, English assessment, medical, background check and training are candidates; confirm the current posting.")];

const q = (id: string, prompt: string, questionType: AirlineInterviewQuestion["questionType"], competencyTags: string[], recommendedExperienceTags: string[]): AirlineInterviewQuestion => ({ id, airlineId: "air_france", prompt: `지원 준비용 예상 질문: ${prompt}`, questionType, competencyTags, recommendedExperienceTags, followUpQuestions: [], sourceReferences: [corporate], status: "draft", publishStatus: "unpublished", sourceBasis: "coaching_draft" });
export const airFranceInterviewQuestionDrafts = [q("af-q-why", "Why Air France?", "motivation", ["brand_understanding", "professionalism", "customer_commitment"], ["airline_research", "customer_service"]), q("af-q-balance", "How do you balance safety and service?", "safety", ["safety_first", "procedure_compliance", "judgment"], ["rule_following", "risk_reporting"]), q("af-q-team", "Tell us about working in a multicultural team.", "experience", ["teamwork", "cultural_openness", "communication"], ["multicultural_team", "international_project"]), q("af-q-complaint", "Tell us about responding to an unhappy customer.", "service", ["empathy", "de_escalation", "professionalism"], ["complaint_handling", "service_recovery"]), q("af-q-language", "How would you assist a customer in French and English?", "language", ["language_communication", "clarity", "adaptability"], ["bilingual_service", "customer_support"]), q("af-q-composure", "How do you stay calm and professional under pressure?", "experience", ["composure", "resilience", "reliability"], ["high_pressure_work", "frontline_service"]), q("af-q-tailored", "How do you tailor service to different customer needs?", "service", ["customer_focus", "attentiveness", "service_quality"], ["personalised_service", "customer_service"]), q("af-q-procedure", "Tell us about a time you followed an important procedure.", "safety", ["discipline", "procedure_compliance", "accountability"], ["rule_following", "safety_awareness"])];
export const airFranceCoachingInsightDrafts: AirlineCoachingInsight[] = [{ id: "af-insight-motivation", airlineId: "air_france", topic: "motivation", coachMessage: "Air France 지원 방향은 안전 우선, 절차 준수, 고객별 맞춤 대응, 다문화 팀워크, 언어 역량, 차분함과 전문성을 선택한 경험과 연결하도록 안내합니다. 프랑스식 서비스는 외모가 아니라 서비스 품질로 설명합니다.", goodDirections: ["안전 우선", "절차 준수", "고객별 맞춤 대응", "다문화 팀워크", "언어 역량", "차분함과 전문성", "프랑스식 서비스를 서비스 품질로 설명"], avoidPatterns: ["여행·패션·이미지만 강조", "프랑스어 필수 수준 단정", "CCA 전체 공통 필수 단정", "EU 취업허가 단정", "Papeete/JFK 조건 일반화", "KLM 조건 혼입"], recommendedExperienceTags: ["safety_awareness", "customer_service", "multicultural_experience", "recruitment_language", "teamwork"], sourceReferences: [corporate], status: "draft", publishStatus: "unpublished" }];
