import assert from "node:assert/strict";
import test from "node:test";
import { airlineJourneyViewRepository, buildAirlineJourneyState, buildApplicationJourneyLineage } from "./airline-target-journey";
import type { WorkspaceQuestion } from "./airline-targeting-workspace";

const applicationQuestion = (id = "aq", airlineId = "korean_air", extra: Record<string, unknown> = {}) => ({ id, airlineId, kind: "APPLICATION", questionText: "지원 동기", position: "객실승무원", category: "MOTIVATION", sourceType: "OFFICIAL_POSTING", verified: true, createdAt: "2026-01-01T00:00:00.000Z", ...extra }) as WorkspaceQuestion;
const interviewQuestion = (id = "iq", airlineId = "korean_air", extra: Record<string, unknown> = {}) => ({ id, airlineId, kind: "INTERVIEW", questionText: "안전 경험", position: "객실승무원", category: "SAFETY", sourceType: "OFFICIAL_INTERVIEW", verified: true, createdAt: "2026-01-01T00:00:00.000Z", ...extra }) as WorkspaceQuestion;
const answer = (airlineId = "korean_air", extra: Record<string, unknown> = {}) => ({ id: "answer", airlineId, promptId: "aq", title: "지원 동기", status: "draft", selectedExperienceIds: [], experienceSnapshots: [], currentVersionId: "v1", versionIds: ["v1"], createdAt: "2026-01-02T00:00:00.000Z", updatedAt: "2026-01-02T00:00:00.000Z", ...extra }) as never;
const attempt = (airlineId = "korean_air", extra: Record<string, unknown> = {}) => ({ id: "attempt", questionId: "im2", category: "introduction_and_motivation", createdAt: "2026-01-03T00:00:00.000Z", transcript: "", durationSeconds: 30, analysis: {}, targetAirlineId: airlineId, attemptNumber: 1, completed: true, ...extra }) as never;
const selfIntro = (airlineId = "korean_air", extra: Record<string, unknown> = {}) => ({ id: "self", createdAt: "2026-01-04T00:00:00.000Z", transcript: "", durationSeconds: 60, analysis: {}, targetAirlineId: airlineId, attemptNumber: 1, completed: true, ...extra }) as never;
const session = (airlineId = "korean_air", extra: Record<string, unknown> = {}) => ({ id: "session", airlineId, mode: "airline_specific", questionIds: ["im2"], attemptIds: ["attempt"], currentQuestionIndex: 0, status: "completed", startedAt: "2026-01-05T00:00:00.000Z", completedAt: "2026-01-05T00:01:00.000Z", ...extra }) as never;
const base = (extra: Record<string, unknown> = {}) => buildAirlineJourneyState({ airlineId: "korean_air", questions: [applicationQuestion(), interviewQuestion()], ...extra });
const status = (id: string, state = base()) => state.steps.find((item) => item.id === id)?.status;

test("no primary airline is represented by no caller-selected state", () => assert.equal(base().airlineId, "korean_air"));
test("primary airline identity is preserved", () => assert.equal(buildAirlineJourneyState({ airlineId: "jin_air" }).airlineId, "jin_air"));
test("empty journey has no activity", () => assert.equal(base().recentActivity.length, 0));
test("company view completes company step", () => assert.equal(status("company", base({ companyViewedAt: "2026-01-01T00:00:00.000Z" })), "completed"));
test("CTA alone does not complete application", () => assert.equal(status("application"), "not_started"));
test("answer save completes application", () => assert.equal(status("application", base({ answers: [answer()] })), "completed"));
test("work draft stays in progress", () => assert.equal(status("application", base({ workDrafts: [{ id: "d", airlineId: "korean_air", selectedExperienceIds: [], updatedAt: "2026-01-01" } as never] })), "in_progress"));
test("experience link is derived from answer", () => assert.equal(base({ answers: [answer("korean_air", { selectedExperienceIds: ["e1"] })] }).experiencesLinked, 1));
test("duplicate experience links are deduped", () => assert.equal(base({ answers: [answer("korean_air", { selectedExperienceIds: ["e1", "e1"] })] }).experiencesLinked, 1));
test("completed interview counts", () => assert.equal(base({ attempts: [attempt()] }).interviewAttemptCount, 1));
test("incomplete interview does not complete", () => assert.equal(status("interview", base({ attempts: [attempt("korean_air", { completed: false })] })), "in_progress"));
test("mock completion counts", () => assert.equal(base({ sessions: [session()] }).mockAttempts, 1));
test("in-progress mock creates resume", () => assert.equal(base({ sessions: [session("korean_air", { status: "in_progress" })] }).resumeActions[0]?.kind, "resume_mock"));
test("self introduction completion counts", () => assert.equal(base({ selfIntroductions: [selfIntro()] }).selfIntroAttempts, 1));
test("incomplete self introduction does not count", () => assert.equal(base({ selfIntroductions: [selfIntro("korean_air", { completed: false })] }).selfIntroAttempts, 0));
test("next action starts with application", () => assert.equal(base().nextRecommendedAction.kind, "application"));
test("next action becomes interview after answer", () => assert.equal(base({ answers: [answer()] }).nextRecommendedAction.kind, "interview"));
test("next action becomes self intro after interview", () => assert.equal(base({ answers: [answer()], attempts: [attempt()] }).nextRecommendedAction.kind, "self_intro"));
test("next action becomes mock after self intro", () => assert.equal(base({ answers: [answer()], attempts: [attempt()], selfIntroductions: [selfIntro()] }).nextRecommendedAction.kind, "mock"));
test("open queue becomes retake after completed path", () => assert.equal(base({ answers: [answer()], attempts: [attempt()], selfIntroductions: [selfIntro()], sessions: [session()], queue: [{ id: "q", questionId: "im2", reason: "manual", status: "open", priority: 5, createdAt: "", updatedAt: "", airlineId: "korean_air" }] }).nextRecommendedAction.kind, "retake"));
test("application lineage keeps airline and question", () => { const value = buildApplicationJourneyLineage(applicationQuestion()); assert.equal(value.airlineId, "korean_air"); assert.equal(value.questionId, "aq"); assert.equal(value.sourceType, "OFFICIAL_POSTING"); assert.equal(value.origin, "airline_workspace"); });
test("application lineage keeps recruitment period", () => assert.equal(buildApplicationJourneyLineage(applicationQuestion("aq", "korean_air", { recruitmentPeriod: "2026 상반기" })).recruitmentPeriod, "2026 상반기"));
test("archive context remains distinct", () => assert.equal(buildApplicationJourneyLineage(applicationQuestion("archive", "korean_air", { sourceType: "VERIFIED_ARCHIVE", archived: true })).sourceType, "VERIFIED_ARCHIVE"));
test("user-reported source remains distinct", () => assert.equal(buildApplicationJourneyLineage(interviewQuestion("user", "korean_air", { sourceType: "USER_REPORTED" })).sourceType, "USER_REPORTED"));
test("multi-airline answers are isolated", () => assert.equal(base({ answers: [answer("jin_air")] }).answersDrafted, 0));
test("multi-airline attempts are isolated", () => assert.equal(base({ attempts: [attempt("jin_air")] }).interviewAttemptCount, 0));
test("question source lineage uses workspace id", () => assert.equal(base({ attempts: [attempt("korean_air", { sourceContext: { source: "airline_workspace", workspaceQuestionId: "official-1" } })] }).interviewQuestionsPracticed, 1));
test("retake lineage preserves one practiced question", () => assert.equal(base({ attempts: [attempt(), attempt("korean_air", { id: "retake", previousAttemptId: "attempt" })] }).interviewQuestionsPracticed, 1));
test("recent activity is capped at five", () => assert.equal(base({ attempts: Array.from({ length: 7 }, (_, index) => attempt("korean_air", { id: `a${index}`, createdAt: `2026-01-0${index + 1}T00:00:00.000Z` })) }).recentActivity.length, 5));
test("recent activity sorts newest first", () => assert.equal(base({ attempts: [attempt(), attempt("korean_air", { id: "new", createdAt: "2026-02-01T00:00:00.000Z" })] }).recentActivity[0].id, "interview:new"));
test("single resume is airline isolated", () => assert.equal(base({ singleResume: { questionId: "im2", practiceLanguage: "ko", targetAirlineId: "jin_air", source: "airline_workspace", startedAt: "2026-01-01" } }).resumeActions.length, 0));
test("single resume appears for matching airline", () => assert.equal(base({ singleResume: { questionId: "im2", practiceLanguage: "ko", targetAirlineId: "korean_air", source: "airline_workspace", startedAt: "2026-01-01" } }).resumeActions[0]?.kind, "resume_interview"));
test("favorite count is airline isolated", () => assert.equal(base({ favorites: [{ questionId: "im2", airlineId: "korean_air", createdAt: "" }, { questionId: "im3", airlineId: "jin_air", createdAt: "" }] }).favoriteCount, 1));
test("queue count only includes open matching items", () => assert.equal(base({ queue: [{ id: "1", questionId: "im2", reason: "manual", status: "open", priority: 5, createdAt: "", updatedAt: "", airlineId: "korean_air" }, { id: "2", questionId: "im3", reason: "manual", status: "practiced", priority: 5, createdAt: "", updatedAt: "", airlineId: "korean_air" }] }).queueCount, 1));
test("deadline label is not invented", () => assert.equal(base().deadlineLabel, undefined));
test("provided deadline label is preserved", () => assert.equal(base({ deadlineLabel: "D-4" }).deadlineLabel, "D-4"));
test("recruitment periods stay explicit", () => assert.deepEqual(buildAirlineJourneyState({ airlineId: "korean_air", questions: [applicationQuestion("a", "korean_air", { recruitmentPeriod: "2026 상반기" }), applicationQuestion("b", "korean_air", { recruitmentPeriod: "2026 상반기" })] }).recruitmentPeriods, ["2026 상반기"]));
test("missing requirements are unavailable", () => assert.equal(status("requirements"), "unavailable"));
test("available requirements are not complete before view", () => assert.equal(status("requirements", base({ requirementsAvailable: true })), "not_started"));
test("available requirements complete after view", () => assert.equal(status("requirements", base({ requirementsAvailable: true, companyViewedAt: "2026-01-01" })), "completed"));
test("fresh user has honest zero counts", () => assert.deepEqual(buildAirlineJourneyState({ airlineId: "korean_air" }).recentActivity, []));
test("journey model contains no readiness score", () => assert.doesNotMatch(JSON.stringify(base()), /readiness|hireProbability|passProbability|overallScore/i));
test("canonical AI gate is absent from journey mutations", () => assert.doesNotMatch(JSON.stringify(base()), /aiContextEnabled|published|verified/));
test("view persistence succeeds only after safe write", () => { const storage = new Map<string, string>(); Object.assign(globalThis, { localStorage: { getItem: (key: string) => storage.get(key) ?? null, setItem: (key: string, value: string) => void storage.set(key, value) } }); const result = airlineJourneyViewRepository.markViewed("korean_air", new Date("2026-01-01T00:00:00.000Z")); assert.equal(result.ok, true); assert.equal(airlineJourneyViewRepository.viewedAt("korean_air"), "2026-01-01T00:00:00.000Z"); });
test("view persistence failure stays honest", () => { Object.assign(globalThis, { localStorage: { getItem: () => null, setItem: () => { throw new Error("quota"); } } }); const result = airlineJourneyViewRepository.markViewed("korean_air"); assert.equal(result.ok, false); assert.equal(airlineJourneyViewRepository.viewedAt("korean_air"), undefined); });
