import type { AirlineFAQ, AirlineKnowledgeProfile } from "./airline-knowledge-repository";
import type { AirlineResearchRecord } from "./airline-research-repository";
import type { AirlineCoachingInsight, AirlineInterviewQuestion } from "./airline-knowledge-transformer";

const cabinCrew = "https://careers.ba.com/jobs/cabin-crew";
const talentPool = "https://careers.ba.com/jobs/cabin-crew-talent-pool";
const faqs = "https://careers.ba.com/cabin-crew-faqs";
const ba = "https://www.ba.com/";
const cabinCrewThirdParty = "https://www.cabincrew.com/british-airways-recruitment-process/";
const guideThirdParty = "https://www.turningleftforless.com/british-airways-cabin-crew-requirements/";
const collectedAt = "2026-07-30T00:00:00.000Z";
const fact = (category: AirlineResearchRecord["extractedFacts"][number]["category"], key: string, value: string, sourceUrl: string, sourceGrade: "A" | "C" | "D" | "E") => ({ category, key, value, sourceUrl, sourceGrade, verified: false });

export const britishAirwaysResearchRecords: AirlineResearchRecord[] = [
  { id: "ba-profile-official-20260730", airlineId: "british_airways", sourceTitle: "British Airways official website", sourceUrl: ba, sourceType: "Official", collectedBy: "manual", collectedAt, sourceDate: "2026-07-29", sourceGrade: "A", confidence: "high", status: "collected", rawSummary: "Official British Airways profile candidates.", rawText: "British Airways; United Kingdom. Headquarters, hub, founding year, IAG relationship and detailed British-service interpretation require confirmation in this Pack.", extractedFacts: [fact("profile", "official_name", "British Airways", ba, "A"), fact("profile", "country", "United Kingdom", ba, "A"), fact("profile", "headquarters", "Requires confirmation.", ba, "E"), fact("profile", "hub", "Requires confirmation.", ba, "E"), fact("profile", "founded", "Requires confirmation.", ba, "E"), fact("profile", "iag_relationship", "Requires official confirmation from a permitted source in this Pack.", ba, "E")] },
  { id: "ba-cabin-crew-official-20260730", airlineId: "british_airways", sourceTitle: "British Airways Cabin Crew", sourceUrl: cabinCrew, sourceType: "Official", collectedBy: "manual", collectedAt, sourceDate: "2026-07-29", sourceGrade: "A", confidence: "high", status: "collected", rawSummary: "Official British Airways cabin-crew role candidates.", rawText: "Global travel and world-class destinations; customer-focused service; warm, professional and reliable service; safety and security priority; teamwork, calm and reliable attitude.", extractedFacts: [fact("profile", "global_network", "Global travel and world-class destinations are described in the cabin-crew role.", cabinCrew, "A"), fact("service", "customer_focused", "Customers are at the heart of service.", cabinCrew, "A"), fact("service", "warm_professional_service", "Warm, professional and reliable service candidate.", cabinCrew, "A"), fact("safety", "safety_security", "Safety and security duties are a priority.", cabinCrew, "A"), fact("interview", "coaching_directions", "Use customer service, teamwork, calmness, safety and responsibility as preparation directions.", cabinCrew, "C")] },
  { id: "ba-talent-pool-official-20260730", airlineId: "british_airways", sourceTitle: "British Airways Cabin Crew Talent Pool", sourceUrl: talentPool, sourceType: "Official", collectedBy: "manual", collectedAt, sourceDate: "2026-07-29", sourceGrade: "A", confidence: "high", status: "collected", rawSummary: "Heathrow-mainline official Talent Pool candidates only.", rawText: "Heathrow mainline: age 18+, fluent spoken and written English, at least 12 months customer-service experience, right to live and work in the UK, no sponsorship, valid passport, unrestricted worldwide travel, ability to obtain required visas and airside-security pass, satisfactory background checks and high grooming standards. Not Gatwick or all-BA conditions.", extractedFacts: [fact("recruitment", "minimum_age", "Heathrow-mainline only: age 18+ at application.", talentPool, "A"), fact("language", "english", "Heathrow-mainline only: fluent spoken and written English.", talentPool, "A"), fact("experience", "customer_service", "Heathrow-mainline only: minimum 12 months customer-service experience.", talentPool, "A"), fact("work_authorization", "uk_work_right", "Heathrow-mainline only: right to live and work in the UK; no sponsorship.", talentPool, "A"), fact("passport", "passport_travel", "Heathrow-mainline only: valid passport, unrestricted worldwide travel and ability to obtain required visas.", talentPool, "A"), fact("background_check", "security_pass", "Heathrow-mainline only: ability to obtain an airside security pass and satisfactory background checks.", talentPool, "A"), fact("grooming", "grooming", "Heathrow-mainline only: high grooming standards.", talentPool, "A"), fact("recruitment", "education", "Specific education and major requirements require confirmation.", talentPool, "E"), fact("language", "second_language", "Second-language preference requires confirmation.", talentPool, "E")] },
  { id: "ba-faq-official-20260730", airlineId: "british_airways", sourceTitle: "British Airways Cabin Crew FAQs", sourceUrl: faqs, sourceType: "Official", collectedBy: "manual", collectedAt, sourceDate: "2026-07-29", sourceGrade: "A", confidence: "high", status: "collected", rawSummary: "Official FAQ candidates without numeric or process extrapolation.", rawText: "Online application, eligibility screening, online assessment candidate, security/background-check candidate, medical candidate, training candidate, visible-tattoo wording and travel/security requirements. Detailed reach, swimming, medical, commute and training-duration details require confirmation.", extractedFacts: [fact("application", "online_application", "Online application candidate.", faqs, "A"), fact("recruitment", "eligibility_screening", "Eligibility screening candidate.", faqs, "A"), fact("interview", "online_assessment", "Online assessment is referenced; exact format requires confirmation.", faqs, "A"), fact("medical", "medical", "Medical candidate; exact content requires confirmation.", faqs, "A"), fact("background_check", "background_check", "Security and background-check candidate.", faqs, "A"), fact("training", "training", "Training candidate; duration requires confirmation.", faqs, "A"), fact("grooming", "visible_tattoo", "Visible tattoos while in BA uniform are addressed in the official FAQ wording.", faqs, "A"), fact("physical", "numeric_physical", "Reach, swimming, detailed medical, commute and training duration require confirmation.", faqs, "E")] },
  { id: "ba-third-party-process-20260730", airlineId: "british_airways", sourceTitle: "Third-party British Airways recruitment-process guide", sourceUrl: cabinCrewThirdParty, sourceType: "Third Party", collectedBy: "manual", collectedAt, sourceDate: "2026-07-29", sourceGrade: "C", confidence: "medium", status: "collected", rawSummary: "Non-official process candidates only.", rawText: "Video interview, assessment centre, group exercise, role-play and face-to-face interview candidates are third-party-only and require official confirmation.", extractedFacts: [fact("interview", "video_interview", "Third-party candidate only.", cabinCrewThirdParty, "C"), fact("interview", "assessment_centre", "Third-party candidate only.", cabinCrewThirdParty, "C"), fact("interview", "group_exercise", "Third-party candidate only.", cabinCrewThirdParty, "C"), fact("interview", "role_play", "Third-party candidate only.", cabinCrewThirdParty, "C"), fact("interview", "face_to_face", "Third-party candidate only.", cabinCrewThirdParty, "C")] },
  { id: "ba-third-party-physical-20260730", airlineId: "british_airways", sourceTitle: "Third-party British Airways requirements guide", sourceUrl: guideThirdParty, sourceType: "Third Party", collectedBy: "manual", collectedAt, sourceDate: "2026-07-29", sourceGrade: "D", confidence: "low", status: "collected", rawSummary: "Non-official physical and base candidates only.", rawText: "Reach, swimming, medical details, 90-minute commute, training 4-6 weeks, Gatwick and mixed-fleet claims are unverified and must not be official or mainline-global facts.", extractedFacts: [fact("physical", "reach_swimming", "Third-party candidate only.", guideThirdParty, "D"), fact("medical", "medical_detail", "Third-party candidate only.", guideThirdParty, "D"), fact("recruitment", "commute", "Third-party candidate only.", guideThirdParty, "D"), fact("training", "training_duration", "Third-party candidate only.", guideThirdParty, "D"), fact("recruitment", "gatwick", "Gatwick candidate only; requires official confirmation.", guideThirdParty, "D")] },
];

export const britishAirwaysKnowledgeProfileCandidate: Partial<AirlineKnowledgeProfile> = { id: "profile-british-airways", airlineId: "british_airways", reviewStatus: "reviewed", publishStatus: "unpublished", overview: { officialName: "British Airways", displayName: "British Airways", countryCode: "GB", region: "europe", businessModel: "full_service", website: cabinCrew, brandIdentity: { value: "Customer-focused, warm, professional and reliable service are review candidates.", status: "needs_review", sourceIds: ["ba-cabin-crew-official-20260730"] }, servicePhilosophy: "Warm and professional service requires review.", customerFocus: { value: "Customer-focused service requires review.", status: "needs_review", sourceIds: ["ba-cabin-crew-official-20260730"] }, safetyCulture: { value: "Safety and security priority requires review.", status: "needs_review", sourceIds: ["ba-cabin-crew-official-20260730"] } } as AirlineKnowledgeProfile["overview"], recruitmentProfile: { recruitmentLanguages: [], applicationLanguages: [], commonRecruitmentStages: ["application", "document_screening", "online_assessment", "medical_check", "background_check", "other"], officialCareerPageUrl: talentPool, currentStatus: "unknown", checkedAt: "2026-07-30", eligibilityRequirements: { value: ["Only Heathrow-mainline Talent Pool requirements are official candidates in this Pack."], status: "needs_review", sourceIds: ["ba-talent-pool-official-20260730"] }, languageRequirements: { value: ["Heathrow-mainline English candidate only; other language requirements require confirmation."], status: "needs_review", sourceIds: ["ba-talent-pool-official-20260730"] }, selectionSteps: { status: "needs_review", sourceIds: ["ba-faq-official-20260730"] }, physicalRequirements: { status: "needs_review", sourceIds: ["ba-faq-official-20260730"] }, status: "draft" } };

const faq=(id:string,question:string,answer:string,grade:"A"|"E"="A"):AirlineFAQ=>({id,airlineId:"british_airways",category:"eligibility",question:`지원 준비 참고 FAQ: ${question}`,answer,sourceGrade:grade,sourceReference:faqs,status:"draft",publishStatus:"unpublished",createdAt:collectedAt,updatedAt:collectedAt});
export const britishAirwaysFaqDrafts=[faq("ba-faq-apply","Where can I apply?","Use the official British Airways Cabin Crew or Talent Pool page."),faq("ba-faq-age","What age is required?","The official Talent Pool candidate states 18+ at application for Heathrow mainline only."),faq("ba-faq-english","Is English required?","The official Heathrow-mainline Talent Pool candidate requires fluent spoken and written English."),faq("ba-faq-work-right","Is UK work authorization required?","The official Heathrow-mainline Talent Pool candidate states the right to live and work in the UK, without sponsorship."),faq("ba-faq-tattoo","What is the tattoo policy?","The official FAQ addresses visible tattoos while in BA uniform; detailed placement rules require confirmation."),faq("ba-faq-process","What are the stages?","Application, eligibility screening, assessment, medical/security and training are candidates; detailed stages require confirmation.")];
const q=(id:string,prompt:string,questionType:AirlineInterviewQuestion["questionType"],competencyTags:string[],recommendedExperienceTags:string[]):AirlineInterviewQuestion=>({id,airlineId:"british_airways",prompt:`지원 준비용 예상 질문: ${prompt}`,questionType,competencyTags,recommendedExperienceTags,followUpQuestions:[],sourceReferences:[cabinCrew],status:"draft",publishStatus:"unpublished",sourceBasis:"coaching_draft"});
export const britishAirwaysInterviewQuestionDrafts=[q("ba-q-1","Why British Airways?","motivation",["brand_understanding","service_orientation","global_mindset"],["airline_research","customer_service"]),q("ba-q-2","Tell me about handling a difficult customer professionally.","service",["empathy","de_escalation","professionalism"],["complaint_handling","retail_service"]),q("ba-q-3","Tell me about providing personalised service.","service",["personalisation","initiative","communication"],["customer_service","hospitality"]),q("ba-q-4","Tell me about working in a multicultural team.","experience",["cross_cultural_communication","collaboration","adaptability"],["international_project","diverse_workplace"]),q("ba-q-5","Tell me about supporting a colleague under pressure.","experience",["reliability","supportiveness","calmness"],["shift_work","crisis_response"]),q("ba-q-6","What would you do if you noticed a safety risk while serving customers?","safety",["situational_judgment","procedure_compliance","assertiveness"],["sop_adherence","risk_reporting"]),q("ba-q-7","How do you prioritise safety and service?","safety",["safety_first","prioritisation","judgment"],["rule_following","customer_service"]),q("ba-q-8","How would you provide clear guidance in English?","language",["spoken_english","clarity","reassurance"],["customer_support","communication"]),q("ba-q-9","How do you remain calm and professional?","experience",["composure","resilience","reliability"],["high_pressure_work","frontline_service"]),q("ba-q-10","How would you prepare for an emergency?","safety",["preparedness","responsibility","procedure_compliance"],["safety_awareness","training_discipline"])];
export const britishAirwaysCoachingInsightDrafts:AirlineCoachingInsight[]=[{id:"ba-insight-motivation",airlineId:"british_airways",topic:"motivation",coachMessage:"British Airways 지원 방향은 안전과 보안을 최우선 가치로 연결하고, 12개월 이상 고객 서비스 경험이 있다면 구체적인 행동으로 제시하며, 차분하고 명확한 의사소통·맞춤 서비스·팀워크·책임감을 설명하도록 안내합니다.",goodDirections:["안전과 보안을 최우선 가치로 연결","12개월 이상 고객 서비스 경험을 구체적 행동으로 제시","차분하고 명확한 의사소통","맞춤 서비스 경험","팀워크와 책임감","British service를 외모·억양이 아닌 신뢰성과 서비스 태도로 설명"],avoidPatterns:["여행 선택만 강조","영국식 억양을 직무 적합성처럼 강조","비자 스폰서 가능성 추정","Euroflyer·Cityflyer 조건 혼입","신체·수영 기준을 비공식 정보로 단정","실제 평가 기준 또는 기출 표현"],recommendedExperienceTags:["customer_service","safety_awareness","teamwork","professional_communication","service_recovery"],sourceReferences:[cabinCrew,talentPool],status:"draft",publishStatus:"unpublished"}];
