import type { AirlineFAQ, AirlineKnowledgeProfile } from "./airline-knowledge-repository";
import type { AirlineResearchRecord } from "./airline-research-repository";
import type { AirlineCoachingInsight, AirlineInterviewQuestion } from "./airline-knowledge-transformer";

const careers = "https://www.china-airlines.com/us/en/career";
const collectedAt = "2026-07-29T00:00:00.000Z";
const fact = (category: AirlineResearchRecord["extractedFacts"][number]["category"], key: string, value: string, sourceUrl: string, sourceGrade: "A" | "B" | "C" | "E") => ({ category, key, value, sourceUrl, sourceGrade, verified: false });

export const chinaAirlinesResearchRecords: AirlineResearchRecord[] = [
  { id: "china-airlines-profile-20260729", airlineId: "china_airlines", sourceTitle: "China Airlines supplied profile research", sourceUrl: careers, sourceType: "Company Profile", collectedBy: "manual", collectedAt, sourceDate: "2026-07-29", sourceGrade: "A", confidence: "medium", status: "collected", rawSummary: "Supplied China Airlines profile candidates only; Air China is excluded.", rawText: "China Airlines; Taiwan-based airline; service quality; safety culture; customer satisfaction; professional development; teamwork; multicultural service.", extractedFacts: [fact("profile", "official_name", "China Airlines", careers, "A"), fact("profile", "country", "Taiwan", careers, "A"), fact("service", "service_quality", "Service quality is a supplied preparation candidate.", careers, "A"), fact("safety", "safety_culture", "Safety culture is a supplied preparation candidate.", careers, "A"), fact("application", "country_scope", "Global profile scope requires confirmation.", careers, "E")] },
  { id: "china-airlines-recruitment-20260729", airlineId: "china_airlines", sourceTitle: "China Airlines supplied recruitment research", sourceUrl: careers, sourceType: "Recruitment Data", collectedBy: "manual", collectedAt, sourceDate: "2026-07-29", sourceGrade: "A", confidence: "medium", status: "collected", rawSummary: "Recruitment candidates are retained without global-condition inference.", rawText: "Candidates: official recruitment page, education/development, service quality and safety training. Age, education, major, English, Chinese, second language, physical, medical, grooming and base conditions require review.", extractedFacts: [fact("recruitment", "careers_page", "Official recruitment page candidate.", careers, "A"), fact("recruitment", "education_development", "Education and development information requires review.", careers, "E"), fact("service", "service_quality", "Service quality candidate.", careers, "A"), fact("safety", "safety_training", "Safety training candidate.", careers, "A"), fact("language", "chinese_mandatory", "Chinese requirement must not be inferred.", careers, "E"), fact("recruitment", "country_base_difference", "Country and base differences require review.", careers, "E")] },
  { id: "china-airlines-preparation-20260729", airlineId: "china_airlines", sourceTitle: "China Airlines supplied preparation candidates", sourceUrl: careers, sourceType: "Interview Preparation and Application Coaching", collectedBy: "manual", collectedAt, sourceDate: "2026-07-29", sourceGrade: "C", confidence: "medium", status: "collected", rawSummary: "Preparation directions only; not official interview questions.", rawText: "Directions: safety culture, customer satisfaction, professional training, teamwork and multicultural service. Avoid claiming Chinese is mandatory, generalizing Taiwan employment conditions, or omitting safety.", extractedFacts: [fact("application", "coaching_directions", "Connect safety, customer satisfaction, training, teamwork and multicultural service to selected experience.", careers, "C"), fact("application", "avoid_patterns", "Do not infer Chinese as mandatory or generalize Taiwan-specific conditions.", careers, "C")] },
];

export const chinaAirlinesKnowledgeProfileCandidate: Partial<AirlineKnowledgeProfile> = { id: "profile-china-airlines", airlineId: "china_airlines", reviewStatus: "reviewed", publishStatus: "unpublished", overview: { officialName: "China Airlines", displayName: "China Airlines", countryCode: "TW", region: "asia_pacific", businessModel: "full_service", website: careers, brandIdentity: { value: "Taiwan-based airline profile requires review.", status: "needs_review", sourceIds: ["china-airlines-profile-20260729"] }, servicePhilosophy: "Service quality and customer satisfaction are review candidates.", customerFocus: { value: "Customer-oriented service requires review.", status: "needs_review", sourceIds: ["china-airlines-profile-20260729"] }, safetyCulture: { value: "Safety culture and training require review.", status: "needs_review", sourceIds: ["china-airlines-profile-20260729"] } } as AirlineKnowledgeProfile["overview"] };

const faq = (id: string, q: string, a: string): AirlineFAQ => ({ id, airlineId: "china_airlines", category: "eligibility", question: `지원 준비 참고 FAQ: ${q}`, answer: a, sourceGrade: "A", sourceReference: careers, status: "draft", publishStatus: "unpublished", createdAt: collectedAt, updatedAt: collectedAt });
export const chinaAirlinesFaqDrafts = [faq("china-faq-1", "Where should I check recruitment information?", "Confirm the current official China Airlines recruitment page."), faq("china-faq-2", "Are education requirements confirmed?", "Education requirements require review against the applicable posting."), faq("china-faq-3", "Is Chinese required?", "Chinese must not be treated as mandatory without an applicable verified posting."), faq("china-faq-4", "Are base conditions global?", "Country and base-specific conditions require separate confirmation."), faq("china-faq-5", "What should I prepare?", "Prepare evidence of service, teamwork, training and safety awareness.")];

const question = (id: string, prompt: string, questionType: AirlineInterviewQuestion["questionType"], competencyTags: string[], recommendedExperienceTags: string[]): AirlineInterviewQuestion => ({ id, airlineId: "china_airlines", prompt: `지원 준비용 예상 질문: ${prompt}`, questionType, competencyTags, recommendedExperienceTags, followUpQuestions: [], sourceReferences: [careers], status: "draft", publishStatus: "unpublished" });
export const chinaAirlinesInterviewQuestionDrafts = [question("china-q-1", "Why are you interested in China Airlines?", "motivation", ["brand_understanding", "service_orientation"], ["airline_research", "customer_service"]), question("china-q-2", "Why do you want to become cabin crew?", "motivation", ["service_mindset", "resilience"], ["hospitality", "communication"]), question("china-q-3", "Tell us about a customer service experience.", "service", ["empathy", "problem_solving"], ["customer_service", "service_recovery"]), question("china-q-4", "Tell us about working in a team.", "experience", ["teamwork", "communication"], ["teamwork", "project_coordination"]), question("china-q-5", "What would you do if you noticed a safety concern?", "safety", ["judgment", "procedure_compliance"], ["risk_reporting", "safety_awareness"]), question("china-q-6", "How do you balance service and safety?", "safety", ["prioritization", "calmness"], ["rule_following", "customer_service"]), question("china-q-7", "How do you communicate with customers from different cultures?", "language", ["cultural_awareness", "adaptability"], ["multicultural_service", "communication"]), question("china-q-8", "How do you maintain professional training habits?", "experience", ["discipline", "learning_agility"], ["professional_training", "continuous_learning"]), question("china-q-9", "What does customer satisfaction mean to you?", "service", ["customer_focus", "consistency"], ["customer_service", "service_quality"])];

export const chinaAirlinesCoachingInsightDrafts: AirlineCoachingInsight[] = [{ id: "china-insight-motivation", airlineId: "china_airlines", topic: "motivation", coachMessage: "China Airlines 지원 방향은 안전 문화, 고객 만족, 전문 교육, 팀워크와 다문화 서비스를 본인 경험과 연결하는 방식으로 검토해 보세요.", goodDirections: ["safety culture", "customer satisfaction", "professional training", "teamwork", "multicultural service"], avoidPatterns: ["중국어 필수라고 단정", "대만 근무 조건 일반화", "서비스만 강조하고 안전 제외"], recommendedExperienceTags: ["customer_service", "teamwork", "professional_training", "multicultural_experience", "safety_awareness"], sourceReferences: [careers], status: "draft", publishStatus: "unpublished" }];
