import assert from "node:assert/strict";
import test from "node:test";
import { buildDailyActionPlan, weeklyTaskToDailyAction } from "./daily-action-plan";
import type { AirlineApplication } from "./supabase/application-sync-repository";
import type { InterviewSession } from "./mock-interview-session";
import type { InterviewPracticeQueueItem } from "./interview-practice-queue";
import type { AdaptiveWeakness } from "./learning-analytics-adaptive";
import type { WeeklyRoutineTask } from "./learning-analytics-service";

const now = new Date("2026-09-02T10:00:00+09:00");
const questionIds = ["im1", "be1", "sj1"];
const base = { now, balancedQuestionId: "im1", validQuestionIds: questionIds };
const session = (patch: Partial<InterviewSession> = {}): InterviewSession => ({ id: "session-1", mode: "general", questionIds: ["im1", "be1", "sj1"], attemptIds: [], currentQuestionIndex: 1, status: "in_progress", startedAt: "2026-09-01T10:00:00.000Z", ...patch });
const application = (patch: Partial<AirlineApplication> = {}): AirlineApplication => ({ id: "app-1", airlineId: "emirates", airlineNameSnapshot: "Emirates", positionTitle: "객실승무원", status: "planning", createdAt: "2026-09-01T00:00:00.000Z", updatedAt: "2026-09-01T00:00:00.000Z", ...patch });
const queue = (patch: Partial<InterviewPracticeQueueItem> = {}): InterviewPracticeQueueItem => ({ id: "queue-1", questionId: "sj1", reason: "safety", status: "open", priority: 1, createdAt: "2026-09-01T00:00:00.000Z", updatedAt: "2026-09-01T00:00:00.000Z", ...patch });
const weakness = (patch: Partial<AdaptiveWeakness> = {}): AdaptiveWeakness => ({ key: "missing_action", title: "본인 행동", relatedCapability: "interview_communication", state: "persistent", trend: "stable", confidence: "high", occurrenceCount: 3, distinctSourceCount: 3, latestObservedAt: "2026-09-01T00:00:00.000Z", priority: 90, evidence: [], explanation: "최근 3개 연습에서 행동 설명 보완 신호가 확인됐습니다.", recommendedAction: "행동 중심으로 다시 연습하세요.", ...patch });
const weekly = (type: WeeklyRoutineTask["type"], patch: Partial<WeeklyRoutineTask> = {}): WeeklyRoutineTask => ({ id: `task-${type}`, type, title: "오늘 계획", estimatedMinutes: 10, relatedCapability: "interview_communication", reason: "확정한 주간 계획입니다.", ...patch });

test("active mock session is primary resume", () => assert.equal(buildDailyActionPlan({ ...base, sessions: [session()] }).primary.target.kind, "mock_resume"));
test("resume does not create a new session target", () => assert.equal(buildDailyActionPlan({ ...base, sessions: [session()] }).primary.id, "resume:session-1"));
test("D-3 interview becomes a high-priority mock action", () => assert.equal(buildDailyActionPlan({ ...base, applications: [application({ status: "interview", interviewAt: "2026-09-05" })] }).primary.target.kind, "mock_start"));
test("D-2 application deadline opens Application Coach", () => assert.equal(buildDailyActionPlan({ ...base, applications: [application({ deadlineAt: "2026-09-04" })] }).primary.target.kind, "application_coach"));
test("expired deadline is excluded", () => assert.equal(buildDailyActionPlan({ ...base, applications: [application({ deadlineAt: "2026-09-01" })] }).primary.source, "balanced_fallback"));
test("deadline beyond seven days is excluded", () => assert.equal(buildDailyActionPlan({ ...base, applications: [application({ deadlineAt: "2026-09-12" })] }).primary.source, "balanced_fallback"));
test("open safety queue has high priority", () => assert.equal(buildDailyActionPlan({ ...base, queue: [queue()] }).primary.source, "practice_queue"));
test("practiced queue is excluded", () => assert.equal(buildDailyActionPlan({ ...base, queue: [queue({ status: "practiced" })] }).primary.source, "balanced_fallback"));
test("persistent adaptive weakness is selected", () => assert.equal(buildDailyActionPlan({ ...base, weaknesses: [{ weakness: weakness(), questionId: "be1" }] }).primary.source, "adaptive"));
test("emerging weakness is selected", () => assert.equal(buildDailyActionPlan({ ...base, weaknesses: [{ weakness: weakness({ state: "emerging" }), questionId: "be1" }] }).primary.source, "adaptive"));
test("improving weakness has lower priority than weekly task", () => assert.equal(buildDailyActionPlan({ ...base, weaknesses: [{ weakness: weakness({ state: "improving" }), questionId: "be1" }], weeklyTasks: [weekly("self_introduction")] }).primary.source, "weekly_plan"));
test("resolved weakness is excluded", () => assert.equal(buildDailyActionPlan({ ...base, weaknesses: [{ weakness: weakness({ state: "resolved" }), questionId: "be1" }] }).primary.source, "balanced_fallback"));
test("observed weakness is not promoted", () => assert.equal(buildDailyActionPlan({ ...base, weaknesses: [{ weakness: weakness({ state: "observed" }), questionId: "be1" }] }).primary.source, "balanced_fallback"));
test("weekly interview task resolves to Interview Practice", () => assert.equal(weeklyTaskToDailyAction(weekly("interview_question"), base)?.target.kind, "interview_question"));
test("weekly self introduction task resolves", () => assert.equal(weeklyTaskToDailyAction(weekly("self_introduction"), base)?.target.kind, "self_introduction"));
test("weekly application task resolves", () => assert.equal(weeklyTaskToDailyAction(weekly("application_work"), base)?.target.kind, "application_coach"));
test("weekly experience task resolves", () => assert.equal(weeklyTaskToDailyAction(weekly("experience_work"), base)?.target.kind, "experience_library"));
test("invalid weekly question target has no CTA", () => assert.equal(weeklyTaskToDailyAction(weekly("interview_question", { sourceEntityId: "invalid" }), base), null));
test("same queue and adaptive question are deduplicated", () => { const plan = buildDailyActionPlan({ ...base, queue: [queue({ questionId: "be1" })], weaknesses: [{ weakness: weakness(), questionId: "be1" }] }); assert.equal([plan.primary, ...plan.secondary].filter((item) => item.dedupeKey === "question:be1").length, 1); });
test("plan always has one primary and at most two secondary actions", () => { const plan = buildDailyActionPlan({ ...base, sessions: [session()], queue: [queue()], weaknesses: [{ weakness: weakness(), questionId: "be1" }], weeklyTasks: [weekly("self_introduction")] }); assert.ok(plan.primary); assert.ok(plan.secondary.length <= 2); });
test("no signal produces a balanced fallback", () => assert.equal(buildDailyActionPlan(base).primary.source, "balanced_fallback"));
test("CTA candidates do not count as completion", () => assert.equal(buildDailyActionPlan(base).completedCount, 0));
test("completed attempt increases today's completed count", () => assert.equal(buildDailyActionPlan({ ...base, completions: [{ id: "attempt-1", type: "interview_attempt", completedAt: now.toISOString() }] }).completedCount, 1));
test("completed mock session increases today's completed count", () => assert.equal(buildDailyActionPlan({ ...base, completions: [{ id: "session-1", type: "mock_session", completedAt: now.toISOString() }] }).completedCount, 1));
test("application save completion counts only on matching day", () => assert.equal(buildDailyActionPlan({ ...base, completions: [{ id: "answer-1", type: "application_answer", completedAt: "2026-09-01T00:00:00.000Z" }] }).completedCount, 0));
test("same input yields stable ordering", () => { const input = { ...base, queue: [queue()], weeklyTasks: [weekly("self_introduction")] }; assert.deepEqual(buildDailyActionPlan(input), buildDailyActionPlan(input)); });
test("legacy empty adaptive data does not crash", () => assert.ok(buildDailyActionPlan({ ...base, weaknesses: undefined }).primary));
test("invalid question is not promoted from queue", () => assert.equal(buildDailyActionPlan({ ...base, queue: [queue({ questionId: "draft-question" })] }).primary.source, "balanced_fallback"));
test("application draft creates a resume candidate", () => assert.equal(buildDailyActionPlan({ ...base, currentApplicationDraft: { id: "answer-1", updatedAt: now.toISOString() } }).primary.source, "application_draft"));
test("resolver has no Azure dependency", () => assert.equal(JSON.stringify(buildDailyActionPlan(base)).toLowerCase().includes("azure"), false));
