import type { AirlineFAQ, AirlineKnowledgeProfile } from "./airline-knowledge-repository";
import type { AirlineResearchRecord } from "./airline-research-repository";
import type { AirlineCoachingInsight, AirlineInterviewQuestion } from "./airline-knowledge-transformer";

const delta = "https://www.delta.com/";
const careers = "https://careers.delta.com/";
const news = "https://news.delta.com/";
const jobtestprep = "https://www.jobtestprep.com/delta-flight-attendant-assessment";
const onetake = "https://www.onetake.ai/blog/delta-flight-attendant-interview";
const collectedAt = "2026-07-31T00:00:00.000Z";
const fact = (category: AirlineResearchRecord["extractedFacts"][number]["category"], key: string, value: string, sourceUrl: string, sourceGrade: "A" | "C" | "D" | "E") => ({ category, key, value, sourceUrl, sourceGrade, verified: false });

export const deltaAirLinesResearchRecords: AirlineResearchRecord[] = [
  { id: "delta-profile-official-20260731", airlineId: "delta_air_lines", sourceTitle: "Delta Air Lines official website", sourceUrl: delta, sourceType: "Official", collectedBy: "manual", collectedAt, sourceDate: "2026-07-31", sourceGrade: "A", confidence: "medium", status: "collected", rawSummary: "Delta Mainline profile candidates only.", rawText: "Delta Air Lines; United States; global network; safety and customer centricity; servant leadership; teamwork and problem solving. Headquarters, founding year and detailed hub list require review.", extractedFacts: [fact("profile", "official_name", "Delta Air Lines", delta, "A"), fact("profile", "country", "United States", delta, "A"), fact("profile", "global_network", "Global network candidate.", delta, "A"), fact("safety", "safety_customer", "Safety and customer centricity candidates.", delta, "A"), fact("service", "servant_leadership", "Servant leadership candidate.", delta, "A"), fact("service", "teamwork_problem_solving", "Teamwork and problem-solving candidates.", delta, "A"), fact("profile", "headquarters", "Requires confirmation.", delta, "E"), fact("profile", "founded", "Requires confirmation.", delta, "E"), fact("base", "hubs", "Detailed hub list requires confirmation.", delta, "E")] },
  { id: "delta-recruitment-official-20260731", airlineId: "delta_air_lines", sourceTitle: "Delta Careers Flight Attendant candidates", sourceUrl: careers, sourceType: "Official", collectedBy: "manual", collectedAt, sourceDate: "2026-07-31", sourceGrade: "A", confidence: "medium", status: "collected", rawSummary: "Delta Mainline Flight Attendant candidates only; excludes Delta Connection carriers.", rawText: "Official candidates: minimum age 21, high-school diploma/GED, English fluency, legal authorization to work in the US, passport/travel ability, background screening, drug testing, medical/fitness assessment and initial training in Atlanta. Delta Connection, Endeavor, SkyWest and Republic are excluded.", extractedFacts: [fact("recruitment", "minimum_age", "Delta Mainline candidate: minimum age 21.", careers, "A"), fact("recruitment", "education", "Delta Mainline candidate: high-school diploma or GED.", careers, "A"), fact("language", "english", "Delta Mainline candidate: English fluency.", careers, "A"), fact("work_authorization", "us_work_authorization", "Delta Mainline candidate: legally authorized to work in the United States.", careers, "A"), fact("recruitment", "passport_travel", "Delta Mainline candidate: passport and travel ability.", careers, "A"), fact("background_check", "background_screening", "Delta Mainline candidate: background screening.", careers, "A"), fact("medical", "drug_testing", "Delta Mainline candidate: drug testing.", careers, "A"), fact("medical", "medical_fitness", "Delta Mainline candidate: medical and fitness assessment.", careers, "A"), fact("training", "atlanta_training", "Delta Mainline candidate: initial training in Atlanta.", careers, "A"), fact("language", "lod_conditions", "Language of Destination conditions must not be generalized.", careers, "E"), fact("base", "base_assignment", "Base-assignment rules require confirmation.", careers, "E"), fact("work_authorization", "visa_sponsorship", "Visa-sponsorship policy requires confirmation.", careers, "E")] },
  { id: "delta-process-official-20260731", airlineId: "delta_air_lines", sourceTitle: "Delta Careers and News recruitment candidates", sourceUrl: news, sourceType: "Official", collectedBy: "manual", collectedAt, sourceDate: "2026-07-31", sourceGrade: "A", confidence: "medium", status: "collected", rawSummary: "Official general-process candidates only.", rawText: "Online application, eligibility screening, talent assessment and training candidates. VJT, video interview, Event Day, CJO, and detailed background/drug-test process require confirmation.", extractedFacts: [fact("recruitment", "online_application", "Online Application candidate.", careers, "A"), fact("recruitment", "eligibility_screening", "Eligibility Screening candidate.", careers, "A"), fact("interview", "talent_assessment", "Talent Assessment candidate.", careers, "A"), fact("training", "training", "Training candidate.", careers, "A"), fact("interview", "vjt", "VJT details require confirmation.", careers, "E"), fact("interview", "video_interview", "Video Interview requires confirmation.", careers, "E"), fact("interview", "event_day", "Event Day composition requires confirmation.", careers, "E"), fact("interview", "cjo", "Conditional Job Offer procedure requires confirmation.", careers, "E")] },
  { id: "delta-third-party-physical-20260731", airlineId: "delta_air_lines", sourceTitle: "Third-party Delta Flight Attendant preparation sources", sourceUrl: jobtestprep, sourceType: "Third Party", collectedBy: "manual", collectedAt, sourceDate: "2026-07-31", sourceGrade: "D", confidence: "low", status: "collected", rawSummary: "Third-party physical and interview candidates only.", rawText: "Reach, jumpseat, water drill, swimming, eyesight, tattoo and grooming claims from Jobtestprep, OneTake, Indeed or LinkedIn citations are not official Delta information.", extractedFacts: [fact("physical", "reach", "Third-party candidate only.", jobtestprep, "D"), fact("physical", "jumpseat", "Third-party candidate only.", jobtestprep, "D"), fact("physical", "water_swimming", "Third-party candidate only.", jobtestprep, "D"), fact("medical", "eyesight", "Third-party candidate only.", onetake, "D"), fact("grooming", "tattoo_grooming", "Third-party candidate only.", onetake, "D")] },
  { id: "delta-preparation-20260731", airlineId: "delta_air_lines", sourceTitle: "Delta supplied coaching candidates", sourceUrl: delta, sourceType: "Interview Preparation and Application Coaching", collectedBy: "manual", collectedAt, sourceDate: "2026-07-31", sourceGrade: "C", confidence: "medium", status: "collected", rawSummary: "Coaching directions only; not actual interview questions.", rawText: "Connect safety and customer experience, servant leadership, problem solving, adaptability, teamwork and global customer communication. Avoid free-flight motivations, inferred US work authorization, LOD generalization, Delta Connection mixing and third-party physical claims.", extractedFacts: [fact("interview", "question_patterns", "Support questions for motivation, safety, customer recovery, teamwork, adaptability and multicultural communication.", delta, "C"), fact("application", "coaching_directions", "Connect safety, service, servant leadership, problem solving and teamwork to selected experience.", delta, "C"), fact("application", "avoid_patterns", "Do not infer US work rights, generalize LOD conditions, mix Delta Connection, or claim third-party physical criteria.", delta, "C")] },
];

export const deltaAirLinesKnowledgeProfileCandidate: Partial<AirlineKnowledgeProfile> = { id: "profile-delta-air-lines", airlineId: "delta_air_lines", reviewStatus: "draft", publishStatus: "unpublished", overview: { officialName: "Delta Air Lines", displayName: "Delta Air Lines", countryCode: "US", region: "north_america", businessModel: "full_service", website: careers, brandIdentity: { value: "Safety, customer centricity and servant leadership are review candidates.", status: "needs_review", sourceIds: ["delta-profile-official-20260731"] }, servicePhilosophy: "Customer centricity and problem solving require review.", customerFocus: { value: "Global customer service requires review.", status: "needs_review", sourceIds: ["delta-profile-official-20260731"] }, safetyCulture: { value: "Safety-first decision making requires review.", status: "needs_review", sourceIds: ["delta-profile-official-20260731"] } } as AirlineKnowledgeProfile["overview"], recruitmentProfile: { recruitmentLanguages: [], applicationLanguages: [], commonRecruitmentStages: ["application", "document_screening", "online_assessment", "other"], officialCareerPageUrl: careers, currentStatus: "unknown", checkedAt: "2026-07-31", eligibilityRequirements: { value: ["Delta Mainline eligibility candidates require current-posting confirmation."], status: "needs_review", sourceIds: ["delta-recruitment-official-20260731"] }, languageRequirements: { value: ["English candidate is separate from Language of Destination conditions."], status: "needs_review", sourceIds: ["delta-recruitment-official-20260731"] }, selectionSteps: { status: "needs_review", sourceIds: ["delta-process-official-20260731"] }, physicalRequirements: { status: "needs_review", sourceIds: ["delta-recruitment-official-20260731"] }, status: "draft" } };

const faq=(id:string,question:string,answer:string,grade:"A"|"E"="A"):AirlineFAQ=>({id,airlineId:"delta_air_lines",category:"eligibility",question:`지원 준비 참고 FAQ: ${question}`,answer,sourceGrade:grade,sourceReference:careers,status:"draft",publishStatus:"unpublished",createdAt:collectedAt,updatedAt:collectedAt});
export const deltaAirLinesFaqDrafts=[faq("delta-faq-apply","Where should I apply?","Use the official Delta Careers site and the applicable Delta Mainline Flight Attendant posting."),faq("delta-faq-age","What age is required?","The supplied official candidate lists minimum age 21 for Delta Mainline."),faq("delta-faq-work","Is US work authorization required?","The supplied official candidate lists legal authorization to work in the United States; sponsorship policy requires confirmation."),faq("delta-faq-language","Are LOD conditions universal?","No. Language of Destination conditions must not be generalized to all Delta Flight Attendant applicants.","E"),faq("delta-faq-physical","What are the physical requirements?","Medical and fitness assessment are candidates; reach, jumpseat, swimming, eyesight, tattoo and grooming details require confirmation.","E"),faq("delta-faq-training","Is training included?","Initial training in Atlanta is a supplied Delta Mainline candidate; verify the current posting.")];
const q=(id:string,prompt:string,questionType:AirlineInterviewQuestion["questionType"],competencyTags:string[],recommendedExperienceTags:string[]):AirlineInterviewQuestion=>({id,airlineId:"delta_air_lines",prompt:`지원 준비용 예상 질문: ${prompt}`,questionType,competencyTags,recommendedExperienceTags,followUpQuestions:[],sourceReferences:[delta],status:"draft",publishStatus:"unpublished",sourceBasis:"coaching_draft"});
export const deltaAirLinesInterviewQuestionDrafts=[q("delta-q-why","Why Delta?","motivation",["brand_understanding","customer_centricity","service_orientation"],["airline_research","customer_service"]),q("delta-q-safety","Describe a safety-first decision you made.","safety",["safety_first","judgment","procedure_compliance"],["risk_reporting","rule_following"]),q("delta-q-recovery","Tell us about recovering a difficult customer experience.","service",["empathy","problem_solving","service_recovery"],["complaint_handling","frontline_service"]),q("delta-q-team","Tell us about serving a team through a challenging situation.","experience",["servant_leadership","teamwork","reliability"],["team_support","shift_work"]),q("delta-q-adapt","Tell us about adapting to change under pressure.","experience",["adaptability","resilience","calmness"],["change_management","high_pressure_work"]),q("delta-q-global","How do you communicate with customers from different cultures?","language",["multicultural_communication","respect","clarity"],["global_customer_service","cross_cultural_experience"]),q("delta-q-service-safety","How do you balance service with safety?","safety",["prioritization","customer_focus","safety_awareness"],["customer_service","safety_awareness"]),q("delta-q-problem","Tell us about solving a problem for a customer.","service",["problem_solving","initiative","professionalism"],["problem_resolution","customer_service"])];
export const deltaAirLinesCoachingInsightDrafts:AirlineCoachingInsight[]=[{id:"delta-insight-motivation",airlineId:"delta_air_lines",topic:"motivation",coachMessage:"Delta 지원 방향은 안전과 고객 경험의 균형, servant leadership, 문제 해결, 변화 적응력, 팀워크와 글로벌 고객 대응을 선택한 경험에 연결하도록 안내합니다.",goodDirections:["안전과 고객 경험 균형","servant leadership","문제 해결 경험","변화 적응력","팀워크","글로벌 고객 대응"],avoidPatterns:["무료 항공권 중심 동기","미국 취업권 추정","LOD 조건 일반화","Delta Connection 혼입","제3자 신체 기준 단정"],recommendedExperienceTags:["safety_awareness","customer_service","teamwork","problem_solving","multicultural_experience"],sourceReferences:[delta,careers],status:"draft",publishStatus:"unpublished"}];
