import type {
  AirlineFAQ,
  AirlineKnowledgeProfile,
} from "./airline-knowledge-repository";
import type { AirlineResearchRecord } from "./airline-research-repository";
import type {
  AirlineCoachingInsight,
  AirlineInterviewQuestion,
} from "./airline-knowledge-transformer";

const careers = "https://www.etihad.com/en-gb/about-us/careers",
  portal = "https://careers.etihad.com/",
  site = "https://www.etihad.com/en/",
  collectedAt = "2026-07-27T00:00:00.000Z";
const fact = (
  category: AirlineResearchRecord["extractedFacts"][number]["category"],
  key: string,
  value: string,
  sourceUrl: string,
  sourceGrade: "A" | "B" | "C" | "D" | "E" = "A",
) => ({ category, key, value, sourceUrl, sourceGrade, verified: false });

/** Transcribed only from the supplied Etihad Knowledge Pack. All records are collected and facts remain unverified. */
export const etihadResearchRecords: AirlineResearchRecord[] = [
  {
    id: "etihad-profile-20260727",
    airlineId: "etihad_airways",
    sourceTitle: "Etihad and Careers official pages",
    sourceUrl: site,
    sourceType: "Company Profile",
    collectedBy: "manual",
    collectedAt,
    sourceDate: "2026-07-27",
    sourceGrade: "A",
    rawSummary: "Supplied Etihad Profile Data and Source Table.",
    rawText:
      "UAE; Abu Dhabi; premium travel experience; guest-focused onboard service; worldwide destinations; global environment; health screening.",
    confidence: "high",
    status: "collected",
    extractedFacts: [
      fact("profile", "official_name", "Etihad Airways", site),
      fact("profile", "country", "UAE", site),
      fact("profile", "headquarters", "Abu Dhabi", careers),
      fact("profile", "hub", "Abu Dhabi based operations.", site),
      fact(
        "profile",
        "network",
        "Worldwide destinations / global routes.",
        site,
      ),
      fact(
        "brand",
        "brand_value",
        "Premium travel experience, ambition, world-class airline.",
        site,
      ),
      fact(
        "service",
        "service_philosophy",
        "Premium travel experience and guest-focused onboard service.",
        site,
      ),
      fact(
        "service",
        "customer_experience",
        "Worldwide destinations with premium travel experience.",
        site,
      ),
      fact(
        "safety",
        "health_screening",
        "UAE/GCAA medical and health screening requirements apply.",
        careers,
      ),
    ],
  },
  {
    id: "etihad-recruitment-20260727",
    airlineId: "etihad_airways",
    sourceTitle: "Etihad Careers official pages",
    sourceUrl: portal,
    sourceType: "Recruitment Data",
    collectedBy: "manual",
    collectedAt,
    sourceDate: "2026-07-27",
    sourceGrade: "A",
    rawSummary: "Supplied Etihad Recruitment Data.",
    rawText:
      "Official Careers and recruitment portal; UAE/GCAA medical and health screening requirement; current vacancies must be confirmed on the portal.",
    confidence: "high",
    status: "collected",
    extractedFacts: [
      fact(
        "recruitment",
        "official_careers",
        "Etihad official Careers page.",
        careers,
      ),
      fact(
        "application",
        "official_portal",
        "Etihad Careers recruitment portal.",
        portal,
      ),
      fact(
        "recruitment",
        "health_screening",
        "UAE/GCAA medical and health screening requirements apply.",
        careers,
      ),
      fact(
        "application",
        "current_vacancies",
        "Current vacancy availability requires confirmation on the official portal.",
        portal,
        "E",
      ),
    ],
  },
  {
    id: "etihad-preparation-20260727",
    airlineId: "etihad_airways",
    sourceTitle: "Supplied Etihad preparation candidates",
    sourceUrl: site,
    sourceType: "Interview Preparation and Application Coaching",
    collectedBy: "manual",
    collectedAt,
    sourceDate: "2026-07-27",
    sourceGrade: "C",
    rawSummary:
      "Supplied support prompts and coaching directions; not actual interview questions.",
    rawText:
      "Preparation prompts for motivation, service, teamwork, safety, language, multicultural communication. Directions: premium guest experience, Abu Dhabi global environment, hospitality, safety awareness. Avoid overseas-life-only emphasis and service-philosophy-free applications.",
    confidence: "medium",
    status: "collected",
    extractedFacts: [
      fact(
        "interview",
        "question_motivation",
        "지원 준비용 예상 질문: Why Etihad Airways?",
        site,
        "C",
      ),
      fact(
        "interview",
        "question_service",
        "지원 준비용 예상 질문: Tell us about a time you handled a difficult customer.",
        site,
        "C",
      ),
      fact(
        "interview",
        "question_teamwork",
        "지원 준비용 예상 질문: Tell us about a time you worked in a team under pressure.",
        site,
        "C",
      ),
      fact(
        "interview",
        "question_safety",
        "지원 준비용 예상 질문: What would you do if you noticed a safety risk during service?",
        site,
        "C",
      ),
      fact(
        "interview",
        "question_language",
        "지원 준비용 예상 질문: Please introduce yourself in English.",
        site,
        "C",
      ),
      fact(
        "interview",
        "question_multicultural",
        "지원 준비용 예상 질문: How do you adapt communication for customers from different cultures?",
        site,
        "C",
      ),
      fact(
        "application",
        "coach_message_motivation",
        "Connect premium guest experience, Abu Dhabi global environment, hospitality, and safety awareness to selected evidence.",
        site,
        "C",
      ),
      fact(
        "application",
        "good_direction_motivation",
        "premium guest experience",
        site,
        "C",
      ),
      fact(
        "application",
        "good_direction_motivation",
        "Abu Dhabi global environment",
        careers,
        "C",
      ),
      fact(
        "application",
        "good_direction_motivation",
        "hospitality",
        portal,
        "C",
      ),
      fact(
        "application",
        "good_direction_motivation",
        "safety awareness",
        careers,
        "C",
      ),
      fact(
        "application",
        "avoid_pattern_motivation",
        "Emphasizing overseas life only.",
        site,
        "C",
      ),
      fact(
        "application",
        "avoid_pattern_motivation",
        "Applying without a connection to service philosophy.",
        site,
        "C",
      ),
    ],
  },
  {
    id: "etihad-needs-review-20260727",
    airlineId: "etihad_airways",
    sourceTitle: "Supplied Etihad items requiring confirmation",
    sourceUrl: careers,
    sourceType: "Needs review",
    collectedBy: "manual",
    collectedAt,
    sourceDate: "2026-07-27",
    sourceGrade: "E",
    rawSummary:
      "Age, education, English, reach, tattoo policy, assessment stages, regional eligibility and event details require confirmation.",
    rawText:
      "Needs review: founding year, age, education, English, reach, tattoo policy, assessment stages, current regional eligibility, events.",
    confidence: "low",
    status: "collected",
    extractedFacts: [
      fact("profile", "founding_year", "Requires confirmation.", site, "E"),
      fact(
        "recruitment",
        "minimum_age",
        "Requires confirmation.",
        careers,
        "D",
      ),
      fact(
        "language",
        "english_requirement",
        "Requires confirmation.",
        careers,
        "D",
      ),
      fact(
        "recruitment",
        "reach_requirement",
        "Requires confirmation.",
        careers,
        "D",
      ),
      fact(
        "recruitment",
        "tattoo_policy",
        "Requires confirmation.",
        careers,
        "D",
      ),
      fact(
        "interview",
        "assessment_stages",
        "Requires confirmation.",
        careers,
        "E",
      ),
      fact(
        "application",
        "regional_eligibility",
        "Requires confirmation for each vacancy.",
        portal,
        "E",
      ),
    ],
  },
];

export const etihadKnowledgeProfileCandidate: Partial<AirlineKnowledgeProfile> =
  {
    id: "profile-etihad-airways",
    airlineId: "etihad_airways",
    reviewStatus: "reviewed",
    publishStatus: "published",
    overview: {
      officialName: "Etihad Airways",
      displayName: "Etihad Airways",
      countryCode: "AE",
      region: "middle_east",
      businessModel: "full_service",
      headquarters: "Abu Dhabi",
      primaryHubs: ["Abu Dhabi"],
      website: careers,
      brandIdentity: {
        value: "Premium travel experience, ambition, world-class airline.",
        status: "verified",
        sourceIds: ["etihad-profile-20260727"],
      },
      servicePhilosophy:
        "Premium travel experience and guest-focused onboard service.",
      customerFocus: {
        value: "Worldwide destinations with premium travel experience.",
        status: "verified",
        sourceIds: ["etihad-profile-20260727"],
      },
      safetyCulture: {
        value: "UAE/GCAA medical and health screening requirements apply.",
        status: "verified",
        sourceIds: ["etihad-profile-20260727"],
      },
    } as AirlineKnowledgeProfile["overview"],
    recruitmentProfile: {
      recruitmentLanguages: ["English"],
      applicationLanguages: ["English"],
      commonRecruitmentStages: ["application"],
      officialCareerPageUrl: portal,
      currentStatus: "unknown",
      checkedAt: "2026-07-27",
      eligibilityRequirements: {
        value: ["Official Etihad Careers recruitment portal."],
        status: "verified",
        sourceIds: ["etihad-recruitment-20260727"],
      },
      languageRequirements: {
        status: "needs_review",
        sourceIds: ["etihad-needs-review-20260727"],
      },
      physicalRequirements: {
        value: ["UAE/GCAA medical and health screening requirements apply."],
        status: "verified",
        sourceIds: ["etihad-recruitment-20260727"],
      },
      selectionSteps: {
        status: "needs_review",
        sourceIds: ["etihad-needs-review-20260727"],
      },
      status: "reviewing",
    },
  };

const faq = (
  id: string,
  question: string,
  answer: string,
  grade: "A" | "D" | "E",
  sourceReference: string,
): AirlineFAQ => ({
  id,
  airlineId: "etihad_airways",
  category: "eligibility",
  question: `지원 준비 참고 FAQ: ${question}`,
  answer,
  sourceGrade: grade,
  sourceReference,
  status: grade === "A" ? "published" : "draft",
  publishStatus: grade === "A" ? "published" : "unpublished",
  createdAt: collectedAt,
  updatedAt: collectedAt,
});
export const etihadFaqDrafts = [
  faq(
    "etihad-faq-apply",
    "Etihad 객실승무원 지원은 어디에서 확인하나요?",
    "공식 Etihad Careers 사이트에서 최신 공고를 확인해야 합니다.",
    "A",
    portal,
  ),
  faq(
    "etihad-faq-airline",
    "Etihad는 어떤 항공사인가요?",
    "제공된 공식 자료에서는 Abu Dhabi 기반의 프리미엄 글로벌 항공사로 안내합니다.",
    "A",
    site,
  ),
  faq(
    "etihad-faq-language",
    "언어 요건은 어디에서 확인하나요?",
    "제공된 보조 출처만으로는 확정하지 않으며 공식 공고에서 확인이 필요합니다.",
    "D",
    careers,
  ),
  faq(
    "etihad-faq-medical",
    "의료 요건이 있나요?",
    "제공된 공식 Careers 자료는 UAE/GCAA medical and health screening requirements를 안내합니다.",
    "A",
    careers,
  ),
  faq(
    "etihad-faq-process",
    "전체 인터뷰 순서는 공개되어 있나요?",
    "제공된 공식 공개 자료만으로는 전체 단계를 확인하기 어려워 추가 확인이 필요합니다.",
    "E",
    careers,
  ),
];
const question = (
  id: string,
  prompt: string,
  type: AirlineInterviewQuestion["questionType"],
  tags: string[],
  experience: string[],
): AirlineInterviewQuestion => ({
  id,
  airlineId: "etihad_airways",
  prompt: `지원 준비용 예상 질문: ${prompt}`,
  questionType: type,
  competencyTags: tags,
  recommendedExperienceTags: experience,
  followUpQuestions: [],
  sourceReferences: [site],
  status: "approved",
  publishStatus: "published",
});
export const etihadInterviewQuestionDrafts = [
  question(
    "etihad-q-motivation",
    "Why Etihad Airways?",
    "motivation",
    ["brand_understanding", "service_motivation", "career_commitment"],
    ["airline_research", "premium_service", "global_ambition"],
  ),
  question(
    "etihad-q-cabin",
    "Why do you want to become cabin crew?",
    "motivation",
    ["guest_care", "resilience", "service_mindset"],
    ["hospitality", "customer_support", "communication"],
  ),
  question(
    "etihad-q-service",
    "Tell us about a time you handled a difficult customer.",
    "service",
    ["empathy", "de_escalation", "problem_solving"],
    ["complaint_handling", "service_recovery", "frontline_service"],
  ),
  question(
    "etihad-q-team",
    "Tell us about a time you worked in a team under pressure.",
    "experience",
    ["collaboration", "prioritization", "communication"],
    ["shift_work", "project_coordination", "crisis_support"],
  ),
  question(
    "etihad-q-safety",
    "What would you do if you noticed a safety risk during service?",
    "safety",
    ["situational_judgment", "procedure_compliance", "calmness"],
    ["risk_reporting", "policy_adherence", "incident_awareness"],
  ),
  question(
    "etihad-q-english",
    "Please introduce yourself in English.",
    "language",
    ["spoken_english", "structure", "clarity"],
    ["self_introduction", "career_summary", "service_example"],
  ),
  question(
    "etihad-q-english-complaint",
    "How would you respond to a customer complaint in English?",
    "language",
    ["service_language", "conflict_resolution", "clarity"],
    ["guest_handling", "apology", "escalation"],
  ),
  question(
    "etihad-q-multicultural",
    "How do you adapt your communication for customers from different cultures?",
    "experience",
    ["cultural_awareness", "adaptability", "respect"],
    ["multicultural_team", "overseas_experience", "diverse_customer_service"],
  ),
];
export const etihadCoachingInsightDrafts: AirlineCoachingInsight[] = [
  {
    id: "etihad-insight-motivation",
    airlineId: "etihad_airways",
    topic: "motivation",
    coachMessage:
      "Etihad 지원동기는 프리미엄 게스트 경험, Abu Dhabi의 글로벌 환경, 호스피탈리티, 안전 인식을 선택한 경험과 연결하도록 안내합니다.",
    goodDirections: [
      "premium guest experience",
      "Abu Dhabi global environment",
      "hospitality",
      "safety awareness",
    ],
    avoidPatterns: ["해외생활만 강조", "서비스 철학 없는 지원"],
    recommendedExperienceTags: [
      "customer_service",
      "teamwork",
      "safety_awareness",
    ],
    sourceReferences: [site, careers, portal],
    status: "approved",
    publishStatus: "published",
  },
];
