import assert from 'node:assert/strict'
import test from 'node:test'
import type { InterviewAttempt } from '@/lib/interview-practice-data'
import type { InterviewSession } from '@/lib/mock-interview-session'
import { interviewQuestions, type InterviewQuestion } from '@/lib/interview-practice-data'
import { buildHomeDrillPlan, buildHomeInterviewRecommendation, buildRecentInterviewGrowth, canUseAirlineContext, findResumableSession, loadHomeInterviewHistory } from './home-dashboard-v2'

const attempt=(id:string,missing:string[]=[],fillers=0,pauses=0):InterviewAttempt=>({id,questionId:'be1',category:'behavioral_experience',createdAt:'2026-08-20T00:00:00.000Z',transcript:'',durationSeconds:30,attemptNumber:1,completed:true,analysis:{} as never,contentAnalysis:{structure:{missingParts:missing},competencies:[]} as never,speechMetrics:{fillers:{totalCount:fillers}} as never,audioMetrics:{pauses:{longCount:pauses}} as never})
const session=(id:string,status:'in_progress'|'completed',attemptIds:string[],date:string):InterviewSession=>({id,mode:'ai_interviewer',questionIds:['be1'],attemptIds,currentQuestionIndex:0,status,startedAt:date,completedAt:status==='completed'?date:undefined})

test('no history or unavailable history keeps generic Quick 5 and excludes unrelated profile fields',()=>{const result=buildHomeInterviewRecommendation({attempts:[],targetAirlineId:'emirates',hasPublishedAirlineContext:false});assert.equal(result.count,5);assert.equal(result.airlineId,undefined);assert.equal('age' in result,false);assert.equal('email' in result,false)})
test('published airline context enables airline-specific recommendation',()=>{assert.equal(buildHomeInterviewRecommendation({attempts:[],targetAirlineId:'emirates',hasPublishedAirlineContext:true}).airlineId,'emirates')})
test('recent repeated weakness drives the recommendation',()=>{const result=buildHomeInterviewRecommendation({attempts:[attempt('a',['Result']),attempt('b',['Result'])],hasPublishedAirlineContext:false});assert.equal(result.topic,'result')})
test('in-progress session is selected before a new recommendation',()=>{assert.equal(findResumableSession([session('old','in_progress',[],'2026-08-19'),session('new','in_progress',[],'2026-08-20')])?.id,'new')})
test('growth needs two completed sessions and compares their attempts',()=>{const one=session('one','completed',['a'],'2026-08-20');assert.deepEqual(buildRecentInterviewGrowth([one],[attempt('a',['Result'],3,2)]),[]);const two=session('two','completed',['b'],'2026-08-19');const growth=buildRecentInterviewGrowth([one,two],[attempt('a',[],1,0),attempt('b',['Result'],4,3)]);assert.deepEqual(growth[0],{label:'긴 쉼',before:'3회',after:'0회'});assert.equal(growth[2].after,'좋아짐')})

test('airline context gate controls the actual home recommendation',()=>{const valid={contextAvailable:true,verified:true,reviewStatus:'approved',publishStatus:'published',aiContextEnabled:true},cases=[{gate:valid,expected:'emirates'},{gate:{...valid,verified:false},expected:undefined},{gate:{...valid,reviewStatus:'reviewing'},expected:undefined},{gate:{...valid,publishStatus:'unpublished'},expected:undefined},{gate:{...valid,aiContextEnabled:false},expected:undefined}];for(const item of cases){const allowed=canUseAirlineContext(item.gate),recommendation=buildHomeInterviewRecommendation({attempts:[],targetAirlineId:'emirates',hasPublishedAirlineContext:allowed});assert.equal(recommendation.airlineId,item.expected)}})

test('mini drill maps weaknesses to real question categories and falls back safely',()=>{const categories=(reason:Parameters<typeof buildHomeDrillPlan>[0])=>buildHomeDrillPlan(reason).selectedQuestionIds.map(id=>interviewQuestions.find(question=>question.id===id)?.category);assert.ok(categories('result').every(value=>value==='behavioral_experience'));assert.ok(categories('action').every(value=>value==='behavioral_experience'));assert.ok(categories('safety').every(value=>value==='safety_and_role_judgment'));assert.ok(categories('customer_service').every(value=>value==='customer_situation'));assert.ok(categories('teamwork').every(value=>value==='behavioral_experience'));assert.ok(categories('motivation').every(value=>value==='introduction_and_motivation'));assert.equal(buildHomeDrillPlan('english').criteria.preferredCapabilities[0],'recruitment_language');assert.equal(buildHomeDrillPlan('unknown').selectedQuestionIds.length,3)})

test('mini drill supplements a short direct-match pool without crashing',()=>{const pool:InterviewQuestion[]=[interviewQuestions.find(question=>question.category==='safety_and_role_judgment')!,...interviewQuestions.filter(question=>question.category!=='safety_and_role_judgment').slice(0,3)];const plan=buildHomeDrillPlan('safety',pool);assert.equal(plan.selectedQuestionIds.length,3);assert.equal(interviewQuestions.find(question=>question.id===plan.selectedQuestionIds[0])?.category,'safety_and_role_judgment')})

test('actual history loader failure returns safe generic home state',()=>{let threw=false;const history=loadHomeInterviewHistory({loadSessions:()=>{threw=true;throw new Error('history read failed')},loadAttempts:()=>[attempt('private')]});const recommendation=buildHomeInterviewRecommendation({attempts:history.attempts,targetAirlineId:'emirates',hasPublishedAirlineContext:history.available&&true});assert.equal(threw,true);assert.equal(history.available,false);assert.deepEqual(history.sessions,[]);assert.deepEqual(history.attempts,[]);assert.equal(recommendation.mode,'ai_interviewer');assert.equal(recommendation.count,5);assert.equal(recommendation.airlineId,undefined);assert.deepEqual(buildRecentInterviewGrowth(history.sessions,history.attempts),[]);assert.equal('email' in recommendation,false);assert.equal('address' in recommendation,false)})
