import {getPracticeQuestionsForAirline} from './airline-knowledge-repository'
import {interviewQuestionById,type InterviewAttempt,type InterviewQuestion} from './interview-practice-data'
import {safeLocalStorageWrite} from './safe-local-storage'

export type InterviewQuestionFavorite={questionId:string;createdAt:string;source?:'question'|'result';airlineId?:string}
export type PracticeQueueReason='manual'|'favorite'|'missing_result'|'missing_action'|'weak_evidence'|'generic_answer'|'safety'|'filler'|'long_pause'|'retake_requested'
export type InterviewPracticeQueueItem={id:string;questionId:string;reason:PracticeQueueReason;status:'open'|'practiced'|'snoozed'|'dismissed';priority:number;createdAt:string;updatedAt:string;sourceAttemptId?:string;airlineId?:string}

const FAVORITES='cabin-interview-question-favorites-v1',QUEUE='cabin-interview-practice-queue-v1'
const eventName='cabin:interview-practice-queue-changed'
const reasons:PracticeQueueReason[]=['manual','favorite','missing_result','missing_action','weak_evidence','generic_answer','safety','filler','long_pause','retake_requested']
const statuses:InterviewPracticeQueueItem['status'][]=['open','practiced','snoozed','dismissed']
const reasonPriority:Record<PracticeQueueReason,number>={safety:1,missing_action:2,missing_result:3,weak_evidence:4,generic_answer:5,filler:5,long_pause:5,retake_requested:5,manual:5,favorite:5}
export const practiceQueueReasonLabel:Record<PracticeQueueReason,string>={manual:'직접 추가',favorite:'즐겨찾기',missing_result:'결과 보완',missing_action:'행동 구체화',weak_evidence:'근거 보완',generic_answer:'구체성 보완',safety:'안전 판단',filler:'필러 표현',long_pause:'긴 쉼',retake_requested:'다시 연습'}

const objectOf=(value:unknown):Record<string,unknown>|null=>typeof value==='object'&&value!==null&&!Array.isArray(value)?value as Record<string,unknown>:null
const textOf=(value:unknown)=>typeof value==='string'&&value.trim()?value.trim():undefined
const validDate=(value:unknown)=>typeof value==='string'&&Number.isFinite(Date.parse(value))?value:''
export const getSafeTimestamp=(value:unknown)=>typeof value==='string'&&Number.isFinite(Date.parse(value))?Date.parse(value):Number.POSITIVE_INFINITY
export function normalizeInterviewQuestionFavorite(raw:unknown):InterviewQuestionFavorite|null{const item=objectOf(raw),questionId=textOf(item?.questionId);if(!item||!questionId)return null;const source=item.source==='question'||item.source==='result'?item.source:undefined;return{questionId,createdAt:validDate(item.createdAt),source,airlineId:textOf(item.airlineId)}}
export function normalizeInterviewPracticeQueueItem(raw:unknown):InterviewPracticeQueueItem|null{const item=objectOf(raw),questionId=textOf(item?.questionId);if(!item||!questionId||!statuses.includes(item.status as InterviewPracticeQueueItem['status']))return null;const reason=reasons.includes(item.reason as PracticeQueueReason)?item.reason as PracticeQueueReason:'manual';const createdAt=validDate(item.createdAt),id=textOf(item.id)??`legacy-${questionId}-${reason}-${createdAt||'undated'}`;return{id,questionId,reason,status:item.status as InterviewPracticeQueueItem['status'],priority:reasonPriority[reason],createdAt,updatedAt:validDate(item.updatedAt)||createdAt,sourceAttemptId:textOf(item.sourceAttemptId),airlineId:textOf(item.airlineId)}}

const rawArray=(key:string):unknown[]=>{if(typeof localStorage==='undefined')return[];try{const value=JSON.parse(localStorage.getItem(key)??'[]');return Array.isArray(value)?value:[]}catch{return[]}}
const favorites=()=>{const seen=new Set<string>(),result:InterviewQuestionFavorite[]=[];for(const raw of rawArray(FAVORITES)){const item=normalizeInterviewQuestionFavorite(raw);if(item&&!seen.has(item.questionId)){seen.add(item.questionId);result.push(item)}}return result}
const queue=()=>{const seen=new Set<string>(),result:InterviewPracticeQueueItem[]=[];for(const raw of rawArray(QUEUE)){const item=normalizeInterviewPracticeQueueItem(raw);if(item&&!seen.has(item.id)){seen.add(item.id);result.push(item)}}return result}
const write=(key:string,value:unknown)=>{const result=safeLocalStorageWrite(key,value,{category:key===FAVORITES?'favorite':'practice_queue'});if(result.ok&&typeof window!=='undefined')window.dispatchEvent(new Event(eventName));return result.ok}
export function isAllowedInterviewQuestion(question:InterviewQuestion,airlineId?:string){if(interviewQuestionById.has(question.id))return true;if(!airlineId||!question.airlineTags?.includes(airlineId))return false;return getPracticeQuestionsForAirline({airlineId,includeGeneralQuestions:false}).some(item=>item.id===question.id)}
export function resolveInterviewQuestion(questionId:string,airlineId?:string){return interviewQuestionById.get(questionId)??(airlineId?getPracticeQuestionsForAirline({airlineId,includeGeneralQuestions:false}).find(item=>item.id===questionId):undefined)}
export function sortPracticeQueue(items:InterviewPracticeQueueItem[]){return [...items].filter(item=>item.status==='open').sort((a,b)=>a.priority-b.priority||getSafeTimestamp(a.createdAt)-getSafeTimestamp(b.createdAt)||a.id.localeCompare(b.id))}
export function recommendedQueueReason(attempt:InterviewAttempt):PracticeQueueReason{if(attempt.category==='safety_and_role_judgment'&&attempt.contentAnalysis?.competencies.some(item=>item.competency.includes('safety')&&item.strength!=='strong'))return'safety';if(attempt.contentAnalysis?.structure.missingParts.some(part=>part.toLowerCase().includes('action')))return'missing_action';if(attempt.contentAnalysis?.structure.missingParts.some(part=>part.toLowerCase().includes('result')))return'missing_result';if(attempt.contentAnalysis?.competencies.some(item=>item.strength==='missing'))return'weak_evidence';if(attempt.contentAnalysis?.answerQuality.genericClaims.length)return'generic_answer';if((attempt.speechMetrics?.fillers.totalCount??0)>=3)return'filler';if((attempt.audioMetrics?.pauses.longCount??0)>=2)return'long_pause';return'retake_requested'}

export const interviewPracticeQueueRepository={
  eventName,listFavorites:favorites,
  isFavorite(questionId:string){return this.listFavorites().some(item=>item.questionId===questionId)},
  toggleFavorite(input:{question:InterviewQuestion;airlineId?:string;source?:InterviewQuestionFavorite['source']},now=new Date()){if(!isAllowedInterviewQuestion(input.question,input.airlineId))return false;const all=this.listFavorites(),exists=all.some(item=>item.questionId===input.question.id),next=exists?all.filter(item=>item.questionId!==input.question.id):[...all,{questionId:input.question.id,airlineId:input.airlineId,source:input.source,createdAt:now.toISOString()}];return write(FAVORITES,next)?!exists:false},
  listQueue:queue,
  listOpen(){return sortPracticeQueue(this.listQueue()).filter(item=>Boolean(resolveInterviewQuestion(item.questionId,item.airlineId)))},
  addQueue(input:{question:InterviewQuestion;reason:PracticeQueueReason;airlineId?:string;sourceAttemptId?:string},now=new Date()){if(!isAllowedInterviewQuestion(input.question,input.airlineId))return null;const all=this.listQueue(),existing=all.find(item=>item.questionId===input.question.id&&item.status==='open');if(existing){const reason=reasonPriority[input.reason]<reasonPriority[existing.reason]?input.reason:existing.reason,updated={...existing,reason,priority:reasonPriority[reason],updatedAt:now.toISOString(),sourceAttemptId:input.sourceAttemptId??existing.sourceAttemptId,airlineId:input.airlineId??existing.airlineId};return write(QUEUE,all.map(item=>item.id===existing.id?updated:item))?updated:null}const item:InterviewPracticeQueueItem={id:crypto.randomUUID(),questionId:input.question.id,reason:input.reason,status:'open',priority:reasonPriority[input.reason],createdAt:now.toISOString(),updatedAt:now.toISOString(),sourceAttemptId:input.sourceAttemptId,airlineId:input.airlineId};return write(QUEUE,[...all,item])?item:null},
  markPracticed(id:string,now=new Date()){const all=this.listQueue(),item=all.find(value=>value.id===id);return Boolean(item&&write(QUEUE,all.map(value=>value.id===id?{...value,status:'practiced' as const,updatedAt:now.toISOString()}:value)))},
  dismiss(id:string,now=new Date()){const all=this.listQueue();return write(QUEUE,all.map(value=>value.id===id?{...value,status:'dismissed' as const,updatedAt:now.toISOString()}:value))},
}
