import assert from 'node:assert/strict'
import test from 'node:test'
import type { AnswerQualityDimension, AnswerQualityFinding, AnswerQualityStatus } from './answer-quality-rubric'
import { adaptiveWeaknessesAsRepeated, buildWeaknessEvidence, deriveAdaptiveWeaknesses, mergeAdaptiveTrainingPriorities, recommendQuestionForWeakness, rubricFindingToWeaknessEvidence, type AdaptiveEvidenceInput, type AdaptiveWeakness, type WeaknessEvidence } from './learning-analytics-adaptive'
import type { InterviewQuestion } from './interview-practice-data'

const now=new Date('2026-08-31T12:00:00.000Z')
const finding=(dimension:AnswerQualityDimension,status:AnswerQualityStatus):AnswerQualityFinding=>({dimension,status,evidence:status==='strong'||status==='adequate'?['실제 답변 근거']:[],feedback:`${dimension} ${status}`,confidence:'high'})
const input=(id:string,dimension:AnswerQualityDimension,status:AnswerQualityStatus,daysAgo=0,familyId=id,sourceType:AdaptiveEvidenceInput['sourceType']='interview_attempt'):AdaptiveEvidenceInput=>({sourceType,sourceId:id,familyId,occurredAt:new Date(now.getTime()-daysAgo*86400000).toISOString(),rubric:{version:1,evaluated:true,context:sourceType==='application_answer'?'application':sourceType==='self_introduction'?'self_introduction':'interview',findings:[finding(dimension,status)],strengths:[],improvements:[],followUpCandidates:[]}})
const evidence=(key:WeaknessEvidence['key'],id:string,signal:WeaknessEvidence['signal'],daysAgo=0,familyId=id):WeaknessEvidence=>({key,sourceType:'interview_attempt',sourceId:id,familyId,occurredAt:new Date(now.getTime()-daysAgo*86400000).toISOString(),signal,severity:key==='safety_priority_unclear'?'high':'low',provenance:'rubric',summary:'실제 기록 기반 신호'})
const weakness=(key:AdaptiveWeakness['key'],priority=80,state:AdaptiveWeakness['state']='emerging'):AdaptiveWeakness=>({key,title:key,relatedCapability:key==='safety_priority_unclear'?'safety_and_role_judgment':'interview_communication',state,trend:state==='improving'?'improving':'stable',confidence:'medium',occurrenceCount:2,distinctSourceCount:2,latestObservedAt:now.toISOString(),priority,evidence:[evidence(key,'a','needs_improvement')],explanation:'최근 2개 서로 다른 연습 묶음에서 보완 신호가 확인됐습니다.',recommendedAction:'다시 연습'})

test('one missing action is observed, never persistent',()=>assert.equal(deriveAdaptiveWeaknesses(buildWeaknessEvidence([input('a','action','needs_improvement')]),now)[0].state,'observed'))
test('two distinct missing-action attempts become emerging',()=>assert.equal(deriveAdaptiveWeaknesses(buildWeaknessEvidence([input('a','action','needs_improvement'),input('b','action','needs_improvement')]),now)[0].state,'emerging'))
test('three distinct attempts become persistent',()=>assert.equal(deriveAdaptiveWeaknesses(buildWeaknessEvidence([input('a','action','needs_improvement'),input('b','action','needs_improvement'),input('c','action','needs_improvement')]),now)[0].state,'persistent'))
test('retake adequate action changes trend to improving',()=>assert.equal(deriveAdaptiveWeaknesses(buildWeaknessEvidence([input('a','action','needs_improvement',2,'family'),input('b','action','adequate',0,'family')]),now)[0].state,'improving'))
test('two later positive results make a resolved candidate while preserving history',()=>{const item=deriveAdaptiveWeaknesses(buildWeaknessEvidence([input('a','action','needs_improvement',3),input('b','action','adequate',2),input('c','action','strong',1)]),now)[0];assert.equal(item.state,'resolved');assert.equal(item.evidence.length,3)})
test('a new regression reactivates a resolved pattern',()=>{const item=deriveAdaptiveWeaknesses([evidence('missing_action','a','needs_improvement',4),evidence('missing_action','b','improved',3),evidence('missing_action','c','improved',2),evidence('missing_action','d','needs_improvement',0)],now)[0];assert.equal(item.state,'emerging');assert.equal(item.trend,'worsening')})
test('repeated safety evidence outranks general content',()=>{const items=deriveAdaptiveWeaknesses([evidence('safety_priority_unclear','s1','needs_improvement'),evidence('safety_priority_unclear','s2','needs_improvement'),evidence('missing_action','a1','needs_improvement'),evidence('missing_action','a2','needs_improvement')],now);assert.equal(items[0].key,'safety_priority_unclear')})
test('not applicable never creates evidence',()=>assert.equal(rubricFindingToWeaknessEvidence(finding('result','not_applicable'),{sourceType:'interview_attempt',sourceId:'a',occurredAt:now.toISOString()}),null))
test('strong and adequate create positive signals, not negative evidence',()=>{const rows=buildWeaknessEvidence([input('a','action','strong'),input('b','result','adequate')]);assert.ok(rows.every(item=>item.signal==='improved'));assert.equal(deriveAdaptiveWeaknesses(rows,now).length,0)})
test('same attempt family is counted once',()=>{const item=deriveAdaptiveWeaknesses([evidence('missing_action','a','needs_improvement',2,'family'),evidence('missing_action','b','needs_improvement',1,'family')],now)[0];assert.equal(item.occurrenceCount,1)})
test('old evidence receives less priority than recent evidence of same kind',()=>{const recent=deriveAdaptiveWeaknesses([evidence('missing_action','a','needs_improvement',1)],now)[0],old=deriveAdaptiveWeaknesses([evidence('missing_action','b','needs_improvement',40)],now)[0];assert.ok(recent.priority>old.priority)})
test('only top three active weaknesses are exposed to the weekly UI',()=>{const rows=adaptiveWeaknessesAsRepeated([weakness('missing_action',80),weakness('missing_result',70),weakness('weak_evidence',60),weakness('weak_structure',50)]);assert.equal(rows.length,3)})
test('practice recommendation returns a candidate without mutating a queue',()=>{const question:InterviewQuestion={id:'q',category:'behavioral_experience',prompt:'q',shortTitle:'q',difficulty:'beginner',targetCapabilities:['interview_communication'],evaluationRubric:{keys:[],guidance:''},localeKey:'q'};const result=recommendQuestionForWeakness(weakness('missing_action'),{questions:[question],openQuestionIds:[]});assert.equal(result?.reason,'missing_action');assert.equal(result?.question.id,'q')})
test('recent questions are skipped when another valid question exists',()=>{const questions=['q1','q2'].map(id=>({id,category:'behavioral_experience',prompt:id,shortTitle:id,difficulty:'beginner',targetCapabilities:['interview_communication'],evaluationRubric:{keys:[],guidance:''},localeKey:id} as InterviewQuestion));assert.equal(recommendQuestionForWeakness(weakness('missing_action'),{questions,recentQuestionIds:['q1']})?.question.id,'q2')})
test('adaptive priorities are limited to three and retain weakness explanation',()=>{const result=mergeAdaptiveTrainingPriorities([],[weakness('missing_action',80),weakness('missing_result',70),weakness('weak_evidence',60),weakness('weak_structure',50)]);assert.equal(result.length,3);assert.match(result[0].reason,/최근 2개/)})
test('improving weakness has lighter priority than an active peer',()=>{const active=weakness('missing_action',80),improving=weakness('missing_result',45,'improving');assert.ok(active.priority>improving.priority)})
test('legacy attempt signals remain supported without rubric',()=>{const rows=buildWeaknessEvidence([{sourceType:'interview_attempt',sourceId:'legacy',occurredAt:now.toISOString(),legacyKeys:['action_specificity']}]);assert.equal(rows[0].key,'missing_action');assert.equal(rows[0].provenance,'legacy')})
test('self introduction rubric contributes only applicable content dimensions',()=>{const rows=buildWeaknessEvidence([input('self','specificity','needs_improvement',0,'self','self_introduction')]);assert.equal(rows[0].sourceType,'self_introduction');assert.equal(rows[0].key,'weak_specificity')})
test('application rubric can contribute airline connection evidence',()=>{const rows=buildWeaknessEvidence([input('app','airlineFit','insufficient_evidence',0,'app','application_answer')]);assert.equal(rows[0].sourceType,'application_answer');assert.equal(rows[0].key,'weak_airline_connection')})
test('speech and content signals share one deterministic priority list',()=>{const rows=buildWeaknessEvidence([{...input('a','action','needs_improvement'),fillerCount:4,longPauseCount:2}]);const keys=deriveAdaptiveWeaknesses(rows,now).map(item=>item.key);assert.deepEqual(keys.slice(0,3),['missing_action','filler','long_pause'])})
test('adaptive weakness objects contain no aggregate or hiring probability',()=>{const output=JSON.stringify(deriveAdaptiveWeaknesses([evidence('missing_action','a','needs_improvement')],now));assert.doesNotMatch(output,/overallScore|passProbability|hireProbability|합격 확률|채용 확률/)})
