import type { CapabilityKey } from '@/lib/interview-practice-data'
import type { TrainingPriority, WeeklyRoutineDay } from '@/lib/learning-analytics-service'
import { safeLocalStorageWrite } from '@/lib/safe-local-storage'

export type ConfirmedWeeklyPlan={weekStart:string;days:WeeklyRoutineDay[];confirmedAt:string;updatedAt:string}
export type TrainingPrioritySnapshot={weekStart:string;priorities:TrainingPriority[];generatedAt:string;basedOnActivityIds:string[]}
export type RoutineCompletionSnapshot={id:string;taskId:string;title:string;minutes:number;occurredAt:string;relatedCapability:CapabilityKey;source?:'manual_routine'|'weekly_plan';weekStart?:string;sourceCompletionId?:string}
export type PlanEdit={id:string;weekStart:string;action:'delete_task'|'replace_task'|'move_task'|'rest_day'|'focus_day'|'confirm';occurredAt:string;detail:string}
export type LearningAnalyticsStore={schemaVersion:1;confirmedWeeklyPlans:ConfirmedWeeklyPlan[];priorityHistory:TrainingPrioritySnapshot[];reportViewHistory:string[];routineCompletions:RoutineCompletionSnapshot[];planEditHistory:PlanEdit[];updatedAt:string}
const KEY='cabin-learning-analytics',VERSION=1,now=()=>new Date().toISOString()
const empty=():LearningAnalyticsStore=>({schemaVersion:VERSION,confirmedWeeklyPlans:[],priorityHistory:[],reportViewHistory:[],routineCompletions:[],planEditHistory:[],updatedAt:now()})
const validDate=(value:unknown):value is string=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)
function inferredWeekStart(value:string){const date=new Date(`${value}T12:00:00`);if(Number.isNaN(date.getTime()))return null;const day=date.getDay()||7;date.setDate(date.getDate()-day+1);return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function normalizePlan(value:unknown):ConfirmedWeeklyPlan|null{if(!value||typeof value!=='object')return null;const row=value as Partial<ConfirmedWeeklyPlan>,days=Array.isArray(row.days)?row.days.filter(day=>day&&validDate(day.date)&&Array.isArray(day.tasks)).map(day=>({...day,tasks:day.tasks.filter(task=>task&&typeof task.id==='string')})):[],weekStart=validDate(row.weekStart)?row.weekStart:days[0]?inferredWeekStart(days[0].date):null;if(!weekStart)return null;const timestamp=typeof row.confirmedAt==='string'?row.confirmedAt:now();return{weekStart,days,confirmedAt:timestamp,updatedAt:typeof row.updatedAt==='string'?row.updatedAt:timestamp}}
function normalizePlans(values:unknown[]){const seen=new Set<string>();return values.map(normalizePlan).filter((plan:ConfirmedWeeklyPlan|null):plan is ConfirmedWeeklyPlan=>{if(!plan||seen.has(plan.weekStart))return false;seen.add(plan.weekStart);return true}).slice(0,52)}
function read(){if(typeof window==='undefined')return empty();try{const raw=JSON.parse(localStorage.getItem(KEY)??'{}');return{schemaVersion:VERSION,confirmedWeeklyPlans:Array.isArray(raw.confirmedWeeklyPlans)?normalizePlans(raw.confirmedWeeklyPlans):[],priorityHistory:Array.isArray(raw.priorityHistory)?raw.priorityHistory.slice(0,52):[],reportViewHistory:Array.isArray(raw.reportViewHistory)?raw.reportViewHistory.slice(0,200):[],routineCompletions:Array.isArray(raw.routineCompletions)?raw.routineCompletions.filter((x:RoutineCompletionSnapshot)=>x&&typeof x.id==='string'&&typeof x.occurredAt==='string').slice(0,1000):[],planEditHistory:Array.isArray(raw.planEditHistory)?raw.planEditHistory.slice(0,500):[],updatedAt:typeof raw.updatedAt==='string'?raw.updatedAt:now()} as LearningAnalyticsStore}catch{return empty()}}
function write(s:LearningAnalyticsStore){const next:LearningAnalyticsStore={...s,schemaVersion:1,updatedAt:now()};if(typeof window!=='undefined'){const result=safeLocalStorageWrite(KEY,next,{category:'learning'});if(result.ok)window.dispatchEvent(new Event('cabin:learning-local-changed'))}return next}
export const learningAnalyticsRepository={
  load:read,recover(){return write(read())},
  markReportViewed(weekStart:string){const s=read();s.reportViewHistory=Array.from(new Set([`${weekStart}:${now()}`,...s.reportViewHistory])).slice(0,200);return write(s)},
  recordRoutine(task:{id:string;name:string;minutes:number},relatedCapability:CapabilityKey='application_readiness'){const s=read(),date=now(),id=`routine:${task.id}:${date.slice(0,10)}`;if(!s.routineCompletions.some(x=>x.id===id))s.routineCompletions.unshift({id,taskId:task.id,title:task.name,minutes:task.minutes,occurredAt:date,relatedCapability});return write(s)},
  recordWeeklyTask(task:{id:string;name:string;minutes:number;weekStart?:string;sourceCompletionId?:string},relatedCapability:CapabilityKey='application_readiness'){const s=read(),date=now(),id=`weekly:${task.id}`;if(s.routineCompletions.some(x=>x.id===id||x.taskId===task.id&&x.source==='weekly_plan'))return s;s.routineCompletions.unshift({id,taskId:task.id,title:task.name,minutes:task.minutes,occurredAt:date,relatedCapability,source:'weekly_plan',weekStart:task.weekStart,sourceCompletionId:task.sourceCompletionId});return write(s)},
  isWeeklyTaskCompleted(taskId?:string){return Boolean(taskId&&read().routineCompletions.some(x=>x.taskId===taskId&&x.source==='weekly_plan'))},
  removeRoutine(taskId:string,date=new Date().toISOString().slice(0,10)){const s=read();s.routineCompletions=s.routineCompletions.filter(x=>!(x.taskId===taskId&&x.occurredAt.slice(0,10)===date));return write(s)},
  savePrioritySnapshot(snapshot:TrainingPrioritySnapshot){const s=read();s.priorityHistory=[snapshot,...s.priorityHistory.filter(x=>x.weekStart!==snapshot.weekStart)].slice(0,52);return write(s)},
  confirmPlan(plan:ConfirmedWeeklyPlan){const s=read();s.confirmedWeeklyPlans=[plan,...s.confirmedWeeklyPlans.filter(x=>x.weekStart!==plan.weekStart)].slice(0,52);s.planEditHistory.unshift({id:`edit-${Date.now()}`,weekStart:plan.weekStart,action:'confirm',occurredAt:now(),detail:'사용자가 주간 계획을 확정함'});return write(s)},
  recordPlanEdit(edit:Omit<PlanEdit,'id'|'occurredAt'>){const s=read();s.planEditHistory.unshift({...edit,id:`edit-${Date.now()}`,occurredAt:now()});return write(s)}
}
