import type { AirlineFAQ, AirlineKnowledgeProfile } from "./airline-knowledge-repository";
import type { AirlineResearchRecord } from "./airline-research-repository";
import type { AirlineCoachingInsight, AirlineInterviewQuestion } from "./airline-knowledge-transformer";

const careers = "https://www.lufthansagroup.careers/en/";
const collectedAt = "2026-07-29T00:00:00.000Z";
const fact = (category: AirlineResearchRecord["extractedFacts"][number]["category"], key: string, value: string, grade: "A" | "C" | "E") => ({ category, key, value, sourceUrl: careers, sourceGrade: grade, verified: false });

export const lufthansaResearchRecords: AirlineResearchRecord[] = [
  { id: "lufthansa-profile-20260729", airlineId: "lufthansa", sourceTitle: "Lufthansa supplied profile research", sourceUrl: careers, sourceType: "Company Profile", collectedBy: "manual", collectedAt, sourceDate: "2026-07-29", sourceGrade: "A", confidence: "medium", status: "collected", rawSummary: "Supplied profile candidates for Lufthansa only.", rawText: "Lufthansa; safety culture; precision; reliability; multicultural teamwork; professional service.", extractedFacts: [fact("profile", "official_name", "Lufthansa", "A"), fact("service", "professional_service", "Professional service is a supplied preparation candidate.", "A"), fact("safety", "safety_culture", "Safety culture is a supplied preparation candidate.", "A"), fact("application", "profile_scope", "Further corporate profile details require review.", "E")] },
  { id: "lufthansa-recruitment-20260729", airlineId: "lufthansa", sourceTitle: "Lufthansa supplied recruitment research", sourceUrl: careers, sourceType: "Recruitment Data", collectedBy: "manual", collectedAt, sourceDate: "2026-07-29", sourceGrade: "A", confidence: "medium", status: "collected", rawSummary: "Recruitment flow candidates are retained without citizenship or language inference.", rawText: "Candidates: online application, first screening, applicant day and career portal. EU citizenship/work permit, German, English, education, age, physical, grooming and base conditions require review.", extractedFacts: [fact("recruitment", "online_application", "Online application candidate.", "A"), fact("recruitment", "first_screening", "First screening candidate.", "A"), fact("recruitment", "applicant_day", "Applicant day candidate.", "A"), fact("recruitment", "career_portal", "Career portal candidate.", "A"), fact("recruitment", "eu_work_permit", "EU citizenship or work permit requires confirmation.", "E"), fact("language", "german", "German requirement must not be inferred.", "E"), fact("language", "english", "English requirement requires confirmation.", "E"), fact("recruitment", "base_specific", "Base-specific requirements require confirmation.", "E")] },
  { id: "lufthansa-preparation-20260729", airlineId: "lufthansa", sourceTitle: "Lufthansa supplied preparation candidates", sourceUrl: careers, sourceType: "Interview Preparation and Application Coaching", collectedBy: "manual", collectedAt, sourceDate: "2026-07-29", sourceGrade: "C", confidence: "medium", status: "collected", rawSummary: "Preparation directions only; not actual interview questions.", rawText: "Directions: safety culture, precision, reliability, multicultural teamwork and professional service. Avoid claiming German is mandatory, romanticizing Europe, or omitting safety.", extractedFacts: [fact("application", "coaching_directions", "Connect safety, precision, reliability, teamwork and professional service to selected experience.", "C"), fact("application", "avoid_patterns", "Do not infer German as mandatory or EU work eligibility, and do not omit safety.", "C")] },
];

export const lufthansaKnowledgeProfileCandidate: Partial<AirlineKnowledgeProfile> = { id: "profile-lufthansa", airlineId: "lufthansa", reviewStatus: "reviewed", publishStatus: "unpublished", overview: { officialName: "Lufthansa", displayName: "Lufthansa", countryCode: "DE", region: "europe", businessModel: "full_service", website: careers, brandIdentity: { value: "Precision and reliability are review candidates.", status: "needs_review", sourceIds: ["lufthansa-profile-20260729"] }, servicePhilosophy: "Professional service requires review.", customerFocus: { value: "Multicultural teamwork and professional service require review.", status: "needs_review", sourceIds: ["lufthansa-profile-20260729"] }, safetyCulture: { value: "Safety culture requires review.", status: "needs_review", sourceIds: ["lufthansa-profile-20260729"] } } as AirlineKnowledgeProfile["overview"] };
const faq=(id:string,q:string,a:string):AirlineFAQ=>({id,airlineId:"lufthansa",category:"eligibility",question:`지원 준비 참고 FAQ: ${q}`,answer:a,sourceGrade:"A",sourceReference:careers,status:"draft",publishStatus:"unpublished",createdAt:collectedAt,updatedAt:collectedAt});
export const lufthansaFaqDrafts=[faq("lufthansa-faq-1","Where should I check recruitment information?","Confirm the current official Lufthansa careers portal."),faq("lufthansa-faq-2","Is German required?","Do not assume a German requirement without the applicable posting."),faq("lufthansa-faq-3","Is EU work eligibility required?","Citizenship and work-permit conditions require confirmation."),faq("lufthansa-faq-4","What stages are listed?","Online application, screening and applicant-day wording requires review."),faq("lufthansa-faq-5","What should I prepare?","Prepare evidence of safety, precision, reliability and teamwork.")];
const q=(id:string,p:string,t:AirlineInterviewQuestion["questionType"],c:string[],e:string[]):AirlineInterviewQuestion=>({id,airlineId:"lufthansa",prompt:`지원 준비용 예상 질문: ${p}`,questionType:t,competencyTags:c,recommendedExperienceTags:e,followUpQuestions:[],sourceReferences:[careers],status:"draft",publishStatus:"unpublished"});
export const lufthansaInterviewQuestionDrafts=[q("lufthansa-q-1","Why are you interested in Lufthansa?","motivation",["brand_understanding","reliability"],["airline_research","professional_service"]),q("lufthansa-q-2","Why do you want to become cabin crew?","motivation",["service_mindset","resilience"],["customer_service","communication"]),q("lufthansa-q-3","Tell us about a time you delivered precise service.","service",["precision","customer_focus"],["customer_service","detail_orientation"]),q("lufthansa-q-4","Tell us about working reliably in a team.","experience",["teamwork","reliability"],["teamwork","shift_work"]),q("lufthansa-q-5","What would you do if you noticed a safety concern?","safety",["judgment","procedure_compliance"],["risk_reporting","safety_awareness"]),q("lufthansa-q-6","How do you balance professional service and safety?","safety",["prioritization","calmness"],["rule_following","service_recovery"]),q("lufthansa-q-7","How do you communicate in a multicultural team?","language",["cultural_awareness","adaptability"],["multicultural_team","communication"]),q("lufthansa-q-8","How do you maintain precision under pressure?","experience",["focus","resilience"],["high_pressure","detail_orientation"]),q("lufthansa-q-9","What does reliability mean in cabin service?","service",["accountability","consistency"],["professional_service","customer_trust"])];
export const lufthansaCoachingInsightDrafts:AirlineCoachingInsight[]=[{id:"lufthansa-insight-motivation",airlineId:"lufthansa",topic:"motivation",coachMessage:"Lufthansa 지원 방향은 안전 문화, 정확성, 신뢰성, 다문화 팀워크와 전문 서비스를 본인 경험과 연결하는 방식으로 검토해 보세요.",goodDirections:["safety culture","precision","reliability","multicultural teamwork","professional service"],avoidPatterns:["독일어 필수라고 단정","유럽 근무 환상만 강조","안전 제외"],recommendedExperienceTags:["safety_awareness","detail_orientation","teamwork","multicultural_experience","professional_service"],sourceReferences:[careers],status:"draft",publishStatus:"unpublished"}];
