import { interviewQuestions, type InterviewAttempt } from './interview-practice-data'
import { getPracticeQuestionsForAirline } from './airline-knowledge-repository'
import type { WeeklyTaskContext } from './weekly-task-completion'

export type InterviewSessionMode='general'|'airline_specific'|'english'|'safety'|'ai_interviewer'|'custom'
export type InterviewSessionAnalysis={overallSummary:string;strengths:string[];improvements:string[];competencySummary:Array<{competency:string;strength:'strong'|'partial'|'missing'}>;speechSummary:string;audioSummary:string;pronunciationSummary?:string;contentSummary:string;nextPractice:string[];followUpSummary?:string}
export type InterviewSession={id:string;mode:InterviewSessionMode;airlineId?:string;questionIds:string[];attemptIds:string[];currentQuestionIndex:number;status:'created'|'in_progress'|'completed';startedAt:string;completedAt?:string;sessionAnalysis?:InterviewSessionAnalysis;weeklyTaskContext?:WeeklyTaskContext}
const key='cabin-mock-interview-sessions-v1'
export const loadInterviewSessions=():InterviewSession[]=>{if(typeof window==='undefined')return[];try{const value=JSON.parse(localStorage.getItem(key)??'[]');return Array.isArray(value)?value:[]}catch{return[]}}
export const saveInterviewSession=(session:InterviewSession)=>{if(typeof window!=='undefined')localStorage.setItem(key,JSON.stringify([session,...loadInterviewSessions().filter(item=>item.id!==session.id)].slice(0,20)))}
export function selectSessionQuestions(input:{mode:InterviewSessionMode;airlineId?:string;count:3|5|8|12}){let list=interviewQuestions.filter(question=>input.mode==='safety'?question.category==='safety_and_role_judgment':input.mode==='english'?question.targetCapabilities.includes('recruitment_language'):true);if((input.mode==='airline_specific'||input.mode==='ai_interviewer')&&input.airlineId){const airline=getPracticeQuestionsForAirline({airlineId:input.airlineId,includeGeneralQuestions:false});list=[...airline,...list.filter(question=>!airline.some(item=>item.id===question.id))]}return list.slice(0,input.count)}
export function createInterviewSession(input:{mode:InterviewSessionMode;airlineId?:string;count:3|5|8|12;questionIds?:string[]}){const selected=input.questionIds?.map(id=>interviewQuestions.find(question=>question.id===id)).filter(question=>question!==undefined)??selectSessionQuestions(input),questions=selected.length?selected:selectSessionQuestions(input),session:InterviewSession={id:`session-${Date.now()}`,mode:input.mode,airlineId:input.airlineId,questionIds:questions.slice(0,input.count).map(question=>question.id),attemptIds:[],currentQuestionIndex:0,status:'in_progress',startedAt:new Date().toISOString()};saveInterviewSession(session);return session}
export function followUpForAttempt(attempt:InterviewAttempt){const content=attempt.contentAnalysis;if(!content)return undefined;if(content.structure.missingParts.includes('Result'))return '결과나 배운 점을 한 문장으로 덧붙여 설명해 주세요.';if(content.answerQuality.genericClaims.length)return '구체적으로 어떤 행동을 했는지 설명해 주세요.';if(content.competencies.some(item=>item.strength==='missing'))return '이 상황에서 본인이 직접 한 행동은 무엇이었나요?';return undefined}
const label=(value:string)=>({application_readiness:'지원 동기',interview_communication:'답변 전달',customer_situation_handling:'고객 대응',safety_and_role_judgment:'안전 판단',recruitment_language:'언어 전달',airline_and_role_understanding:'직무 이해'}[value]??value)
export function analyzeInterviewSession(session:InterviewSession,attempts:InterviewAttempt[]):InterviewSessionAnalysis{const rows=attempts.filter(attempt=>session.attemptIds.includes(attempt.id)),competencies=rows.flatMap(row=>row.contentAnalysis?.competencies??[]);const competencySummary=Array.from(new Set(competencies.map(item=>item.competency))).map(competency=>{const matches=competencies.filter(item=>item.competency===competency),strong=matches.filter(item=>item.strength==='strong').length,partial=matches.filter(item=>item.strength==='partial').length;return{competency,strength:strong>partial&&strong>0?'strong':partial>0?'partial':'missing'} as const});const strengths=Array.from(new Set(rows.flatMap(row=>row.contentAnalysis?.strongPoints??[]))).slice(0,3),improvements=Array.from(new Set(rows.flatMap(row=>row.contentAnalysis?.improvementPoints??[]).sort((a,b)=>a.priority-b.priority).map(item=>item.message))).slice(0,3),missingResult=rows.filter(row=>row.contentAnalysis?.structure.missingParts.includes('Result')).length,filler=rows.reduce((sum,row)=>sum+(row.speechMetrics?.fillers?.totalCount??0),0),pauses=rows.reduce((sum,row)=>sum+(row.audioMetrics?.pauses?.longCount??0),0),wpm=rows.map(row=>row.speechMetrics?.speechRate?.voicedWpm??row.audioMetrics?.speech?.wordsPerMinute).filter((value):value is number=>typeof value==='number'),actualPronunciation=rows.filter(row=>row.pronunciationAnalysis?.status==='success'||row.pronunciationAnalysis?.status==='partial'),followUps=rows.filter(row=>row.isFollowUp);const primaryStrength=strengths[0]??(competencySummary.find(item=>item.strength==='strong')?`${label(competencySummary.find(item=>item.strength==='strong')!.competency)} 근거가 답변에 드러났습니다.`:'답변의 핵심 방향을 유지한 점이 확인됩니다.'),primaryImprovement=improvements[0]??(missingResult?'결과 또는 배운 점을 한 문장으로 보완해 보세요.':'각 답변에 본인이 한 행동을 한 문장 더 붙여 보세요.');return{overallSummary:`${primaryStrength} ${primaryImprovement}`,strengths,improvements,competencySummary,speechSummary:wpm.length?`평균 발화 속도 ${Math.round(wpm.reduce((sum,value)=>sum+value,0)/wpm.length)} WPM · 필러 ${filler}회 · 긴 쉼 ${pauses}회`:`필러 ${filler}회 · 긴 쉼 ${pauses}회`,audioSummary:rows.some(row=>row.audioMetrics)?`오디오 분석 ${rows.filter(row=>row.audioMetrics).length}개 답변에 반영`:'오디오 분석 정보가 없습니다.',pronunciationSummary:actualPronunciation.length?`정밀 발음 분석 ${actualPronunciation.length}개 답변에 반영`:undefined,contentSummary:missingResult?`${missingResult}개 답변에서 결과 또는 배운 점 보완이 추천됩니다.`:'가능한 답변에서 구조 요소를 확인했습니다.',followUpSummary:followUps.length?`추가 질문 ${followUps.length}개에서 행동·결과·판단 근거를 더 구체적으로 확인했습니다.`:undefined,nextPractice:[...improvements.map(item=>`보완: ${item}`),...competencySummary.filter(item=>item.strength!=='strong').map(item=>`${label(item.competency)} 질문 다시 연습`)].slice(0,3)}}
export function completeInterviewSessionAttempt(session:InterviewSession,attemptId:string,advance=true){const attemptIds=session.attemptIds.includes(attemptId)?session.attemptIds:[...session.attemptIds,attemptId],nextQuestionIndex=advance?session.currentQuestionIndex+1:session.currentQuestionIndex,completed=advance&&nextQuestionIndex>=session.questionIds.length,currentQuestionIndex=completed?Math.max(0,session.questionIds.length-1):nextQuestionIndex;return {...session,attemptIds,currentQuestionIndex,status:completed?'completed' as const:'in_progress' as const,completedAt:completed?new Date().toISOString():undefined}}
