import { interviewQuestions, type InterviewAttempt, type InterviewQuestion } from './interview-practice-data'
export type InterviewSessionMode='general'|'airline_specific'|'english'|'safety'|'custom'
export type InterviewSession={id:string;mode:InterviewSessionMode;airlineId?:string;questionIds:string[];attemptIds:string[];currentQuestionIndex:number;status:'created'|'in_progress'|'completed';startedAt:string;completedAt?:string;sessionAnalysis?:InterviewSessionAnalysis}
export type InterviewSessionAnalysis={overallSummary:string;strengths:string[];improvements:string[];competencySummary:Array<{competency:string;strength:'strong'|'partial'|'missing'}>;speechSummary:string;contentSummary:string;nextPractice:string[]}
const key='cabin-mock-interview-sessions-v1'
export const loadInterviewSessions=():InterviewSession[]=>{try{return JSON.parse(localStorage.getItem(key)??'[]')}catch{return[]}}
export const saveInterviewSession=(session:InterviewSession)=>localStorage.setItem(key,JSON.stringify([session,...loadInterviewSessions().filter(item=>item.id!==session.id)].slice(0,20)))
export function selectSessionQuestions(input:{mode:InterviewSessionMode;airlineId?:string;count:5|8|12}){let list=interviewQuestions.filter(question=>input.mode==='safety'?question.category==='safety_and_role_judgment':input.mode==='english'?question.targetCapabilities.includes('recruitment_language'):true);const airlineId=input.airlineId;if(input.mode==='airline_specific'&&airlineId)list=[...list.filter(question=>question.airlineTags?.includes(airlineId)),...list.filter(question=>!question.airlineTags?.length)];return list.slice(0,input.count)}
export function createInterviewSession(input:{mode:InterviewSessionMode;airlineId?:string;count:5|8|12}){const questions=selectSessionQuestions(input),session:InterviewSession={id:`session-${Date.now()}`,mode:input.mode,airlineId:input.airlineId,questionIds:questions.map(question=>question.id),attemptIds:[],currentQuestionIndex:0,status:'in_progress',startedAt:new Date().toISOString()};saveInterviewSession(session);return session}
export function followUpForAttempt(attempt:InterviewAttempt){const content=attempt.contentAnalysis;if(!content)return undefined;if(content.structure.missingParts.includes('Result'))return '결과나 배운 점을 한 문장으로 덧붙여 설명해 주세요.';if(content.answerQuality.genericClaims.length)return '구체적으로 어떤 행동을 했는지 설명해 주세요.';if(content.competencies.some(item=>item.strength==='missing'))return '이 상황에서 본인이 직접 한 행동은 무엇이었나요?';return undefined}
export function analyzeInterviewSession(session:InterviewSession,attempts:InterviewAttempt[]):InterviewSessionAnalysis{const rows=attempts.filter(attempt=>session.attemptIds.includes(attempt.id));const competencies=rows.flatMap(row=>row.contentAnalysis?.competencies??[]);const summary=Array.from(new Set(competencies.map(item=>item.competency))).map(competency=>{const matches=competencies.filter(item=>item.competency===competency);return{competency,strength:matches.some(item=>item.strength==='strong')?'strong':matches.some(item=>item.strength==='partial')?'partial':'missing'} as const});const filler=rows.reduce((sum,row)=>sum+(row.speechMetrics?.fillers.totalCount??0),0),pauses=rows.reduce((sum,row)=>sum+(row.audioMetrics?.pauses.longCount??0),0);return{overallSummary:`${rows.length}개 답변을 바탕으로 다음 연습 방향을 정리했습니다.`,strengths:summary.filter(item=>item.strength==='strong').map(item=>`${item.competency} 근거가 답변에 드러났습니다.`).slice(0,3),improvements:summary.filter(item=>item.strength!=='strong').map(item=>`${item.competency}의 직접 근거를 한 문장 더 제시해 보세요.`).slice(0,3),competencySummary:summary,speechSummary:`필러 ${filler}회 · 긴 쉼 ${pauses}회`,contentSummary:rows.some(row=>row.contentAnalysis?.structure.missingParts.includes('Result'))?'일부 답변에서 결과 또는 배운 점을 보완해 보세요.':'답변 구조의 핵심 요소가 확인됩니다.',nextPractice:summary.filter(item=>item.strength!=='strong').map(item=>`${item.competency} 질문 다시 연습`)} }
