import assert from 'node:assert/strict'
import test from 'node:test'
import type { AnswerQualityDimension } from './answer-quality-rubric'
import { resolveMockReportActions } from './mock-report-actions'
import type { InterviewAttempt, InterviewQuestion } from './interview-practice-data'
import type { InterviewSession } from './mock-interview-session'

const question=(id:string):InterviewQuestion=>({id,category:'behavioral_experience',prompt:id,shortTitle:`질문 ${id}`,difficulty:'beginner',targetCapabilities:['interview_communication'],evaluationRubric:{keys:[],guidance:''},localeKey:id})
const attempt=(id:string,questionId:string,dimension?:AnswerQualityDimension,status='needs_improvement'):InterviewAttempt=>({id,questionId,category:'behavioral_experience',createdAt:'2026-01-01',transcript:'answer',durationSeconds:60,analysis:{} as InterviewAttempt['analysis'],attemptNumber:1,completed:true,contentAnalysis:dimension?{rubric:{version:1,evaluated:true,context:'interview',findings:[{dimension,status:status as 'needs_improvement',feedback:'근거',evidence:[]}],strengths:[],improvements:[],followUpCandidates:[]}} as unknown as InterviewAttempt['contentAnalysis']:undefined})
const session=(ids:string[],attemptIds:string[]=[]):InterviewSession=>({id:'session',mode:'general',questionIds:ids,attemptIds,currentQuestionIndex:0,status:'completed',startedAt:'2026-01-01'})

test('safety weakness becomes primary',()=>assert.equal(resolveMockReportActions({session:session(['q'],['a']),attempts:[attempt('a','q','safetyJudgment')],questions:[question('q')]} )[0]?.priority,1))
test('relevance precedes evidence',()=>assert.deepEqual(resolveMockReportActions({session:session(['q1','q2'],['a','b']),attempts:[attempt('a','q1','evidence'),attempt('b','q2','relevance')],questions:[question('q1'),question('q2')]}).map(x=>x.questionId),['q2','q1']))
test('evidence weakness has source attempt lineage',()=>assert.equal(resolveMockReportActions({session:session(['q'],['a']),attempts:[attempt('a','q','evidence')],questions:[question('q')]} )[0]?.sourceAttemptId,'a'))
test('incomplete question becomes candidate',()=>assert.equal(resolveMockReportActions({session:session(['q']),attempts:[],questions:[question('q')]} )[0]?.kind,'RETAKE_QUESTION'))
test('actions are capped at three',()=>assert.equal(resolveMockReportActions({session:session(['a','b','c','d']),attempts:[],questions:['a','b','c','d'].map(question)}).length,3))
test('same question is deduplicated',()=>assert.equal(resolveMockReportActions({session:session(['q'],['a']),attempts:[attempt('a','q','evidence')],questions:[question('q')],queue:[{id:'queue',questionId:'q',reason:'manual',status:'open',priority:5,createdAt:'',updatedAt:''}]}).length,1))
test('existing queue is referenced without mutation',()=>{const queue=[{id:'queue',questionId:'q',reason:'manual' as const,status:'open' as const,priority:5,createdAt:'',updatedAt:''}];const before=JSON.stringify(queue),result=resolveMockReportActions({session:session(['q'],['a']),attempts:[attempt('a','q')],questions:[question('q')],queue});assert.equal(result[0]?.kind,'PRACTICE_QUEUE_ITEM');assert.equal(JSON.stringify(queue),before)})
test('favorite is never toggled by resolver',()=>{const favorites=[{questionId:'q',createdAt:''}];const before=JSON.stringify(favorites);resolveMockReportActions({session:session(['q'],['a']),attempts:[attempt('a','q')],questions:[question('q')],favorites});assert.equal(JSON.stringify(favorites),before)})
test('strong session has honest empty state',()=>assert.equal(resolveMockReportActions({session:session(['q'],['a']),attempts:[attempt('a','q','evidence','strong')],questions:[question('q')]}).length,0))
test('legacy session without rubric is safe',()=>assert.doesNotThrow(()=>resolveMockReportActions({session:session(['q'],['a']),attempts:[attempt('a','q')],questions:[question('q')]})))
test('invalid and generated questions are excluded',()=>assert.equal(resolveMockReportActions({session:session(['missing']),attempts:[],questions:[question('valid')]}).length,0))
test('action carries mock report lineage',()=>assert.deepEqual(Object.fromEntries(Object.entries(resolveMockReportActions({session:session(['q'],['a']),attempts:[attempt('a','q','action')],questions:[question('q')]} )[0]).filter(([key])=>['mockSessionId','sourceAttemptId','questionId'].includes(key))),{questionId:'q',mockSessionId:'session',sourceAttemptId:'a'}))
test('resolver does not change session completion',()=>{const value=session(['q'],['a']),before=JSON.stringify(value);resolveMockReportActions({session:value,attempts:[attempt('a','q','result')],questions:[question('q')]});assert.equal(JSON.stringify(value),before)})
test('ordering is deterministic for equal priority',()=>assert.deepEqual(resolveMockReportActions({session:session(['b','a']),attempts:[],questions:[question('a'),question('b')]}).map(x=>x.questionId),['b','a']))
test('queue action preserves existing queue item target',()=>assert.equal(resolveMockReportActions({session:session(['q'],['a']),attempts:[attempt('a','q')],questions:[question('q')],queue:[{id:'queue',questionId:'q',reason:'manual',status:'open',priority:5,createdAt:'',updatedAt:''}]} )[0]?.queueItemId,'queue'))
test('favorite is a legacy fallback only',()=>assert.equal(resolveMockReportActions({session:session(['q'],['a']),attempts:[attempt('a','q')],questions:[question('q')],favorites:[{questionId:'q',createdAt:''}]} )[0]?.kind,'REVIEW_FAVORITE'))
test('strong rubric is not overridden by an old queue item',()=>assert.equal(resolveMockReportActions({session:session(['q'],['a']),attempts:[attempt('a','q','evidence','strong')],questions:[question('q')],queue:[{id:'queue',questionId:'q',reason:'manual',status:'open',priority:5,createdAt:'',updatedAt:''}]}).length,0))
test('not applicable finding creates no weakness action',()=>assert.equal(resolveMockReportActions({session:session(['q'],['a']),attempts:[attempt('a','q','result','not_applicable')],questions:[question('q')]}).length,0))
test('attempt outside the session is ignored',()=>assert.equal(resolveMockReportActions({session:session(['q'],[]),attempts:[attempt('outside','q','safetyJudgment')],questions:[question('q')]} )[0]?.kind,'RETAKE_QUESTION'))
test('follow-up does not replace base completion evidence',()=>{const follow={...attempt('follow','q','safetyJudgment'),isFollowUp:true};assert.equal(resolveMockReportActions({session:session(['q'],['follow']),attempts:[follow],questions:[question('q')]} )[0]?.kind,'RETAKE_QUESTION')})
test('session airline lineage is preserved',()=>{const value={...session(['q'],['a']),airlineId:'published-airline'};assert.equal(resolveMockReportActions({session:value,attempts:[attempt('a','q','evidence')],questions:[question('q')]} )[0]?.airlineId,'published-airline')})
test('resolver output contains no transcript or score',()=>{const value=resolveMockReportActions({session:session(['q'],['a']),attempts:[attempt('a','q','evidence')],questions:[question('q')]} )[0];assert.equal('transcript' in value,false);assert.equal('score' in value,false)})
