import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { selfIntroductionPrompt } from './self-introduction-language'
import { assessTranscript, contentAnalysisGate, createTranscriptReview, understandInterviewAnswer } from './speech-understanding-v2'

const koPrompt = selfIntroductionPrompt('ko')
const enPrompt = selfIntroductionPrompt('en')
const understandKo = (transcript: string) => understandInterviewAnswer({ questionPrompt: koPrompt, transcript, language: 'ko', practiceType: 'self_introduction' })
const understandEn = (transcript: string) => understandInterviewAnswer({ questionPrompt: enPrompt, transcript, language: 'en', practiceType: 'self_introduction' })

test('30 second challenge uses the real Korean self introduction prompt', () => assert.match(koPrompt, /강점과 경험/))
test('60 second challenge uses the same real prompt contract', () => assert.equal(selfIntroductionPrompt('ko'), koPrompt))
test('90 second challenge does not invent a different question', () => assert.equal(selfIntroductionPrompt('ko'), koPrompt))
test('English mode supplies the English prompt', () => assert.match(enPrompt, /Introduce yourself/))
test('Korean self introduction is directly addressed', () => assert.equal(understandKo('저는 고객 응대 경험을 통해 경청하는 강점을 키웠습니다. 객실승무원으로서 승객에게 기여하겠습니다.').questionAddressed, 'addressed'))
test('English self introduction is directly addressed', () => assert.equal(understandEn('I am a calm communicator. My experience in customer service taught me to listen carefully, and I hope to contribute as cabin crew.').questionAddressed, 'addressed'))
test('main point is copied from the answer', () => assert.equal(understandKo('저는 침착한 소통이 강점입니다. 고객 응대 경험이 있습니다.').mainPoint, '저는 침착한 소통이 강점입니다.'))
test('answer evidence is copied from actual sentences', () => { const text = '저는 침착한 소통이 강점입니다. 고객 응대 경험에서 경청을 배웠습니다.'; assert.ok(understandKo(text).evidence.every((fragment) => text.includes(fragment))) })
test('missing core message is reported', () => assert.ok(understandKo('카페에서 근무한 경험이 있습니다. 객실승무원으로 기여하겠습니다.').missingElements.includes('나를 설명하는 핵심 문장')))
test('missing experience is reported', () => assert.ok(understandKo('저는 침착함이 강점입니다. 객실승무원으로 기여하겠습니다.').missingElements.includes('강점을 뒷받침하는 경험')))
test('missing cabin crew connection is reported', () => assert.ok(understandKo('저는 경청이 강점입니다. 카페 근무 경험에서 고객 응대를 배웠습니다.').missingElements.includes('객실승무원 역할과의 연결')))
test('Korean closing is detected', () => assert.equal(understandKo('저는 서비스 경험이 있습니다. 객실승무원으로 기여하겠습니다.').closing, 'present'))
test('English closing is detected', () => assert.equal(understandEn('I am a service professional with customer experience. I look forward to contributing as cabin crew.').closing, 'present'))
test('missing closing is reported', () => assert.ok(understandKo('저는 소통이 강점입니다. 고객 응대 경험이 있습니다.').missingElements.includes('지원 역할로 연결하는 마무리')))
test('self introduction does not force STAR action', () => assert.equal(understandKo('저는 고객 응대 경험이 강점입니다. 객실승무원으로 기여하겠습니다.').action, 'not_applicable'))
test('self introduction does not force STAR result', () => assert.equal(understandKo('저는 고객 응대 경험이 강점입니다. 객실승무원으로 기여하겠습니다.').result, 'not_applicable'))
test('problem solving evidence requires answer words', () => assert.equal(understandKo('저는 고객 문제를 해결한 경험이 있습니다. 객실승무원으로 기여하겠습니다.').cabinCrewEvidence.find((item) => item.competency === 'problem_solving')?.evidence.length, 1))
test('problem solving evidence is absent when not spoken', () => assert.deepEqual(understandKo('저는 경청이 강점입니다. 서비스 경험이 있습니다. 객실승무원으로 기여하겠습니다.').cabinCrewEvidence.find((item) => item.competency === 'problem_solving')?.evidence, []))
test('safety evidence is evidence-first', () => assert.equal(understandKo('저는 안전을 우선한 경험이 있습니다. 객실승무원으로 기여하겠습니다.').cabinCrewEvidence.find((item) => item.competency === 'safety')?.evidence.length, 1))
test('service evidence is evidence-first', () => assert.equal(understandKo('저는 고객 서비스 경험이 있습니다. 객실승무원으로 기여하겠습니다.').cabinCrewEvidence.find((item) => item.competency === 'service')?.evidence.length, 1))
test('teamwork evidence is evidence-first', () => assert.equal(understandKo('저는 팀 협업 경험이 있습니다. 객실승무원으로 기여하겠습니다.').cabinCrewEvidence.find((item) => item.competency === 'teamwork')?.evidence.length, 1))
test('communication evidence is evidence-first', () => assert.equal(understandKo('저는 경청과 소통을 배운 경험이 있습니다. 객실승무원으로 기여하겠습니다.').cabinCrewEvidence.find((item) => item.competency === 'communication')?.evidence.length, 1))
test('unrelated Korean answer is off topic', () => assert.equal(understandKo('오늘은 날씨가 맑아서 산책하고 요리를 만들었습니다. 주말에는 영화를 보았습니다.').offTopic, true))
test('too-short Korean transcript blocks content', () => assert.equal(contentAnalysisGate(assessTranscript('저는 학생입니다', 'ko')).allowed, false))
test('too-short English transcript blocks content', () => assert.equal(contentAnalysisGate(assessTranscript('I am ready', 'en')).allowed, false))
test('language mismatch blocks Korean mode', () => assert.ok(assessTranscript('I have customer service experience and I communicate calmly with passengers.', 'ko').errors.includes('LANGUAGE_MISMATCH')))
test('language mismatch blocks English mode', () => assert.ok(assessTranscript('저는 고객 서비스 경험을 통해 차분한 소통 역량을 길렀습니다.', 'en').errors.includes('LANGUAGE_MISMATCH')))
test('unchanged transcript keeps actual audio provenance', () => assert.equal(createTranscriptReview('  저는  서비스 경험이 있습니다.  ', '저는 서비스 경험이 있습니다.', 'ko').provenance, 'actual_audio'))
test('corrected transcript records corrected provenance', () => assert.equal(createTranscriptReview('저는 서비수 경험이 있습니다.', '저는 서비스 경험이 있습니다.', 'ko').provenance, 'user_corrected_transcript'))
test('review preserves raw STT text', () => assert.equal(createTranscriptReview('  raw  text ', 'raw text', 'en').rawTranscript, '  raw  text '))
test('review quality is recomputed after correction', () => assert.notEqual(createTranscriptReview('I am ready', 'I am a service professional with customer experience, calm communication, and a goal to contribute as cabin crew.', 'en').quality, 'INSUFFICIENT'))
test('evidence fragments remain bounded', () => assert.ok(understandKo(`저는 ${'침착한 '.repeat(80)}소통 경험이 있습니다. 객실승무원으로 기여하겠습니다.`).evidence.every((fragment) => fragment.length <= 180)))
test('repetition is reported without rewriting', () => { const sentence = '저는 고객 서비스 경험이 있습니다.'; assert.equal(understandKo(`${sentence} ${sentence} 객실승무원으로 기여하겠습니다.`).repetition[0], '저는 고객 서비스 경험이 있습니다') })

const flowSource = readFileSync('components/self-introduction/self-introduction-flow.tsx', 'utf8')
const repositorySource = readFileSync('lib/supabase/training-attempt-repositories.ts', 'utf8')
test('Self Introduction has a transcript review step', () => assert.match(flowSource, /transcript_review/))
test('Self Introduction has a separate content analysis step', () => assert.match(flowSource, /content_analyzing/))
test('Self Introduction sends the selected language to STT', () => assert.match(flowSource, /languageHint: selfIntroductionLanguageHint\(practiceLanguage\)/))
test('Self Introduction passes the selected challenge duration with the real prompt', () => assert.match(flowSource, /challengeTarget[\s\S]*selfIntroductionPrompt\(practiceLanguage\)/))
test('Self Introduction does not use fallback transcript fabrication', () => assert.doesNotMatch(flowSource, /fallbackTranscript/))
test('Self Introduction keeps nonverbal result separate', () => assert.match(flowSource, /nonverbalSignal: completedNonverbalSignal\.current/))
test('Self Introduction stores transcript review provenance', () => assert.match(flowSource, /transcriptReview,/))
test('Self Introduction stores AnswerUnderstanding', () => assert.match(flowSource, /speechUnderstanding,/))
test('remote persistence carries transcript review', () => assert.match(repositorySource, /transcriptReview:value\.transcriptReview/))
test('remote persistence carries AnswerUnderstanding', () => assert.match(repositorySource, /speechUnderstanding:value\.speechUnderstanding/))
