import assert from 'node:assert/strict'
import test from 'node:test'
import { assessTranscript, classifyInterviewQuestion, contentAnalysisGate, normalizeTranscriptForReview, understandInterviewAnswer } from './speech-understanding-v2'

test('normalization preserves words while trimming spacing',()=>assert.equal(normalizeTranscriptForReview('  제가   확인했습니다.\r\n 결과입니다. '),'제가 확인했습니다.\n결과입니다.'))
test('empty transcript is insufficient',()=>assert.deepEqual(assessTranscript('','ko').errors,['STT_EMPTY']))
test('short Korean transcript is insufficient',()=>assert.ok(assessTranscript('네 그렇습니다','ko').errors.includes('TRANSCRIPT_TOO_SHORT')))
test('short English transcript is insufficient',()=>assert.ok(assessTranscript('Yes I can','en').errors.includes('TRANSCRIPT_TOO_SHORT')))
test('Korean hint detects English mismatch',()=>assert.ok(assessTranscript('I handled the customer complaint with my team.','ko').errors.includes('LANGUAGE_MISMATCH')))
test('English hint detects Korean mismatch',()=>assert.ok(assessTranscript('저는 고객의 불편을 확인하고 해결했습니다.','en').errors.includes('LANGUAGE_MISMATCH')))
test('poor repeated filler is insufficient',()=>assert.ok(assessTranscript('um um um um I helped a customer today','en').errors.includes('STT_POOR_TRANSCRIPT')))
test('usable Korean transcript is accepted',()=>assert.equal(contentAnalysisGate(assessTranscript('당시 고객의 불편을 확인하고 제가 대안을 설명했습니다. 이후 문제가 원만히 해결되었습니다.','ko')).allowed,true))
test('good English transcript is accepted',()=>assert.equal(assessTranscript('When a passenger raised a concern, I listened carefully, checked the facts, explained the available options, and worked with my colleague. As a result, the issue was resolved and I learned to communicate early.','en').quality,'GOOD'))
test('insufficient transcript blocks content analysis',()=>assert.equal(contentAnalysisGate(assessTranscript('네','ko')).allowed,false))

const types:Array<[string,ReturnType<typeof classifyInterviewQuestion>]>=[
  ['자기소개를 해주세요.','SELF_INTRODUCTION'],['왜 객실승무원에 지원했나요?','MOTIVATION'],['갈등을 해결한 경험을 말해주세요.','CONFLICT'],['팀워크를 발휘한 경험은?','TEAMWORK'],['본인의 강점과 약점은?','STRENGTH_WEAKNESS'],['비상 상황에서 안전을 어떻게 지키겠습니까?','SAFETY'],['승객 불만에 어떻게 대응하겠습니까?','SITUATIONAL'],['고객 서비스에서 중요한 점은?','SERVICE'],['Tell me about a time you solved a problem.','EXPERIENCE'],['오늘의 목표는 무엇인가요?','GENERAL'],
]
for(const [prompt,expected] of types)test(`classifies ${expected}`,()=>assert.equal(classifyInterviewQuestion(prompt),expected))

test('behavioral answer is addressed with direct evidence',()=>{const value=understandInterviewAnswer({questionPrompt:'고객 문제를 해결한 경험을 말해주세요.',questionCategory:'behavioral_experience',language:'ko',transcript:'당시 고객이 불편을 호소했습니다. 제가 주문을 확인하고 대안을 설명했습니다. 결과적으로 문제가 해결되었고 경청의 중요성을 배웠습니다.'});assert.equal(value.questionAddressed,'addressed');assert.equal(value.action,'present');assert.equal(value.result,'present');assert.ok(value.evidence.every(fragment=>value.mainPoint!==null&&fragment.length<=180))})
test('generic behavioral claim has no invented evidence',()=>{const text='저는 항상 열심히 하고 친절하게 소통합니다.';const value=understandInterviewAnswer({questionPrompt:'갈등을 해결한 경험을 말해주세요.',questionCategory:'behavioral_experience',language:'ko',transcript:text});assert.equal(value.specificity,'generic');assert.deepEqual(value.evidence,[]);assert.ok(value.missingElements.includes('답변에서 확인 가능한 구체적 근거'))})
test('off-topic answer is detected',()=>{const value=understandInterviewAnswer({questionPrompt:'비상 상황에서 안전을 어떻게 지키겠습니까?',questionCategory:'safety_and_role_judgment',language:'ko',transcript:'저의 강점은 밝은 성격이고 새로운 요리를 배우는 것을 좋아합니다.'});assert.equal(value.offTopic,true);assert.equal(value.questionAddressed,'not_addressed')})
test('safety evidence is verbatim only',()=>{const text='저는 안전을 우선하고 위험을 확인한 뒤 즉시 상급자에게 보고하겠습니다.';const value=understandInterviewAnswer({questionPrompt:'비상 상황에서 어떻게 대응합니까?',questionCategory:'safety_and_role_judgment',language:'ko',transcript:text});assert.deepEqual(value.cabinCrewEvidence.find(item=>item.competency==='safety')?.evidence,[text])})
test('service evidence is not inferred without words',()=>{const value=understandInterviewAnswer({questionPrompt:'서비스 경험을 말해주세요.',questionCategory:'customer_situation',language:'ko',transcript:'저는 매일 계획을 세우고 공부했습니다.'});assert.deepEqual(value.cabinCrewEvidence.find(item=>item.competency==='service')?.evidence,[])})
test('teamwork evidence is isolated',()=>{const text='팀 동료와 역할을 나누고 협업했습니다.';const value=understandInterviewAnswer({questionPrompt:'팀워크 경험을 말해주세요.',language:'ko',transcript:text});assert.deepEqual(value.cabinCrewEvidence.find(item=>item.competency==='teamwork')?.evidence,[text])})
test('communication evidence is isolated',()=>{const text='고객의 말을 경청하고 선택지를 설명했습니다.';const value=understandInterviewAnswer({questionPrompt:'고객 서비스 경험을 말해주세요.',language:'ko',transcript:text});assert.deepEqual(value.cabinCrewEvidence.find(item=>item.competency==='communication')?.evidence,[text])})
test('STAR is not forced on motivation',()=>{const value=understandInterviewAnswer({questionPrompt:'왜 지원했나요?',questionCategory:'introduction_and_motivation',language:'ko',transcript:'객실승무원으로서 승객의 안전과 편안한 서비스를 함께 책임지고 싶어 지원했습니다.'});assert.equal(value.situation,'not_applicable');assert.equal(value.action,'not_applicable');assert.equal(value.result,'not_applicable')})
test('situational question requires action but not result',()=>{const value=understandInterviewAnswer({questionPrompt:'승객 불만 상황에서 어떻게 대응하겠습니까?',questionCategory:'customer_situation',language:'ko',transcript:'승객의 말을 경청하고 상황을 확인하겠습니다.'});assert.equal(value.action,'present');assert.equal(value.result,'not_applicable')})
test('experience question marks missing result',()=>{const value=understandInterviewAnswer({questionPrompt:'고객 문제를 해결한 경험을 말해주세요.',questionCategory:'behavioral_experience',language:'ko',transcript:'당시 고객이 불편해했고 제가 주문을 확인하고 대안을 설명했습니다.'});assert.equal(value.result,'missing');assert.ok(value.missingElements.includes('결과'))})
test('experience question marks reflection present',()=>{const value=understandInterviewAnswer({questionPrompt:'어려움을 극복한 경험을 말해주세요.',questionCategory:'behavioral_experience',language:'ko',transcript:'당시 문제가 있었고 제가 직접 확인했습니다. 이 경험으로 사전 확인의 중요성을 배웠습니다.'});assert.equal(value.reflection,'present')})
test('duplicate sentences are reported without rewriting',()=>{const sentence='제가 고객 요청을 확인하고 설명했습니다.';const value=understandInterviewAnswer({questionPrompt:'고객 서비스 경험을 말해주세요.',language:'ko',transcript:`${sentence} ${sentence}`});assert.equal(value.repetition[0],'제가 고객 요청을 확인하고 설명했습니다')})
test('evidence is capped at five fragments',()=>{const transcript=Array.from({length:8},(_,i)=>`당시 ${i}번 상황에서 제가 확인하고 해결했습니다.`).join(' ');const value=understandInterviewAnswer({questionPrompt:'문제 해결 경험을 말해주세요.',questionCategory:'behavioral_experience',language:'ko',transcript});assert.ok(value.evidence.length<=5)})
test('evidence fragments are capped at 180 characters',()=>{const transcript=`제가 ${'아주 '.repeat(100)}직접 확인하고 해결했습니다.`;const value=understandInterviewAnswer({questionPrompt:'문제 해결 경험을 말해주세요.',questionCategory:'behavioral_experience',language:'ko',transcript});assert.ok(value.evidence.every(item=>item.length<=180))})
test('English behavioral evidence is recognized',()=>{const value=understandInterviewAnswer({questionPrompt:'Tell me about a time you handled a complaint.',questionCategory:'behavioral_experience',language:'en',transcript:'When a passenger complained, I checked the booking and explained two options. As a result, the issue was resolved and I learned to confirm expectations early.'});assert.equal(value.questionAddressed,'addressed');assert.equal(value.result,'present')})
test('answer does not create cabin crew evidence from question',()=>{const value=understandInterviewAnswer({questionPrompt:'How would you protect passenger safety?',questionCategory:'safety_and_role_judgment',language:'en',transcript:'I would remain calm and think carefully.'});assert.deepEqual(value.cabinCrewEvidence.find(item=>item.competency==='safety')?.evidence,[])})
test('self introduction practice type uses self introduction applicability',()=>{const value=understandInterviewAnswer({questionPrompt:'60초 답변',language:'ko',practiceType:'self_introduction',transcript:'저는 고객 응대 경험을 바탕으로 경청하는 강점을 키웠습니다. 이 경험에서 먼저 확인하는 태도를 배웠습니다.'});assert.equal(value.questionType,'SELF_INTRODUCTION');assert.equal(value.action,'not_applicable');assert.equal(value.result,'not_applicable')})
