import { AI_LIMITS, loadAiConfig, sanitizeTextForAi, validateText } from './config'
import { aiConsentRepository } from './consent-repository'
import { failure, normalizeAiError } from './errors'
import { providerRegistry } from './provider-registry'
import { aiUsageRepository } from './usage-repository'
import type { AiProvider, AiRequestContext, AiResponse, AiTaskType, AnalyzeApplicationAnswerRequest, AnalyzeInterviewRequest, AnalyzeSelfIntroductionRequest, ApplicationRevisionResult, CoachMessageResult, GenerateApplicationDraftRequest, GenerateCoachMessageRequest, ReviseApplicationDraftRequest, StructureExperienceRequest, StructuredExperienceResult, TranscriptionRequest, TranscriptionResult } from './types'
import type { InterviewAnswerAnalysis } from '@/lib/interview-practice-data'
import type { SelfIntroductionAnalysis } from '@/lib/self-introduction-data'
import type { ApplicationAnswerAnalysis, ApplicationDraft } from '@/lib/application-answer-repository'
import { assertNoAgeDataInRecommendationContext } from '@/lib/privacy/assert-no-age-data'

const cache=new Map<string,{expires:number;data:unknown}>(),requestId=()=>`ai-${Date.now()}-${Math.random().toString(36).slice(2,8)}`
const hash=(value:unknown)=>{const s=JSON.stringify(value);let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return(h>>>0).toString(36)}
function context(task:AiTaskType|'transcription',targetAirlineId?:string,audio=false):AiRequestContext{const consent=aiConsentRepository.load(),provider=task==='transcription'?providerRegistry.activeStt().id:providerRegistry.activeAi(task).id,isMock=provider==='mock';return{requestId:requestId(),locale:'ko',targetAirlineId,consentGranted:isMock||(audio?consent.allowAudioProcessing:consent.allowTextProcessing),createdAt:new Date().toISOString(),timeoutMs:loadAiConfig().timeoutMs,metadata:{task}}}
function sanitized<T>(value:T):T{return JSON.parse(JSON.stringify(value,(_key,item)=>typeof item==='string'?sanitizeTextForAi(item):item))}
async function timed<T>(action:(signal:AbortSignal)=>Promise<AiResponse<T>>,timeoutMs:number,outer?:AbortSignal){const controller=new AbortController(),timer=setTimeout(()=>controller.abort('timeout'),timeoutMs),abort=()=>controller.abort();outer?.addEventListener('abort',abort,{once:true});try{return await action(controller.signal)}finally{clearTimeout(timer);outer?.removeEventListener('abort',abort)}}
const transcriptionRequests=new WeakMap<Blob,Promise<AiResponse<TranscriptionResult>>>()
export function deduplicateTranscription(blob:Blob,action:()=>Promise<AiResponse<TranscriptionResult>>){const existing=transcriptionRequests.get(blob);if(existing)return existing;const request=action().finally(()=>transcriptionRequests.delete(blob));transcriptionRequests.set(blob,request);return request}
type ProviderMethod='analyzeInterviewAnswer'|'analyzeSelfIntroduction'|'structureExperience'|'generateApplicationDraft'|'reviseApplicationDraft'|'analyzeApplicationAnswer'|'generateCoachMessage'
async function execute<T>(task:AiTaskType,method:ProviderMethod,request:unknown,targetAirlineId?:string,signal?:AbortSignal):Promise<AiResponse<T>>{const c=context(task,targetAirlineId);assertNoAgeDataInRecommendationContext({request,context:c},task);const config=loadAiConfig(),primary=providerRegistry.activeAi(task),cacheKey=`${primary.id}:${task}:${hash(request)}`,hit=cache.get(cacheKey);if(hit&&hit.expires>Date.now())return hit.data as AiResponse<T>;if(primary.id!=='mock'&&!c.consentGranted&&(!config.enableFallback||providerRegistry.fallbackAi().id!=='mock'))return failure(c.requestId,'consent_required','Consent is required',primary.id,false);const invoke=async(provider:AiProvider)=>{const safe=provider.id==='server'?sanitized(request):request;return timed<T>(s=>Reflect.apply(provider[method],provider,[safe,c,s]),config.timeoutMs,signal)};let response:AiResponse<T>;try{response=await invoke(primary);if(!response.ok&&response.error.retryable&&config.retryCount>0&&response.error.code!=='rate_limited')response=await invoke(primary)}catch(error){response={ok:false,requestId:c.requestId,providerId:primary.id,error:normalizeAiError(error),fallbackAvailable:config.enableFallback}}if(!response.ok&&config.enableFallback&&response.fallbackAvailable&&response.error.code!=='invalid_request'&&response.error.code!=='cancelled'){const fallbackProvider=providerRegistry.fallbackAi();if(fallbackProvider.id!==primary.id){const fallback=await invoke(fallbackProvider);if(fallback.ok){fallback.usage.fallbackUsed=true;fallback.warnings.push({code:'fallback_used',message:'현재 기본 분석 모드로 결과를 제공했습니다.'});response=fallback}}}if(response.usage)aiUsageRepository.record(response.usage);if(response.ok){cache.set(cacheKey,{expires:Date.now()+AI_LIMITS.cacheTtlMs,data:response});return response}return response}
export const aiService={
  analyzeInterviewAnswer:(request:AnalyzeInterviewRequest,options?:{signal?:AbortSignal})=>execute<InterviewAnswerAnalysis>('interview_analysis','analyzeInterviewAnswer',request,undefined,options?.signal),
  analyzeSelfIntroduction:(request:AnalyzeSelfIntroductionRequest,options?:{signal?:AbortSignal})=>execute<SelfIntroductionAnalysis>('self_introduction_analysis','analyzeSelfIntroduction',request,undefined,options?.signal),
  structureExperience:(request:StructureExperienceRequest,options?:{signal?:AbortSignal})=>execute<StructuredExperienceResult>('experience_structuring','structureExperience',request,undefined,options?.signal),
  generateApplicationDraft:(request:GenerateApplicationDraftRequest,options?:{signal?:AbortSignal})=>execute<ApplicationDraft>('application_draft_generation','generateApplicationDraft',request,request.airlineId,options?.signal),
  reviseApplicationDraft:(request:ReviseApplicationDraftRequest,options?:{signal?:AbortSignal})=>execute<ApplicationRevisionResult>('application_draft_revision','reviseApplicationDraft',request,request.airlineId,options?.signal),
  analyzeApplicationAnswer:(request:AnalyzeApplicationAnswerRequest,options?:{signal?:AbortSignal})=>execute<ApplicationAnswerAnalysis>('application_answer_analysis','analyzeApplicationAnswer',request,request.airlineId,options?.signal),
  generateCoachMessage:(request:GenerateCoachMessageRequest,options?:{signal?:AbortSignal})=>execute<CoachMessageResult>('coach_message_generation','generateCoachMessage',request,undefined,options?.signal),
  async transcribeAudio(request:TranscriptionRequest,options?:{signal?:AbortSignal}){const c=context('transcription',undefined,true);assertNoAgeDataInRecommendationContext({request:{...request,audioBlob:request.audioBlob?{type:request.audioBlob.type,size:request.audioBlob.size}:undefined},context:c},'transcription');const primary=providerRegistry.activeStt();if((request.durationSeconds??0)>AI_LIMITS.maxAudioSeconds)return failure(c.requestId,'audio_too_large','Audio is too long',primary.id,false);if((request.audioBlob?.size??0)>AI_LIMITS.maxAudioBytes)return failure(c.requestId,'audio_too_large','Audio file is too large',primary.id,false);if(request.mimeType&&!AI_LIMITS.supportedAudioMimeTypes.some(x=>request.mimeType!.startsWith(x)))return failure(c.requestId,'audio_format_unsupported','Unsupported audio format',primary.id,false);const run=()=>timed(s=>primary.transcribe(request,c,s),loadAiConfig().timeoutMs,options?.signal);const response=request.audioBlob?await deduplicateTranscription(request.audioBlob,run):await run();if(response.usage)aiUsageRepository.record(response.usage);return response as AiResponse<TranscriptionResult>},
  sanitizeTextForAi,clearMemoryCache:()=>cache.clear()
}
