import { analyzeApplicationAnswer as deterministicApplicationAnalysis, generateApplicationDraft as deterministicDraft, getVerifiedAirlineContext } from '@/lib/application-answer-repository'
import { recommendCompetencies, type CareerExperience } from '@/lib/experience-repository'
import { analyzeInterviewAnswer as deterministicInterviewAnalysis } from '@/lib/interview-practice-data'
import { analyzeSelfIntroduction as deterministicSelfIntroduction } from '@/lib/self-introduction-data'
import type { AiProvider, AiRequestContext, AiResponse, AiTaskType, AiUsage } from '../types'

const respond=<T>(data:T,taskType:AiTaskType,context:AiRequestContext,inputCharacters=0):AiResponse<T>=>{const completedAt=new Date().toISOString();return{ok:true,requestId:context.requestId,providerId:'mock',data,usage:{providerId:'mock',taskType,inputCharacters,outputCharacters:JSON.stringify(data).length,startedAt:context.createdAt,completedAt,durationMs:Math.max(0,new Date(completedAt).getTime()-new Date(context.createdAt).getTime()),success:true,fallbackUsed:false},warnings:[{code:'mock_result',message:'기본 분석 모드 결과입니다.'}]}}
const abort=(signal?:AbortSignal)=>{if(signal?.aborted)throw new DOMException('Aborted','AbortError')}
export const mockAiProvider:AiProvider={id:'mock',isAvailable:()=>true,
async analyzeInterviewAnswer(r,c,s){abort(s);return respond(deterministicInterviewAnalysis(r.question,r.transcript,r.durationSeconds),'interview_analysis',c,r.transcript.length)},
async analyzeSelfIntroduction(r,c,s){abort(s);return respond(deterministicSelfIntroduction(r.transcript,r.durationSeconds),'self_introduction_analysis',c,r.transcript.length)},
async structureExperience(r,c,s){abort(s);const source=r.originalText.trim(),parts=source.split(/(?<=[.!?요다])\s+/);const data={situation:r.current.situation||parts[0]||source,task:r.current.task||parts[1]||'',action:r.current.action||parts.slice(2,-2).join(' '),result:r.current.result||parts.at(-2)||'',learning:r.current.learning||parts.at(-1)||'',suggestedCompetencyTags:recommendCompetencies({...r.current,id:'mock',title:'',category:r.category,roleConnection:'',shortSummary:'',competencyTags:[],questionTags:[],status:'draft',createdAt:c.createdAt,updatedAt:c.createdAt,usageCount:0,source:'manual'} as CareerExperience),evidenceWarnings:source?['사용자 원문 범위에서만 구조화했습니다.']:['원문이 없어 기존 값만 유지했습니다.']};return respond(data,'experience_structuring',c,source.length)},
async generateApplicationDraft(r,c,s){abort(s);return respond(deterministicDraft(r),'application_draft_generation',c,JSON.stringify(r).length)},
async reviseApplicationDraft(r,c,s){abort(s);let content=r.content;if(r.mode==='concise')content=content.split(/(?<=\.)\s+/).filter((_,i)=>i%3!==2).join(' ');else if(r.mode==='polish')content=content.replace(/매우|정말|항상/g,'');else if(r.mode==='role_connection')content+= ' 이 경험을 고객과 안전을 함께 고려하는 객실승무원 업무에 연결하겠습니다.';else if(r.mode==='airline_connection'){const x=getVerifiedAirlineContext(r.airlineId);if(x?.servicePhilosophy)content+=` ${x.airlineName}의 검수된 서비스 방향과 연결해 기여하겠습니다.`}return respond({content,changedSentenceIds:content===r.content?[]:['revision-1'],evidence:r.evidence,warnings:content===r.content?['검수된 근거가 없어 기존 문장을 유지했습니다.']:[]},'application_draft_revision',c,r.content.length)},
async analyzeApplicationAnswer(r,c,s){abort(s);return respond(deterministicApplicationAnalysis(r.content,r.prompt,r.evidence,r.airlineId),'application_answer_analysis',c,r.content.length)},
async generateCoachMessage(r,c,s){abort(s);const weakest=Object.entries(r.scores).sort((a,b)=>a[1]-b[1])[0]?.[0]??'핵심 역량';return respond({message:`${weakest}을 중심으로 다음 훈련을 이어가세요.`,recommendedAction:r.weaknesses[0]??'최근 답변을 한 번 더 점검하세요.',relatedTaskType:'coach_message_generation'},'coach_message_generation',c,JSON.stringify(r).length)}}
