import assert from 'node:assert/strict'
import test from 'node:test'
import { POST } from './route'

const original={key:process.env.AZURE_SPEECH_KEY,region:process.env.AZURE_SPEECH_REGION,provider:process.env.PRONUNCIATION_PROVIDER,fetch:globalThis.fetch}
const formRequest=(input:{consent?:boolean;language?:string;audio?:File;transcript?:string})=>{const form=new FormData();if(input.audio)form.set('audio',input.audio);form.set('transcript',input.transcript??'Cabin crew safety.');form.set('language',input.language??'en-US');form.set('consent',String(input.consent??true));return new Request('http://localhost/api/pronunciation/analyze',{method:'POST',body:form})}
const audio=()=>new File([new Uint8Array([1,2,3])],'answer.webm',{type:'audio/webm'})
const configured=()=>{process.env.AZURE_SPEECH_KEY='hidden-test-key';process.env.AZURE_SPEECH_REGION='test-region';process.env.PRONUNCIATION_PROVIDER='azure'}
const restore=()=>{if(original.key===undefined)delete process.env.AZURE_SPEECH_KEY;else process.env.AZURE_SPEECH_KEY=original.key;if(original.region===undefined)delete process.env.AZURE_SPEECH_REGION;else process.env.AZURE_SPEECH_REGION=original.region;if(original.provider===undefined)delete process.env.PRONUNCIATION_PROVIDER;else process.env.PRONUNCIATION_PROVIDER=original.provider;globalThis.fetch=original.fetch}

test('missing ENV fails closed before any Azure request',async()=>{delete process.env.AZURE_SPEECH_KEY;delete process.env.AZURE_SPEECH_REGION;delete process.env.PRONUNCIATION_PROVIDER;let calls=0;globalThis.fetch=async()=>{calls++;return new Response()};try{const response=await POST(formRequest({audio:audio()}));assert.equal(response.status,503);assert.equal(calls,0);assert.equal((await response.json()).status,'not_configured')}finally{restore()}})

test('denied consent, non-English, and invalid audio make zero Azure requests',async()=>{configured();let calls=0;globalThis.fetch=async()=>{calls++;return new Response()};try{for(const request of [formRequest({audio:audio(),consent:false}),formRequest({audio:audio(),language:'ko-KR'}),formRequest({audio:new File([new Uint8Array([1])],'x.txt',{type:'text/plain'})})]){const response=await POST(request);assert.ok(response.status>=400)}assert.equal(calls,0)}finally{restore()}})

test('valid Azure response is normalized without preserving raw response fields',async()=>{configured();globalThis.fetch=async()=>new Response(JSON.stringify({rawSecret:'discard',NBest:[{Display:'Safety first.',PronunciationAssessment:{PronScore:91,FluencyScore:85},Words:[{Word:'Safety',Offset:0,Duration:5_000_000,PronunciationAssessment:{AccuracyScore:89,ErrorType:'None'}}]}]}),{status:200});try{const response=await POST(formRequest({audio:audio()}));const body=await response.json();assert.equal(response.status,200);assert.equal(body.overall.pronunciationScore,91);assert.equal(body.words[0].endMs,500);assert.equal('rawSecret' in body,false)}finally{restore()}})

test('401, 403, 429, 5xx, abort, and malformed responses remain unavailable',async()=>{configured();try{for(const status of [401,403,429,500]){globalThis.fetch=async()=>new Response('{}',{status});const response=await POST(formRequest({audio:audio()}));assert.equal((await response.json()).status,'failed')}globalThis.fetch=async()=>{throw new DOMException('aborted','AbortError')};assert.equal((await (await POST(formRequest({audio:audio()}))).json()).status,'failed');globalThis.fetch=async()=>new Response(JSON.stringify({NBest:[{}]}),{status:200});assert.equal((await (await POST(formRequest({audio:audio()}))).json()).status,'failed')}finally{restore()}})
