import type {User} from '@supabase/supabase-js'
import {airlineById} from '@/lib/airline-data'
import {listApplicationAnswers,listAnswerVersions,type ApplicationAnswer,type ApplicationAnswerVersion} from '@/lib/application-answer-repository'
import {getSupabaseBrowserClient} from './client'
import {syncQueueRepository,type SyncQueueItem} from './sync-queue-repository'

export type ApplicationStatus='planning'|'drafting'|'ready'|'submitted'|'screening'|'interview'|'offer'|'rejected'|'withdrawn'|'archived'
export const applicationStatusLabel:Record<ApplicationStatus,string>={planning:'준비 중',drafting:'작성 중',ready:'제출 준비',submitted:'제출 완료',screening:'서류 전형',interview:'면접 진행',offer:'합격',rejected:'불합격',withdrawn:'지원 철회',archived:'보관됨'}
export type AirlineApplication={id:string;airlineId?:string;airlineNameSnapshot:string;positionTitle:string;status:ApplicationStatus;deadlineAt?:string;submittedAt?:string;interviewAt?:string;memo?:string;createdAt:string;updatedAt:string;deletedAt?:string}
export type ApplicationDraft={id:string;applicationId:string;title:string;versionNumber:number;contentJson:{content:string;characterCount:number;analysis?:unknown;changeReason:string};isCurrent:boolean;createdAt:string;updatedAt:string;deletedAt?:string}
export type ApplicationActivity={id:string;applicationId:string;activityType:'created'|'updated'|'version_saved'|'submitted'|'status_changed'|'deleted';occurredAt:string}
const DECISION='cabin-application-merge-decision-v1',META='cabin-application-sync-meta-v1'
const read=<T>(key:string):Record<string,T>=>{try{return JSON.parse(localStorage.getItem(key)??'{}')}catch{return{}}}
const write=(key:string,value:unknown)=>localStorage.setItem(key,JSON.stringify(value))
export const applicationMergeDecision={
  get(userId:string){return read<string>(DECISION)[userId]},
  set(userId:string,value:'connect_all'|'review_server'|'keep_local'|'later'){
    write(DECISION,{...read<string>(DECISION),[userId]:value})
  }
}
export const applicationSyncMeta={get(id:string){return read<{status:'local_only'|'pending'|'synced'|'failed'}>(META)[id]??{status:'local_only' as const}},set(id:string,status:'local_only'|'pending'|'synced'|'failed'){write(META,{...read(META),[id]:{status}});window.dispatchEvent(new Event('cabin:application-sync-changed'))}}
export function statusFromAnswer(answer:ApplicationAnswer):ApplicationStatus{return answer.status==='ready'?'ready':answer.status==='reviewed'?'drafting':answer.status==='structured'?'drafting':'planning'}
export function airlineApplicationFromAnswer(answer:ApplicationAnswer):AirlineApplication{return{id:answer.id,airlineId:answer.airlineId,airlineNameSnapshot:answer.sourceContextSnapshot?.airlineName??(answer.airlineId?airlineById.get(answer.airlineId)?.name:'')??'',positionTitle:answer.title,status:statusFromAnswer(answer),createdAt:answer.createdAt,updatedAt:answer.updatedAt}}
export function airlineApplicationToRow(value:AirlineApplication,userId:string){return{user_id:userId,legacy_id:value.id,airline_id:value.airlineId??null,airline_name_snapshot:value.airlineNameSnapshot,position_title:value.positionTitle,status:value.status,deadline_at:value.deadlineAt??null,submitted_at:value.submittedAt??null,interview_at:value.interviewAt??null,memo:value.memo??null,deleted_at:value.deletedAt??null}}
export function applicationDraftFromVersion(value:ApplicationAnswerVersion,answer:ApplicationAnswer):ApplicationDraft{return{id:value.id,applicationId:answer.id,title:answer.title,versionNumber:value.version,contentJson:{content:value.content,characterCount:value.characterCount,analysis:value.analysis,changeReason:value.changeReason},isCurrent:answer.currentVersionId===value.id,createdAt:value.createdAt,updatedAt:answer.updatedAt}}
export function applicationDraftToRow(value:ApplicationDraft,userId:string,applicationId:string){return{user_id:userId,application_id:applicationId,legacy_id:value.id,title:value.title,version_number:value.versionNumber,content_json:value.contentJson,is_current:value.isCurrent,deleted_at:value.deletedAt??null}}
export function applicationAnswerToRow(answer:ApplicationAnswer,userId:string,applicationId:string){const current=listAnswerVersions(answer.id).find(version=>version.id===answer.currentVersionId);return{user_id:userId,legacy_id:answer.id,application_id:applicationId,airline_id:answer.airlineId??null,prompt_id:answer.promptId,question_key:answer.promptId,question_text_snapshot:answer.customPrompt??answer.title,answer_text:current?.content??'',answer_order:0,custom_prompt:answer.customPrompt??null,document_type:answer.documentType,title:answer.title,status:answer.status,selected_experience_ids:answer.selectedExperienceIds,source_context_snapshot:answer.sourceContextSnapshot??{},client_updated_at:answer.updatedAt}}
export function applicationAnswerFromRow(row:{legacy_id:string|null;airline_id:string|null;prompt_id:string;custom_prompt:string|null;document_type:string;title:string;status:string;selected_experience_ids:unknown;created_at:string;updated_at:string}):Partial<ApplicationAnswer>{return{id:row.legacy_id??'',airlineId:row.airline_id??undefined,promptId:row.prompt_id,customPrompt:row.custom_prompt??undefined,documentType:row.document_type as ApplicationAnswer['documentType'],title:row.title,status:row.status as ApplicationAnswer['status'],selectedExperienceIds:Array.isArray(row.selected_experience_ids)?row.selected_experience_ids as string[]:[],createdAt:row.created_at,updatedAt:row.updated_at}}

export interface AirlineApplicationRepository{list():Promise<AirlineApplication[]>;save(value:AirlineApplication):Promise<void>;softDelete(id:string):Promise<void>}
export interface ApplicationDraftRepository{list(applicationId:string):Promise<ApplicationDraft[]>;save(value:ApplicationDraft):Promise<void>}
export interface ApplicationAnswerRepository{list(applicationId:string):Promise<ApplicationAnswer[]>;save(value:ApplicationAnswer):Promise<void>}
export interface ApplicationActivityRepository{list(applicationId:string):Promise<ApplicationActivity[]>;save(value:ApplicationActivity):Promise<void>}
export class LocalAirlineApplicationRepository implements AirlineApplicationRepository{async list(){return listApplicationAnswers().map(airlineApplicationFromAnswer)}async save(){}async softDelete(){}}
export class LocalApplicationDraftRepository implements ApplicationDraftRepository{async list(applicationId:string){const answer=listApplicationAnswers().find(item=>item.id===applicationId);return answer?listAnswerVersions(answer.id).map(version=>applicationDraftFromVersion(version,answer)):[]}async save(){}}
export class LocalApplicationAnswerRepository implements ApplicationAnswerRepository{async list(applicationId:string){return listApplicationAnswers().filter(answer=>answer.id===applicationId)}async save(){}}
export class LocalApplicationActivityRepository implements ApplicationActivityRepository{async list(applicationId:string):Promise<ApplicationActivity[]>{const answer=listApplicationAnswers().find(item=>item.id===applicationId);return answer?[{id:`activity-${answer.id}`,applicationId,activityType:'updated',occurredAt:answer.updatedAt}]:[]}async save(){}}

export class SupabaseAirlineApplicationRepository implements AirlineApplicationRepository{constructor(private user:User){}async list(){const client=getSupabaseBrowserClient();if(!client)throw new Error('not_configured');const{data,error}=await client.from('airline_applications').select('*').is('deleted_at',null).order('updated_at',{ascending:false});if(error)throw error;return(data??[]).map(row=>({id:row.legacy_id??row.id,airlineId:row.airline_id??undefined,airlineNameSnapshot:row.airline_name_snapshot,positionTitle:row.position_title,status:row.status as ApplicationStatus,deadlineAt:row.deadline_at??undefined,submittedAt:row.submitted_at??undefined,interviewAt:row.interview_at??undefined,memo:row.memo??undefined,createdAt:row.created_at,updatedAt:row.updated_at,deletedAt:row.deleted_at??undefined}))}async save(value:AirlineApplication){const client=getSupabaseBrowserClient();if(!client)throw new Error('not_configured');const{error}=await client.from('airline_applications').upsert(airlineApplicationToRow(value,this.user.id) as never,{onConflict:'user_id,legacy_id'});if(error)throw error}async softDelete(id:string){const client=getSupabaseBrowserClient();if(!client)throw new Error('not_configured');const{data,error}=await client.from('airline_applications').select('id').eq('legacy_id',id).single();if(error||!data)throw error??new Error('application_not_found');const deletedAt=new Date().toISOString();const results=await Promise.all([client.from('airline_applications').update({deleted_at:deletedAt} as never).eq('id',data.id),client.from('application_drafts').update({deleted_at:deletedAt} as never).eq('application_id',data.id),client.from('application_answers').update({deleted_at:deletedAt} as never).eq('application_id',data.id)]);if(results.some(result=>result.error))throw results.find(result=>result.error)?.error}}
async function remoteApplicationId(user:User,value:AirlineApplication){const client=getSupabaseBrowserClient();if(!client)throw new Error('not_configured');const{data,error}=await client.from('airline_applications').upsert(airlineApplicationToRow(value,user.id) as never,{onConflict:'user_id,legacy_id'}).select('id').single();if(error||!data)throw error??new Error('application_upsert_failed');return data.id}
export class SupabaseApplicationDraftRepository implements ApplicationDraftRepository{constructor(private user:User){}async list(){return[]}async save(value:ApplicationDraft){const answer=listApplicationAnswers().find(item=>item.id===value.applicationId);if(!answer)throw new Error('local_application_missing');const id=await remoteApplicationId(this.user,airlineApplicationFromAnswer(answer)),client=getSupabaseBrowserClient();if(!client)throw new Error('not_configured');const{error}=await client.from('application_drafts').upsert(applicationDraftToRow(value,this.user.id,id) as never,{onConflict:'user_id,legacy_id'});if(error)throw error}}
export class SupabaseApplicationAnswerRepository implements ApplicationAnswerRepository{constructor(private user:User){}async list(){return[]}async save(value:ApplicationAnswer){const id=await remoteApplicationId(this.user,airlineApplicationFromAnswer(value)),client=getSupabaseBrowserClient();if(!client)throw new Error('not_configured');const{error}=await client.from('application_answers').upsert(applicationAnswerToRow(value,this.user.id,id) as never,{onConflict:'user_id,legacy_id'});if(error)throw error}}
export class SupabaseApplicationActivityRepository implements ApplicationActivityRepository{constructor(private user:User){}async list(){return[]}async save(value:ApplicationActivity){const answer=listApplicationAnswers().find(item=>item.id===value.applicationId);if(!answer)throw new Error('local_application_missing');const id=await remoteApplicationId(this.user,airlineApplicationFromAnswer(answer)),client=getSupabaseBrowserClient();if(!client)throw new Error('not_configured');const{error}=await client.from('application_activity_logs').upsert({user_id:this.user.id,application_id:id,activity_type:value.activityType,occurred_at:value.occurredAt,metadata:{}} as never);if(error)throw error}}
export class HybridAirlineApplicationRepository extends LocalAirlineApplicationRepository{constructor(readonly user:User){super()}}
export class HybridApplicationDraftRepository extends LocalApplicationDraftRepository{constructor(readonly user:User){super()}}
export class HybridApplicationAnswerRepository extends LocalApplicationAnswerRepository{constructor(readonly user:User){super()}}
export class HybridApplicationActivityRepository extends LocalApplicationActivityRepository{constructor(readonly user:User){super()}}

async function push(item:SyncQueueItem,user:User){if(item.entityType==='airline_application'&&item.operation==='delete')return new SupabaseAirlineApplicationRepository(user).softDelete(item.entityId);if(item.entityType==='airline_application')return new SupabaseAirlineApplicationRepository(user).save(item.payload as AirlineApplication);if(item.entityType==='application_draft')return new SupabaseApplicationDraftRepository(user).save(item.payload as ApplicationDraft);if(item.entityType==='application_answer')return new SupabaseApplicationAnswerRepository(user).save(item.payload as ApplicationAnswer);if(item.entityType==='application_activity')return new SupabaseApplicationActivityRepository(user).save(item.payload as ApplicationActivity)}
export function localApplicationSyncSummary(){const answers=listApplicationAnswers(),versions=answers.flatMap(answer=>listAnswerVersions(answer.id));return{applications:answers.length,drafts:versions.length,answers:answers.length,activities:answers.length}}
function queueLocalApplicationDeletions(user:User){try{const key='cabin-application-deletions-v1',ids=JSON.parse(localStorage.getItem(key)??'[]');if(!Array.isArray(ids))return;ids.filter((id):id is string=>typeof id==='string').forEach(id=>syncQueueRepository.enqueue({userId:user.id,entityType:'airline_application',entityId:id,operation:'delete',localUpdatedAt:new Date().toISOString()}))}catch{}}
export async function connectAllLocalApplications(user:User){for(const answer of listApplicationAnswers()){const application=airlineApplicationFromAnswer(answer);syncQueueRepository.enqueue({userId:user.id,entityType:'airline_application',entityId:application.id,operation:'create',payload:application,localUpdatedAt:application.updatedAt});syncQueueRepository.enqueue({userId:user.id,entityType:'application_answer',entityId:answer.id,operation:'create',payload:answer,localUpdatedAt:answer.updatedAt});for(const version of listAnswerVersions(answer.id)){const draft=applicationDraftFromVersion(version,answer);syncQueueRepository.enqueue({userId:user.id,entityType:'application_draft',entityId:draft.id,operation:'create',payload:draft,localUpdatedAt:draft.updatedAt})}syncQueueRepository.enqueue({userId:user.id,entityType:'application_activity',entityId:`activity-${answer.id}`,operation:'create',payload:{id:`activity-${answer.id}`,applicationId:answer.id,activityType:'updated',occurredAt:answer.updatedAt} satisfies ApplicationActivity,localUpdatedAt:answer.updatedAt})}queueLocalApplicationDeletions(user);applicationMergeDecision.set(user.id,'connect_all');await flushApplicationQueue(user)}
let flushing=false
export async function flushApplicationQueue(user:User){if(flushing||!navigator.onLine)return;flushing=true;try{for(const item of syncQueueRepository.list().filter(item=>item.userId===user.id&&['airline_application','application_draft','application_answer','application_activity'].includes(item.entityType)&&['pending','failed'].includes(item.status))){try{applicationSyncMeta.set(item.entityId,'pending');await push(item,user);if(item.operation==='delete'){try{const key='cabin-application-deletions-v1',ids=JSON.parse(localStorage.getItem(key)??'[]');localStorage.setItem(key,JSON.stringify(Array.isArray(ids)?ids.filter(id=>id!==item.entityId):[]))}catch{}}syncQueueRepository.update(item.id,{status:'completed'});applicationSyncMeta.set(item.entityId,'synced')}catch{syncQueueRepository.update(item.id,{status:'failed',retryCount:item.retryCount+1});applicationSyncMeta.set(item.entityId,'failed')}}syncQueueRepository.clearCompleted()}finally{flushing=false}}
export function startApplicationSyncCoordinator(user:User){const flush=()=>{if(applicationMergeDecision.get(user.id)==='connect_all'){queueLocalApplicationDeletions(user);void flushApplicationQueue(user)}};window.addEventListener('online',flush);window.addEventListener('cabin:application-local-changed',flush);flush();return()=>{window.removeEventListener('online',flush);window.removeEventListener('cabin:application-local-changed',flush)}}
