// Hand-maintained from supabase/migrations for unconfigured development.
// Replace with generated types after connecting a project; see SUPABASE_SETUP.md.
export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[]
type UserRow={id:string;user_id:string;created_at:string;updated_at:string;client_updated_at:string;schema_version:number;deleted_at:string|null}
type Table<Row,Insert=Partial<Row>,Update=Partial<Row>>={Row:Row;Insert:Insert;Update:Update;Relationships:[]}
export type Database={public:{Tables:{
  profiles:Table<{id:string;display_name:string|null;full_name:string|null;phone:string|null;birth_date:string|null;kakao_id:string|null;profile_completed:boolean;required_terms_version:string|null;privacy_consent_version:string|null;required_terms_agreed_at:string|null;privacy_consent_agreed_at:string|null;marketing_consent:boolean;marketing_consent_at:string|null;kakao_contact_consent:boolean;kakao_contact_consent_at:string|null;sms_notification_consent:boolean;sms_notification_consent_at:string|null;age_verified_at:string|null;is_under_14:boolean|null;phone_verified:boolean;phone_verified_at:string|null;locale:string;timezone:string|null;primary_airline_id:string|null;onboarding_completed:boolean;avatar_path:string|null;avatar_url:string|null;recruitment_language:string|null;app_preferences:Json;last_active_at:string|null;created_at:string;updated_at:string},Partial<{id:string}>>
  onboarding_states:Table<UserRow&{answers:Json;diagnosis_result:Json;completed:boolean}>
  career_experiences:Table<UserRow&{legacy_id:string|null;title:string;category:string;organization:string|null;role:string|null;period:string|null;situation:string;task:string;action:string;result:string;learning:string;role_connection:string;short_summary:string;competency_tags:string[];question_tags:string[];status:string;source:string;original_transcript:string|null;source_experience_id:string|null;usage_count:number;last_used_at:string|null}>
  interview_attempts:Table<UserRow&{legacy_id:string|null;question_id:string;category:string;transcript:string;duration_seconds:number;analysis:Json;target_airline_id:string|null;experience_id:string|null;experience_snapshot:Json;attempt_number:number;previous_attempt_id:string|null;completed:boolean;audio_path:string|null}>
  self_introduction_attempts:Table<UserRow&{legacy_id:string|null;transcript:string;duration_seconds:number;analysis:Json;target_airline_id:string|null;experience_id:string|null;experience_snapshot:Json;attempt_number:number;previous_attempt_id:string|null;completed:boolean;audio_path:string|null}>
  application_answers:Table<UserRow&{legacy_id:string|null;application_id:string|null;airline_id:string|null;prompt_id:string;question_key:string|null;question_text_snapshot:string|null;answer_text:string|null;answer_order:number;custom_prompt:string|null;document_type:string;title:string;status:string;selected_experience_ids:Json;current_version_id:string|null;source_context_snapshot:Json}>
  application_answer_versions:Table<Omit<UserRow,'user_id'>&{user_id:string;answer_id:string;version:number;content:string;character_count:number;word_count:number;evidence:Json;analysis:Json;change_reason:string}>
  airline_applications:Table<UserRow&{legacy_id:string|null;airline_id:string|null;airline_name_snapshot:string;position_title:string;status:string;deadline_at:string|null;submitted_at:string|null;interview_at:string|null;memo:string|null}>
  application_drafts:Table<UserRow&{application_id:string;legacy_id:string|null;title:string;version_number:number;content_json:Json;is_current:boolean}>
  application_activity_logs:Table<{id:string;user_id:string;application_id:string;activity_type:string;occurred_at:string;metadata:Json;created_at:string}>
  learning_events:Table<UserRow&{event_type:string;source_entity_type:string;source_entity_id:string|null;duration_minutes:number;duration_source:string;related_capability_keys:string[];capability_deltas:Json;metadata:Json;occurred_at:string;stable_key:string}>
  weekly_plans:Table<UserRow&{week_start:string;week_end:string;status:string;priorities:Json;routine_days:Json;generated_from_activity_ids:Json;confirmed_at:string|null;revision:number;plan_json:Json;completion_json:Json;progress_percent:number}>
  user_learning_profiles:Table<{user_id:string;onboarding_snapshot:Json;target_airline_ids:Json;learning_priorities:Json;weekly_available_minutes:number|null;current_plan_id:string|null;created_at:string;updated_at:string}>
  user_settings:Table<UserRow&{locale:string;timezone:string|null;ai_text_consent:boolean;ai_audio_consent:boolean;airline_context_consent:boolean;cloud_audio_preference:string;study_time:string|null;primary_airline_id:string|null;interested_airline_ids:string[];notification_preferences:Json;provider_preference:Json}>
  sync_metadata:Table<UserRow&{device_id:string;last_sync_at:string|null;last_pulled_at:string|null;last_pushed_at:string|null;app_schema_version:number}>
  user_audio_files:Table<UserRow&{entity_type:string;entity_id:string;bucket:string;path:string;mime_type:string;size_bytes:number;duration_seconds:number|null}>
};Views:Record<string,never>;Functions:Record<string,never>;Enums:Record<string,never>;CompositeTypes:Record<string,never>}}
