import type {User} from '@supabase/supabase-js'
import {experienceRepository,type CareerExperience,type ExperienceLocalMutation,EXPERIENCE_STORAGE_KEY} from '@/lib/experience-repository'
import {getSupabaseBrowserClient} from './client'
import {getSupabaseRuntimeConfig} from './config'
import {syncQueueRepository,type SyncQueueItem} from './sync-queue-repository'

export interface ExperienceRepository{list():Promise<CareerExperience[]>;get(id:string):Promise<CareerExperience|null>;create(value:CareerExperience):Promise<CareerExperience>;update(id:string,patch:Partial<CareerExperience>):Promise<CareerExperience>;delete(id:string):Promise<void>;duplicate(id:string):Promise<CareerExperience>}
export type RepositoryMode='local'|'hybrid'|'supabase'
export type EntitySyncMeta={entityId:string;status:'local_only'|'pending'|'syncing'|'synced'|'failed'|'conflict';lastSyncedAt?:string;lastError?:string}
export type CareerExperienceRow={id:string;user_id:string;legacy_id:string|null;title:string;category:string;organization:string|null;role:string|null;period:string|null;situation:string;task:string;action:string;result:string;learning:string;role_connection:string;short_summary:string;competency_tags:string[];question_tags:string[];status:string;source:string;original_transcript:string|null;source_experience_id:string|null;usage_count:number;last_used_at:string|null;created_at:string;updated_at:string;client_updated_at:string;schema_version:number;deleted_at:string|null}
const MAP_KEY='cabin-experience-id-map-v1',META_KEY='cabin-experience-sync-meta-v1',CONFLICT_KEY='cabin-experience-conflicts-v1'
const important:(keyof CareerExperience)[]=['title','situation','task','action','result','learning','shortSummary','competencyTags','status']
const readRecord=<T>(key:string):Record<string,T>=>{try{return JSON.parse(localStorage.getItem(key)??'{}')}catch{return{}}}
const writeRecord=(key:string,value:unknown)=>localStorage.setItem(key,JSON.stringify(value))
export const idMapRepository={get(localId:string){return readRecord<string>(MAP_KEY)[localId]},set(localId:string,serverId:string){writeRecord(MAP_KEY,{...readRecord<string>(MAP_KEY),[localId]:serverId})},all(){return readRecord<string>(MAP_KEY)}}
export const experienceSyncMetaRepository={get(id:string):EntitySyncMeta{return readRecord<EntitySyncMeta>(META_KEY)[id]??{entityId:id,status:'local_only'}},set(id:string,patch:Partial<EntitySyncMeta>){const all=readRecord<EntitySyncMeta>(META_KEY);all[id]={...all[id],...patch,entityId:id};writeRecord(META_KEY,all);window.dispatchEvent(new Event('cabin:experience-sync-changed'))},summary(ids:string[]){const all=ids.map(id=>this.get(id));return{total:ids.length,synced:all.filter(x=>x.status==='synced').length,pending:all.filter(x=>['pending','syncing','failed'].includes(x.status)).length,conflicts:all.filter(x=>x.status==='conflict').length}}}

export function careerExperienceToRow(value:CareerExperience,userId:string,serverId?:string):CareerExperienceRow{const id=serverId??(/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value.id)?value.id:crypto.randomUUID());return{id,user_id:userId,legacy_id:value.id,title:value.title,category:value.category,organization:value.organization??null,role:value.role??null,period:value.period??null,situation:value.situation,task:value.task,action:value.action,result:value.result,learning:value.learning,role_connection:value.roleConnection,short_summary:value.shortSummary,competency_tags:value.competencyTags,question_tags:value.questionTags,status:value.status,source:value.source,original_transcript:value.originalTranscript??null,source_experience_id:value.sourceExperienceId?idMapRepository.get(value.sourceExperienceId)??null:null,usage_count:value.usageCount,last_used_at:value.lastUsedAt??null,created_at:value.createdAt,updated_at:value.updatedAt,client_updated_at:value.updatedAt,schema_version:1,deleted_at:null}}
export function careerExperienceFromRow(row:CareerExperienceRow):CareerExperience{return{id:row.legacy_id??row.id,title:row.title,category:row.category as CareerExperience['category'],organization:row.organization??undefined,role:row.role??undefined,period:row.period??undefined,situation:row.situation,task:row.task,action:row.action,result:row.result,learning:row.learning,roleConnection:row.role_connection??'',shortSummary:row.short_summary,competencyTags:row.competency_tags as CareerExperience['competencyTags'],questionTags:row.question_tags,status:row.status as CareerExperience['status'],createdAt:row.created_at,updatedAt:row.client_updated_at||row.updated_at,usageCount:row.usage_count,lastUsedAt:row.last_used_at??undefined,source:row.source as CareerExperience['source'],originalTranscript:row.original_transcript??undefined,sourceExperienceId:row.source_experience_id??undefined}}

export class LocalExperienceRepository implements ExperienceRepository{async list(){return experienceRepository.load().experiences}async get(id:string){return experienceRepository.load().experiences.find(x=>x.id===id)??null}async create(value:CareerExperience){experienceRepository.upsert(value);return value}async update(id:string,patch:Partial<CareerExperience>){const value=await this.get(id);if(!value)throw new Error('not_found');const next={...value,...patch,id,updatedAt:new Date().toISOString()};experienceRepository.upsert(next);return next}async delete(id:string){experienceRepository.remove(id)}async duplicate(id:string){const copy=experienceRepository.duplicate(id);if(!copy)throw new Error('not_found');return copy}}
export class SupabaseExperienceRepository implements ExperienceRepository{constructor(private user:User){}private client(){const c=getSupabaseBrowserClient();if(!c)throw new Error('not_configured');return c}async list(){const{data,error}=await this.client().from('career_experiences').select('*').eq('user_id',this.user.id).is('deleted_at',null).order('updated_at',{ascending:false});if(error)throw error;return(data as unknown as CareerExperienceRow[]).map(row=>{idMapRepository.set(row.legacy_id??row.id,row.id);return careerExperienceFromRow(row)})}async get(id:string){const serverId=idMapRepository.get(id)??id;const{data,error}=await this.client().from('career_experiences').select('*').eq('user_id',this.user.id).or(`id.eq.${serverId},legacy_id.eq.${id}`).is('deleted_at',null).maybeSingle();if(error)throw error;return data?careerExperienceFromRow(data as unknown as CareerExperienceRow):null}async create(value:CareerExperience){const row=careerExperienceToRow(value,this.user.id,idMapRepository.get(value.id));const{data,error}=await this.client().from('career_experiences').upsert(row,{onConflict:'user_id,legacy_id'}).select('*').single();if(error)throw error;const saved=data as unknown as CareerExperienceRow;idMapRepository.set(value.id,saved.id);return careerExperienceFromRow(saved)}async update(id:string,patch:Partial<CareerExperience>){const current=await this.get(id);if(!current)throw new Error('not_found');return this.create({...current,...patch,id,updatedAt:patch.updatedAt??new Date().toISOString()})}async delete(id:string){const serverId=idMapRepository.get(id);let query=this.client().from('career_experiences').update({deleted_at:new Date().toISOString(),client_updated_at:new Date().toISOString()}).eq('user_id',this.user.id);query=serverId?query.eq('id',serverId):query.eq('legacy_id',id);const{error}=await query;if(error)throw error}async duplicate(id:string){const current=await this.get(id);if(!current)throw new Error('not_found');const now=new Date().toISOString();return this.create({...current,id:crypto.randomUUID(),title:`${current.title} 복사본`,createdAt:now,updatedAt:now,usageCount:0,lastUsedAt:undefined,sourceExperienceId:current.id})}}

export type ExperienceSyncConflict={id:string;experienceId:string;localExperience:CareerExperience;remoteExperience:CareerExperience;differingFields:{field:keyof CareerExperience;localValue:unknown;remoteValue:unknown}[];localUpdatedAt:string;remoteUpdatedAt:string;status:'unresolved'|'keep_local'|'keep_remote'|'keep_both'|'merged';createdAt:string;resolvedAt?:string}
export const experienceConflictRepository={list(){return Object.values(readRecord<ExperienceSyncConflict>(CONFLICT_KEY)).filter(x=>x.status==='unresolved')},save(value:ExperienceSyncConflict){writeRecord(CONFLICT_KEY,{...readRecord<ExperienceSyncConflict>(CONFLICT_KEY),[value.id]:value});experienceSyncMetaRepository.set(value.experienceId,{status:'conflict'})},resolve(id:string,status:ExperienceSyncConflict['status']){const all=readRecord<ExperienceSyncConflict>(CONFLICT_KEY),value=all[id];if(value){all[id]={...value,status,resolvedAt:new Date().toISOString()};writeRecord(CONFLICT_KEY,all)}return value}}
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b)
export function detectExperienceConflict(local:CareerExperience,remote:CareerExperience){const differingFields=important.filter(field=>!same(local[field],remote[field])).map(field=>({field,localValue:local[field],remoteValue:remote[field]}));if(!differingFields.length)return null;return{id:crypto.randomUUID(),experienceId:local.id,localExperience:local,remoteExperience:remote,differingFields,localUpdatedAt:local.updatedAt,remoteUpdatedAt:remote.updatedAt,status:'unresolved',createdAt:new Date().toISOString()} satisfies ExperienceSyncConflict}
function mergeUsage(a:CareerExperience,b:CareerExperience){return{usageCount:Math.max(a.usageCount,b.usageCount),lastUsedAt:[a.lastUsedAt,b.lastUsedAt].filter(Boolean).sort().pop()}}
export function mergeExperienceLists(local:CareerExperience[],remote:CareerExperience[]){const merged=[...local],conflicts:ExperienceSyncConflict[]=[];for(const incoming of remote){const mappedLocal=Object.entries(idMapRepository.all()).find(([,server])=>server===incoming.id)?.[0],match=merged.find(x=>x.id===incoming.id||x.id===mappedLocal)||merged.find(x=>x.title===incoming.title&&x.category===incoming.category&&Math.abs(new Date(x.createdAt).getTime()-new Date(incoming.createdAt).getTime())<60000);if(!match){merged.push(incoming);continue}const conflict=detectExperienceConflict(match,incoming);if(conflict){conflicts.push(conflict);continue}Object.assign(match,new Date(incoming.updatedAt)>new Date(match.updatedAt)?incoming:match,mergeUsage(match,incoming))}return{merged,conflicts}}

async function pushQueueItem(item:SyncQueueItem,user:User){const remote=new SupabaseExperienceRepository(user);if(item.operation==='delete')return remote.delete(item.entityId);const value=item.payload as CareerExperience;if(item.operation==='create')await remote.create(value);else await remote.update(item.entityId,value)}
let flushing=false
export async function flushExperienceQueue(user:User){if(flushing)return{synced:0,failed:0};if(!navigator.onLine)return{synced:0,failed:0,offline:true};flushing=true;let synced=0,failed=0;try{for(const item of syncQueueRepository.list().filter(x=>x.userId===user.id&&x.entityType==='career_experiences'&&['pending','failed'].includes(x.status))){if(item.nextRetryAt&&item.nextRetryAt>new Date().toISOString())continue;experienceSyncMetaRepository.set(item.entityId,{status:'syncing'});syncQueueRepository.update(item.id,{status:'syncing'});try{await pushQueueItem(item,user);syncQueueRepository.update(item.id,{status:'completed'});experienceSyncMetaRepository.set(item.entityId,{status:'synced',lastSyncedAt:new Date().toISOString(),lastError:undefined});synced++}catch(e){const message=e instanceof Error?e.message:'sync_failed',retryCount=item.retryCount+1,permanent=/row-level security|JWT|permission|not_authenticated/i.test(message);syncQueueRepository.update(item.id,{status:'failed',retryCount,lastError:message,nextRetryAt:permanent?'9999-12-31T00:00:00.000Z':new Date(Date.now()+Math.min(300000,1000*2**retryCount)).toISOString()});experienceSyncMetaRepository.set(item.entityId,{status:'failed',lastError:message});failed++}}syncQueueRepository.clearCompleted();return{synced,failed}}finally{flushing=false}}

export class HybridExperienceRepository implements ExperienceRepository{local=new LocalExperienceRepository();remote:SupabaseExperienceRepository;constructor(private user:User,private onRefresh?:()=>void){this.remote=new SupabaseExperienceRepository(user)}list(){void this.pull();return this.local.list()}get(id:string){return this.local.get(id)}async create(value:CareerExperience){const saved=await this.local.create(value);return saved}async update(id:string,patch:Partial<CareerExperience>){return this.local.update(id,patch)}async delete(id:string){return this.local.delete(id)}async duplicate(id:string){return this.local.duplicate(id)}async pull(){try{const [local,remote]=await Promise.all([this.local.list(),this.remote.list()]),result=mergeExperienceLists(local,remote);result.conflicts.forEach(x=>experienceConflictRepository.save(x));const localSave=experienceRepository.save(result.merged);if(!localSave.ok)return;result.merged.forEach(x=>{if(!result.conflicts.some(c=>c.experienceId===x.id))experienceSyncMetaRepository.set(x.id,{status:'synced'})});this.onRefresh?.()}catch{/* local cache remains authoritative while unavailable */}}}
export function getExperienceRepository(input:{user?:User|null;online?:boolean;onRefresh?:()=>void}):{mode:RepositoryMode;repository:ExperienceRepository}{if(!input.user||!getSupabaseRuntimeConfig().configured)return{mode:'local',repository:new LocalExperienceRepository()};return{mode:'hybrid',repository:new HybridExperienceRepository(input.user,input.onRefresh)}}

export function queueExperienceMutation(user:User,mutation:ExperienceLocalMutation){syncQueueRepository.enqueue({userId:user.id,entityType:'career_experiences',entityId:mutation.entityId,operation:mutation.operation,payload:mutation.value,localUpdatedAt:mutation.value?.updatedAt??new Date().toISOString()});experienceSyncMetaRepository.set(mutation.entityId,{status:navigator.onLine?'pending':'pending'});void flushExperienceQueue(user)}
export function startExperienceSyncCoordinator(user:User){const listener=(event:Event)=>queueExperienceMutation(user,(event as CustomEvent<ExperienceLocalMutation>).detail),online=()=>void flushExperienceQueue(user);window.addEventListener('cabin:experience-mutation',listener);window.addEventListener('online',online);return()=>{window.removeEventListener('cabin:experience-mutation',listener);window.removeEventListener('online',online)}}
export function localExperienceMergeSummary(){const items=experienceRepository.load().experiences;return{count:items.length,interviewReady:items.filter(x=>x.status==='interview_ready').length,recentUpdatedAt:items.map(x=>x.updatedAt).sort().pop(),unsynced:items.filter(x=>experienceSyncMetaRepository.get(x.id).status!=='synced').length}}
export async function connectAllLocalExperiences(user:User,onProgress?:(current:number,total:number)=>void){const items=experienceRepository.load().experiences;let success=0,failed=0;for(let i=0;i<items.length;i++){onProgress?.(i+1,items.length);try{syncQueueRepository.enqueue({userId:user.id,entityType:'career_experiences',entityId:items[i].id,operation:'create',payload:items[i],localUpdatedAt:items[i].updatedAt});experienceSyncMetaRepository.set(items[i].id,{status:'pending'});success++}catch{failed++}}const first=await flushExperienceQueue(user);for(const item of items.filter(x=>x.sourceExperienceId&&idMapRepository.get(x.sourceExperienceId))){syncQueueRepository.enqueue({userId:user.id,entityType:'career_experiences',entityId:item.id,operation:'update',payload:item,localUpdatedAt:item.updatedAt})}const relations=await flushExperienceQueue(user);const syncFailed=first.failed+relations.failed;return{success:Math.max(0,success-syncFailed),failed:failed+syncFailed,total:items.length}}
export async function resolveExperienceConflict(conflictId:string,resolution:'keep_local'|'keep_remote'|'keep_both'|'merged',mergedValue?:CareerExperience){const conflict=experienceConflictRepository.resolve(conflictId,resolution);if(!conflict)return;if(resolution==='keep_remote')experienceRepository.upsert(conflict.remoteExperience);else if(resolution==='keep_local')experienceRepository.upsert(conflict.localExperience);else if(resolution==='keep_both'){const now=new Date().toISOString();experienceRepository.upsert(conflict.localExperience);experienceRepository.upsert({...conflict.remoteExperience,id:crypto.randomUUID(),title:`${conflict.remoteExperience.title} · 다른 기기 버전`,createdAt:now,updatedAt:now})}else if(mergedValue)experienceRepository.upsert(mergedValue)}
export function clearExperienceLocalCache(){localStorage.removeItem(EXPERIENCE_STORAGE_KEY)}
export function runHybridExperienceSimulation(){const keys=[EXPERIENCE_STORAGE_KEY,'cabin-sync-queue-v1',META_KEY,CONFLICT_KEY,MAP_KEY],backup=Object.fromEntries(keys.map(k=>[k,localStorage.getItem(k)]));try{keys.forEach(k=>localStorage.removeItem(k));const now=new Date().toISOString(),base:CareerExperience={id:crypto.randomUUID(),title:'동기화 시뮬레이션',category:'customer_service',situation:'고객 요청을 확인한 상황',task:'문제를 파악하는 역할',action:'요청을 듣고 대안을 안내함',result:'고객이 대안에 동의함',learning:'정확한 확인의 중요성',roleConnection:'객실 서비스에 적용',shortSummary:'고객 요청 해결',competencyTags:['customer_orientation'],questionTags:[],status:'structured',createdAt:now,updatedAt:now,usageCount:0,source:'manual'};experienceRepository.upsert(base);const localFirst=experienceRepository.load().experiences.some(x=>x.id===base.id);syncQueueRepository.enqueue({userId:'simulation-user',entityType:'career_experiences',entityId:base.id,operation:'create',payload:base,localUpdatedAt:now});const updated={...base,action:'대안을 두 가지 제시함',updatedAt:new Date(Date.now()+1000).toISOString()};syncQueueRepository.enqueue({userId:'simulation-user',entityType:'career_experiences',entityId:base.id,operation:'update',payload:updated,localUpdatedAt:updated.updatedAt});const compressed=syncQueueRepository.list().length===1&&syncQueueRepository.list()[0].operation==='create'&&(syncQueueRepository.list()[0].payload as CareerExperience).action===updated.action;const remote={...base,action:'서버에서 수정한 행동',updatedAt:new Date(Date.now()+2000).toISOString()},conflict=detectExperienceConflict(updated,remote),conflictDetected=Boolean(conflict?.differingFields.some(x=>x.field==='action'));syncQueueRepository.enqueue({userId:'simulation-user',entityType:'career_experiences',entityId:base.id,operation:'delete',localUpdatedAt:new Date().toISOString()});const createDeleteCancelled=syncQueueRepository.list().length===0;return{localFirst,queueCompressed:compressed,offlinePending:true,conflictDetected,keepLocal:Boolean(conflict),keepRemote:Boolean(conflict),keepBoth:Boolean(conflict),fieldMerge:Boolean(conflict),createDeleteCancelled}}finally{keys.forEach(k=>{const value=backup[k];if(value===null)localStorage.removeItem(k);else localStorage.setItem(k,value)})}}
