import type {User} from '@supabase/supabase-js'
import {getSupabaseBrowserClient} from './client'
import {syncQueueRepository,type SyncQueueItem} from './sync-queue-repository'
import {loadOnboarding,type StoredOnboarding} from '@/lib/onboarding-data'
import {learningAnalyticsRepository,type LearningAnalyticsStore} from '@/lib/learning-analytics-repository'

export type LearningSyncStatus='local_only'|'pending'|'synced'|'failed'
const META='cabin-learning-sync-meta-v1',DECISION='cabin-learning-merge-decision-v1'
const read=<T>(key:string):Record<string,T>=>{try{return JSON.parse(localStorage.getItem(key)??'{}')}catch{return{}}}
const write=(key:string,value:unknown)=>localStorage.setItem(key,JSON.stringify(value))
export const learningSyncMeta={get(key:string){return read<{status:LearningSyncStatus}>(META)[key]??{status:'local_only' as const}},set(key:string,status:LearningSyncStatus){write(META,{...read(META),[key]:{status}});window.dispatchEvent(new Event('cabin:learning-sync-changed'))}}
export const learningMergeDecision={
  get(userId:string){return read<string>(DECISION)[userId]},
  set(userId:string,value:'connect_all'|'review_server'|'keep_local'|'later'){
    write(DECISION,{...read<string>(DECISION),[userId]:value})
  }
}
export type LearningProfileLocal={onboarding:StoredOnboarding|null;analytics:LearningAnalyticsStore}
export const loadLocalLearningProfile=():LearningProfileLocal=>({onboarding:loadOnboarding(),analytics:learningAnalyticsRepository.load()})
export function learningProfileToRow(local:LearningProfileLocal,userId:string){const answers=local.onboarding?.answers;return{user_id:userId,onboarding_snapshot:local.onboarding??{},target_airline_ids:[answers?.primaryAirline,...(answers?.interestAirlines??[])].filter(Boolean),learning_priorities:local.onboarding?.diagnosis?.priorityAreas??[],weekly_available_minutes:local.onboarding?.diagnosis?.routineMinutesPerTask??null}}
export function weeklyPlanToRow(plan:LearningAnalyticsStore['confirmedWeeklyPlans'][number],userId:string){const completion=learningAnalyticsRepository.load().routineCompletions.filter(item=>item.occurredAt.startsWith(plan.weekStart));const total=plan.days.flatMap(day=>day.tasks).length,progress=total?Math.round(Math.min(100,(completion.length/total)*100)):0;return{user_id:userId,week_start:plan.weekStart,week_end:plan.days.at(-1)?.date??plan.weekStart,status:'confirmed',priorities:[],routine_days:plan.days,generated_from_activity_ids:[],plan_json:plan,completion_json:completion,progress_percent:progress,revision:1,client_updated_at:plan.updatedAt}}
export function learningActivityToRow(item:LearningAnalyticsStore['routineCompletions'][number],userId:string){return{user_id:userId,event_type:'routine_completed',source_entity_type:'routine',source_entity_id:item.taskId,duration_minutes:item.minutes,duration_source:'estimated',related_capability_keys:[item.relatedCapability],capability_deltas:{},metadata:{},occurred_at:item.occurredAt,stable_key:item.id,client_updated_at:item.occurredAt}}
export interface LearningProfileRepository{load():Promise<LearningProfileLocal>;save(value:LearningProfileLocal):Promise<void>}
export interface WeeklyPlanRepository{list():Promise<LearningAnalyticsStore['confirmedWeeklyPlans']>;save(value:LearningAnalyticsStore['confirmedWeeklyPlans'][number]):Promise<void>}
export interface LearningActivityRepository{list():Promise<LearningAnalyticsStore['routineCompletions']>;save(value:LearningAnalyticsStore['routineCompletions'][number]):Promise<void>}
export class LocalLearningProfileRepository implements LearningProfileRepository{async load(){return loadLocalLearningProfile()}async save(){}}
export class LocalWeeklyPlanRepository implements WeeklyPlanRepository{async list(){return learningAnalyticsRepository.load().confirmedWeeklyPlans}async save(value:LearningAnalyticsStore['confirmedWeeklyPlans'][number]){learningAnalyticsRepository.confirmPlan(value)}}
export class LocalLearningActivityRepository implements LearningActivityRepository{async list(){return learningAnalyticsRepository.load().routineCompletions}async save(value:LearningAnalyticsStore['routineCompletions'][number]){learningAnalyticsRepository.recordRoutine({id:value.taskId,name:value.title,minutes:value.minutes},value.relatedCapability)}}
export class SupabaseLearningProfileRepository implements LearningProfileRepository{constructor(private user:User){}async load(){return loadLocalLearningProfile()}async save(value:LearningProfileLocal){const c=getSupabaseBrowserClient();if(!c)throw new Error('not_configured');const{error}=await c.from('user_learning_profiles').upsert(learningProfileToRow(value,this.user.id) as never,{onConflict:'user_id'});if(error)throw error}}
export class SupabaseWeeklyPlanRepository implements WeeklyPlanRepository{constructor(private user:User){}async list(){return[]}async save(value:LearningAnalyticsStore['confirmedWeeklyPlans'][number]){const c=getSupabaseBrowserClient();if(!c)throw new Error('not_configured');const{error}=await c.from('weekly_plans').upsert(weeklyPlanToRow(value,this.user.id) as never,{onConflict:'user_id,week_start,revision'});if(error)throw error}}
export class SupabaseLearningActivityRepository implements LearningActivityRepository{constructor(private user:User){}async list(){return[]}async save(value:LearningAnalyticsStore['routineCompletions'][number]){const c=getSupabaseBrowserClient();if(!c)throw new Error('not_configured');const{error}=await c.from('learning_events').upsert(learningActivityToRow(value,this.user.id) as never,{onConflict:'user_id,stable_key'});if(error)throw error}}
export class HybridLearningProfileRepository extends LocalLearningProfileRepository{constructor(readonly user:User){super()}}
export class HybridWeeklyPlanRepository extends LocalWeeklyPlanRepository{constructor(readonly user:User){super()}}
export class HybridLearningActivityRepository extends LocalLearningActivityRepository{constructor(readonly user:User){super()}}
async function push(item:SyncQueueItem,user:User){if(item.entityType==='learning_profile')return new SupabaseLearningProfileRepository(user).save(item.payload as LearningProfileLocal);if(item.entityType==='weekly_learning_plan')return new SupabaseWeeklyPlanRepository(user).save(item.payload as LearningAnalyticsStore['confirmedWeeklyPlans'][number]);if(item.entityType==='learning_activity')return new SupabaseLearningActivityRepository(user).save(item.payload as LearningAnalyticsStore['routineCompletions'][number])}
export async function connectAllLocalLearning(user:User){const local=loadLocalLearningProfile();syncQueueRepository.enqueue({userId:user.id,entityType:'learning_profile',entityId:'profile',operation:'create',payload:local,localUpdatedAt:new Date().toISOString()});local.analytics.confirmedWeeklyPlans.forEach(plan=>syncQueueRepository.enqueue({userId:user.id,entityType:'weekly_learning_plan',entityId:plan.weekStart,operation:'create',payload:plan,localUpdatedAt:plan.updatedAt}));local.analytics.routineCompletions.forEach(item=>syncQueueRepository.enqueue({userId:user.id,entityType:'learning_activity',entityId:item.id,operation:'create',payload:item,localUpdatedAt:item.occurredAt}));learningMergeDecision.set(user.id,'connect_all');await flushLearningQueue(user)}
let flushing=false
export async function flushLearningQueue(user:User){if(flushing||!navigator.onLine)return;flushing=true;try{for(const item of syncQueueRepository.list().filter(item=>item.userId===user.id&&['learning_profile','weekly_learning_plan','learning_activity'].includes(item.entityType)&&['pending','failed'].includes(item.status))){try{await push(item,user);syncQueueRepository.update(item.id,{status:'completed'});learningSyncMeta.set(item.entityId,'synced')}catch{syncQueueRepository.update(item.id,{status:'failed',retryCount:item.retryCount+1});learningSyncMeta.set(item.entityId,'failed')}}syncQueueRepository.clearCompleted()}finally{flushing=false}}
export function startLearningSyncCoordinator(user:User){const flush=()=>{if(learningMergeDecision.get(user.id)==='connect_all')void flushLearningQueue(user)};window.addEventListener('online',flush);window.addEventListener('cabin:learning-local-changed',flush);flush();return()=>{window.removeEventListener('online',flush);window.removeEventListener('cabin:learning-local-changed',flush)}}
