import type {User} from '@supabase/supabase-js'
import {getSupabaseBrowserClient} from './client'
import {getSupabaseRuntimeConfig} from './config'
import {syncQueueRepository,type SyncQueueItem} from './sync-queue-repository'
import {storageService} from './storage-service'
import {loadInterviewAttempts,saveInterviewAttempt,type InterviewAttempt} from '@/lib/interview-practice-data'
import {deleteAttemptAudio,loadAttemptAudio,loadSelfIntroductionAttempts,saveSelfIntroductionAttempt,type SelfIntroductionAttempt} from '@/lib/self-introduction-data'

type Kind='interview'|'self_introduction'
type Attempt=InterviewAttempt|SelfIntroductionAttempt
type AttemptRow={id:string;user_id:string;legacy_id:string;question_id?:string;category?:string;transcript:string;duration_seconds:number;analysis:unknown;target_airline_id:string|null;experience_id:string|null;experience_snapshot:unknown;attempt_number:number;previous_attempt_id:string|null;completed:boolean;audio_path:string|null;created_at:string;updated_at:string;client_updated_at:string;schema_version:number}
const MAP_KEY='cabin-training-attempt-id-map-v1',META_KEY='cabin-training-sync-meta-v1'
const read=<T>(key:string):Record<string,T>=>{try{return JSON.parse(localStorage.getItem(key)??'{}')}catch{return{}}}
const write=(key:string,value:unknown)=>localStorage.setItem(key,JSON.stringify(value))
const isUuid=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
const table=(kind:Kind)=>kind==='interview'?'interview_attempts':'self_introduction_attempts'
const entity=(kind:Kind)=>kind==='interview'?'interview_attempts':'self_introduction_attempts'
export const localServerIdMap={get(id:string){return read<string>(MAP_KEY)[id]},set(id:string,serverId:string){write(MAP_KEY,{...read<string>(MAP_KEY),[id]:serverId})}}
export type AttemptSyncStatus='local_only'|'pending'|'uploading_audio'|'synced'|'failed'
export const trainingSyncMeta={get(id:string){return read<{status:AttemptSyncStatus;audioStatus?:AttemptSyncStatus}>(META_KEY)[id]??{status:'local_only' as const}},set(id:string,value:Partial<{status:AttemptSyncStatus;audioStatus:AttemptSyncStatus;error:string}>){write(META_KEY,{...read(META_KEY),[id]:{...read<{status:AttemptSyncStatus;audioStatus?:AttemptSyncStatus}>(META_KEY)[id],...value}});window.dispatchEvent(new Event('cabin:training-sync-changed'))}}

export function interviewAttemptToRow(value:InterviewAttempt,userId:string,serverId?:string):AttemptRow{const analysis=value.audioMetrics||value.speechMetrics||value.pronunciationAnalysis||value.contentAnalysis?{...value.analysis,audioMetrics:value.audioMetrics,speechMetrics:value.speechMetrics,pronunciationAnalysis:value.pronunciationAnalysis,contentAnalysis:value.contentAnalysis}:value.analysis;return{id:serverId??(isUuid(value.id)?value.id:crypto.randomUUID()),user_id:userId,legacy_id:value.id,question_id:value.questionId,category:value.category,transcript:value.transcript,duration_seconds:value.durationSeconds,analysis,target_airline_id:value.targetAirlineId??null,experience_id:value.experienceId?localServerIdMap.get(value.experienceId)??null:null,experience_snapshot:value.experienceSnapshot??{},attempt_number:value.attemptNumber,previous_attempt_id:value.previousAttemptId?localServerIdMap.get(value.previousAttemptId)??null:null,completed:value.completed,audio_path:(value as InterviewAttempt&{audioPath?:string}).audioPath??null,created_at:value.createdAt,updated_at:value.createdAt,client_updated_at:value.createdAt,schema_version:1}}
export function interviewAttemptFromRow(row:AttemptRow):InterviewAttempt{localServerIdMap.set(row.legacy_id,row.id);const stored=row.analysis&&typeof row.analysis==='object'?row.analysis as Record<string,unknown>:{};const{audioMetrics,speechMetrics,pronunciationAnalysis,contentAnalysis,...analysis}=stored;return{id:row.legacy_id,questionId:row.question_id??'',category:row.category as InterviewAttempt['category'],transcript:row.transcript,durationSeconds:row.duration_seconds,analysis:analysis as InterviewAttempt['analysis'],audioMetrics:audioMetrics as InterviewAttempt['audioMetrics'],speechMetrics:speechMetrics as InterviewAttempt['speechMetrics'],pronunciationAnalysis:pronunciationAnalysis as InterviewAttempt['pronunciationAnalysis'],contentAnalysis:contentAnalysis as InterviewAttempt['contentAnalysis'],targetAirlineId:row.target_airline_id??undefined,experienceId:row.experience_id??undefined,experienceSnapshot:row.experience_snapshot as InterviewAttempt['experienceSnapshot'],attemptNumber:row.attempt_number,previousAttemptId:row.previous_attempt_id??undefined,completed:row.completed,createdAt:row.created_at,audioPath:row.audio_path??undefined} as InterviewAttempt&{audioPath?:string}}
export function selfIntroductionAttemptToRow(value:SelfIntroductionAttempt,userId:string,serverId?:string):AttemptRow{const analysis=value.audioMetrics||value.speechMetrics||value.pronunciationAnalysis||value.practiceLanguage?{...value.analysis,audioMetrics:value.audioMetrics,speechMetrics:value.speechMetrics,pronunciationAnalysis:value.pronunciationAnalysis,practiceLanguage:value.practiceLanguage}:value.analysis;return{id:serverId??(isUuid(value.id)?value.id:crypto.randomUUID()),user_id:userId,legacy_id:value.id,transcript:value.transcript,duration_seconds:value.durationSeconds,analysis,target_airline_id:value.targetAirlineId??null,experience_id:value.experienceId?localServerIdMap.get(value.experienceId)??null:null,experience_snapshot:value.experienceSnapshot??{},attempt_number:value.attemptNumber,previous_attempt_id:value.previousAttemptId?localServerIdMap.get(value.previousAttemptId)??null:null,completed:value.completed,audio_path:(value as SelfIntroductionAttempt&{audioPath?:string}).audioPath??null,created_at:value.createdAt,updated_at:value.createdAt,client_updated_at:value.createdAt,schema_version:1}}
export function selfIntroductionAttemptFromRow(row:AttemptRow):SelfIntroductionAttempt{localServerIdMap.set(row.legacy_id,row.id);const stored=row.analysis&&typeof row.analysis==='object'?row.analysis as Record<string,unknown>:{};const{audioMetrics,speechMetrics,pronunciationAnalysis,practiceLanguage,...analysis}=stored;const challengeAnalysis=analysis as SelfIntroductionAttempt['analysis'],targetSeconds=challengeAnalysis.challenge?.timing.targetSeconds;return{id:row.legacy_id,transcript:row.transcript,durationSeconds:row.duration_seconds,analysis:challengeAnalysis,audioMetrics:audioMetrics as SelfIntroductionAttempt['audioMetrics'],speechMetrics:speechMetrics as SelfIntroductionAttempt['speechMetrics'],pronunciationAnalysis:pronunciationAnalysis as SelfIntroductionAttempt['pronunciationAnalysis'],practiceLanguage:practiceLanguage==='en'?'en':practiceLanguage==='ko'?'ko':undefined,targetAirlineId:row.target_airline_id??undefined,experienceId:row.experience_id??undefined,experienceSnapshot:row.experience_snapshot as SelfIntroductionAttempt['experienceSnapshot'],attemptNumber:row.attempt_number,previousAttemptId:row.previous_attempt_id??undefined,completed:row.completed,createdAt:row.created_at,audioPath:row.audio_path??undefined,targetSeconds,challengeType:targetSeconds?`self_intro_${targetSeconds}`:undefined} as SelfIntroductionAttempt&{audioPath?:string}}

export interface AttemptRepository<T extends Attempt>{list():Promise<T[]>;create(value:T):Promise<T>;update(id:string,patch:Partial<T>):Promise<T>;delete(id:string):Promise<void>}
export interface InterviewAttemptRepository extends AttemptRepository<InterviewAttempt>{}
export interface SelfIntroductionRepository extends AttemptRepository<SelfIntroductionAttempt>{}
export interface AudioRepository{get(id:string):Promise<Blob|null>;delete(id:string):Promise<void>}
class LocalAttemptRepository<T extends Attempt> implements AttemptRepository<T>{constructor(private kind:Kind){}list(){return Promise.resolve((this.kind==='interview'?loadInterviewAttempts():loadSelfIntroductionAttempts()) as T[])}async create(value:T){this.save(value);return value}async update(id:string,patch:Partial<T>){const value=(await this.list()).find(x=>x.id===id);if(!value)throw new Error('not_found');const next={...value,...patch,id} as T;this.save(next);return next}async delete(id:string){const values=(await this.list()).filter(x=>x.id!==id);localStorage.setItem(this.kind==='interview'?'cabin-interview-attempts-v1':'cabin-self-introduction-attempts-v1',JSON.stringify(values));await deleteAttemptAudio(id)}private save(value:T){if(this.kind==='interview')saveInterviewAttempt(value as InterviewAttempt);else saveSelfIntroductionAttempt(value as SelfIntroductionAttempt)}}
export class LocalInterviewAttemptRepository extends LocalAttemptRepository<InterviewAttempt> implements InterviewAttemptRepository{constructor(){super('interview')}}
export class LocalSelfIntroductionRepository extends LocalAttemptRepository<SelfIntroductionAttempt> implements SelfIntroductionRepository{constructor(){super('self_introduction')}}
class SupabaseAttemptRepository<T extends Attempt> implements AttemptRepository<T>{constructor(private kind:Kind,private user:User){}private client(){const c=getSupabaseBrowserClient();if(!c)throw new Error('not_configured');return c}private row(value:T){return this.kind==='interview'?interviewAttemptToRow(value as InterviewAttempt,this.user.id,localServerIdMap.get(value.id)):selfIntroductionAttemptToRow(value as SelfIntroductionAttempt,this.user.id,localServerIdMap.get(value.id))}private from(row:AttemptRow){return(this.kind==='interview'?interviewAttemptFromRow(row):selfIntroductionAttemptFromRow(row)) as T}async list(){const{data,error}=await this.client().from(table(this.kind)).select('*').eq('user_id',this.user.id).is('deleted_at',null).order('created_at',{ascending:false});if(error)throw error;return(data as unknown as AttemptRow[]).map(x=>this.from(x))}async create(value:T){const{data,error}=await this.client().from(table(this.kind)).upsert(this.row(value) as never,{onConflict:'user_id,legacy_id'}).select('*').single();if(error)throw error;return this.from(data as unknown as AttemptRow)}async update(id:string,patch:Partial<T>){const current=(await this.list()).find(x=>x.id===id);if(!current)throw new Error('not_found');return this.create({...current,...patch,id} as T)}async delete(id:string){const serverId=localServerIdMap.get(id);const q=this.client().from(table(this.kind)).update({deleted_at:new Date().toISOString()} as never).eq('user_id',this.user.id);const{error}=serverId?await q.eq('id',serverId):await q.eq('legacy_id',id);if(error)throw error}}
export class SupabaseInterviewAttemptRepository extends SupabaseAttemptRepository<InterviewAttempt> implements InterviewAttemptRepository{constructor(user:User){super('interview',user)}}
export class SupabaseSelfIntroductionRepository extends SupabaseAttemptRepository<SelfIntroductionAttempt> implements SelfIntroductionRepository{constructor(user:User){super('self_introduction',user)}}
export class HybridInterviewAttemptRepository extends LocalInterviewAttemptRepository{constructor(readonly user:User){super()}}
export class HybridSelfIntroductionRepository extends LocalSelfIntroductionRepository{constructor(readonly user:User){super()}}
export class LocalAudioRepository implements AudioRepository{get(id:string){return loadAttemptAudio(id)};delete(id:string){return deleteAttemptAudio(id)}}
export class SupabaseAudioRepository{async playback(path:string){return storageService.createPlaybackUrl(path)};async delete(path:string){return storageService.deleteAudio(path)}}
export class HybridAudioRepository extends LocalAudioRepository{}

// Audio processing consent does not grant persistent remote storage consent.
// Until a dedicated storage consent is introduced, raw recordings stay local.
export function hasExplicitRemoteAudioStorageConsent(){return false}

async function push(item:SyncQueueItem,user:User){const kind=item.entityType==='interview_attempts'?'interview':'self_introduction';if(item.operation==='delete')return kind==='interview'?new SupabaseInterviewAttemptRepository(user).delete(item.entityId):new SupabaseSelfIntroductionRepository(user).delete(item.entityId);if(item.operation==='upload_audio'){const blob=await loadAttemptAudio(item.entityId);if(!blob)throw new Error('local_audio_missing');const serverId=localServerIdMap.get(item.entityId)??item.entityId;const uploaded=await storageService.uploadAudio({userId:user.id,entityType:kind==='interview'?'interview':'self-introduction',entityId:serverId,file:blob,fileName:`${crypto.randomUUID()}.${blob.type.split('/')[1]||'webm'}`});const c=getSupabaseBrowserClient();if(!c)throw new Error('not_configured');const{error}=await c.from(table(kind)).update({audio_path:uploaded.path} as never).eq('user_id',user.id).eq('legacy_id',item.entityId);if(error)throw error;return}return kind==='interview'?new SupabaseInterviewAttemptRepository(user).create(item.payload as InterviewAttempt):new SupabaseSelfIntroductionRepository(user).create(item.payload as SelfIntroductionAttempt)}
async function repairRetryRelations(user:User){const client=getSupabaseBrowserClient();if(!client)return;for(const [kind,items] of [['interview',loadInterviewAttempts()],['self_introduction',loadSelfIntroductionAttempts()]] as const){for(const item of items){if(!item.previousAttemptId)continue;const serverId=localServerIdMap.get(item.id),parentId=localServerIdMap.get(item.previousAttemptId);if(!serverId||!parentId)continue;await client.from(table(kind)).update({previous_attempt_id:parentId} as never).eq('id',serverId).eq('user_id',user.id)}}}
let flushing=false
export function isRemoteAudioUploadBlocked(item:Pick<SyncQueueItem,'operation'>){return item.operation==='upload_audio'&&!hasExplicitRemoteAudioStorageConsent()}
export async function executeTrainingQueueOperation(item:Pick<SyncQueueItem,'operation'>,execute:()=>Promise<void>){if(isRemoteAudioUploadBlocked(item))return'blocked' as const;await execute();return'executed' as const}
export async function flushTrainingQueue(user:User){if(flushing||!navigator.onLine)return;flushing=true;try{for(const item of syncQueueRepository.list().filter(x=>x.userId===user.id&&['interview_attempts','self_introduction_attempts'].includes(x.entityType)&&['pending','failed'].includes(x.status))){const result=await executeTrainingQueueOperation(item,async()=>{try{syncQueueRepository.update(item.id,{status:'syncing'});if(item.operation==='upload_audio')trainingSyncMeta.set(item.entityId,{audioStatus:'uploading_audio'});await push(item,user);syncQueueRepository.update(item.id,{status:'completed'});trainingSyncMeta.set(item.entityId,item.operation==='upload_audio'?{audioStatus:'synced'}:{status:'synced'})}catch{syncQueueRepository.update(item.id,{status:'failed',retryCount:item.retryCount+1});trainingSyncMeta.set(item.entityId,item.operation==='upload_audio'?{audioStatus:'failed'}:{status:'failed'})}});if(result==='blocked'){syncQueueRepository.update(item.id,{status:'conflict',lastError:'remote_audio_storage_consent_required'});trainingSyncMeta.set(item.entityId,{audioStatus:'failed',error:'remote_audio_storage_consent_required'})}}await repairRetryRelations(user);syncQueueRepository.clearCompleted()}finally{flushing=false}}
export function queueTrainingAttempt(kind:Kind,value:Attempt,withAudio:boolean){void (async()=>{const c=getSupabaseBrowserClient();const user=c?(await c.auth.getUser()).data.user:null;if(!user||!getSupabaseRuntimeConfig().configured){trainingSyncMeta.set(value.id,{status:'local_only'});return}const uploadAudio=withAudio&&hasExplicitRemoteAudioStorageConsent();syncQueueRepository.enqueue({userId:user.id,entityType:entity(kind),entityId:value.id,operation:'create',payload:value,localUpdatedAt:value.createdAt});if(uploadAudio)syncQueueRepository.enqueue({userId:user.id,entityType:entity(kind),entityId:value.id,operation:'upload_audio',payload:{},localUpdatedAt:value.createdAt});trainingSyncMeta.set(value.id,{status:'pending',audioStatus:uploadAudio?'pending':undefined});void flushTrainingQueue(user)})()}
export function startTrainingSyncCoordinator(user:User){const online=()=>void flushTrainingQueue(user);window.addEventListener('online',online);void flushTrainingQueue(user);return()=>window.removeEventListener('online',online)}
export async function localTrainingMergeSummary(){const interviews=loadInterviewAttempts(),selfIntroductions=loadSelfIntroductionAttempts();let audio=0;for(const item of [...interviews,...selfIntroductions])if(await loadAttemptAudio(item.id))audio++;return{interviews,selfIntroductions,audio}}
export async function connectAllLocalTrainingRecords(){const c=getSupabaseBrowserClient(),user=c?(await c.auth.getUser()).data.user:null;if(!user)return{queued:0};const summary=await localTrainingMergeSummary();for(const item of summary.interviews)queueTrainingAttempt('interview',item,Boolean(await loadAttemptAudio(item.id)));for(const item of summary.selfIntroductions)queueTrainingAttempt('self_introduction',item,Boolean(await loadAttemptAudio(item.id)));return{queued:summary.interviews.length+summary.selfIntroductions.length}}
